import { bars, plot, step, story, strips, type LessonIntuition, type Point } from "./types";
const people: Point[] = [[160,58],[165,66],[170,68],[175,74],[180,74]];
const cloud: Point[] = [[1,1],[2,1.8],[3,3.2],[4,3.7],[5,5]];
const arc: Point[] = [[0,0],[1,3],[2,4],[3,3],[4,0]];
const line = [[160,60],[180,76]];

export const foundations: Record<string, LessonIntuition> = {
  "simple-linear-regression": story([
    "Suppose we know someone's height and want to estimate their weight. We have measured both quantities for five other people. Before choosing a formula, we can put those observations on a picture and ask what prediction rule might follow their pattern.",
    "A straight line gives us a simple rule to try. First we need to read a prediction from it and notice when that prediction misses. Then we can ask a computer to choose the line."
  ], [
    step("Give each measurement a job", "Each point represents one person. Height runs across the picture because it is the information we supply. Weight runs upward because it is what we want to predict. Those jobs stay fixed throughout the example.", plot("The five measured people used in the worked lesson.", people, "Height in centimetres", "Weight in kilograms")),
    step("Read an answer from a line", "The green line is a candidate rule. Choose a height, move upward to the line, and read the predicted weight. It can answer for heights between the measured people, which is why a rule is useful.", plot("A candidate line, chosen before measuring its errors.", people, "Height", "Weight", {paths:[line]})),
    step("Keep the observation and the guess separate", "Compare each point with the line directly above or below it. That vertical gap is the error in predicted weight. A point above the line means our guess was too low. The measurement stays fixed.", plot("Amber vertical segments connect observations to predictions.", people, "Height", "Weight", {paths:[line],guides:people.map(([x,y])=>[x,y,x,0.8*x-68])})),
    step("Make the rule answer to all five people", "Raising the line helps some guesses and hurts others. Tilting it changes the predicted increase in weight for extra height. Fitting chooses those two adjustments under an agreed way of counting all the errors.", plot("The observations and candidate line remain available for comparison.", people, "Height", "Weight", {paths:[line]}), {label:"Raise the candidate line",explanation:"The points stay fixed while every prediction increases. Several guesses are now too high. We need to consider every observation, rather than judging the rule from one convenient person.",scene:plot("Only the candidate line moved.",people,"Height","Weight",{paths:[[[160,67],[180,83]]]})})
  ], "Now we have a reason to measure the misses", ["The line has two settings: its tilt and vertical position. The observations let us judge them. We can now introduce slope, intercept, and squared error with a clear job for each.", "The full example fits those settings automatically. A good fit describes these measurements; it does not establish that height causes weight."]),

  "held-out-evaluation": story(["Imagine a student revising from a practice booklet. A perfect score could mean they learned the subject or memorized the answers. We need questions absent from practice to distinguish those possibilities.","A model has the same problem. Its training examples cannot, by themselves, tell us how well it will answer new examples."], [
    step("Set some questions aside first", "Before fitting, divide the observations into examples the model may learn from and examples reserved for evaluation. The reserved answers must stay outside the fitting process.", strips("Letters identify observations, not classes.",[["Available",["A","B","C","D","E","F"]],["Training",["A","B","D","F"]],["Reserved",["C","E"],[0,1]]])),
    step("Let the model learn from its own booklet", "Fitting adjusts the model using only training observations. It can check those answers repeatedly. A flexible model may become very good at those particular cases, so training performance is only part of the story.", strips("Reserved observations remain outside this route.",[["Training data",["A","B","D","F"]],["Fit",["Adjust the model"]],["Result",["A fitted model"]]],true)),
    step("Ask a question it has not practised", "Freeze the fitted model and give it a reserved input. Record its prediction before comparing it with the reserved answer. That observation did not help choose the model's fitted parameters.", strips("Prediction comes before reading the reserved answer.",[["Input",["Reserved observation C"]],["Frozen model",["Make a prediction"]],["Evaluate",["Compare with C's answer"]]],true)),
    step("Do not turn the exam into practice", "If we repeatedly choose settings because they score well on the same reserved examples, those examples guide our choices. They are validation data. Keep another test separate for the final assessment.", strips("Each set has a distinct job.",[["Training",["Fit parameters"]],["Validation",["Choose candidates"]],["Final test",["Assess the chosen procedure"]]]))
  ], "The split determines what a score can tell us", ["A score needs a description of which observations were excluded and what choices happened before scoring. Training and held-out errors answer different questions.","The experiment below compares them as model flexibility changes. Its result belongs to its particular data and split; another sample can give another score."]),

  "logistic-regression": story(["Suppose a model must choose between two supplied categories. Measurements offer evidence, but the groups may overlap. We would like the model to express uncertainty before turning its estimate into a decision.","There are three jobs to separate: collect evidence, express a probability estimate, and apply a decision threshold."], [
    step("Measurements provide evidence", "Height and weight are inputs in the teaching example; the supplied category is the training answer. Measurements can point toward a category without guaranteeing it. An immediate yes-or-no answer hides that uncertainty.", strips("A schematic classification task.",[["Inputs",["Height","Weight"]],["Question",["Which of the two supplied categories?"]]],true)),
    step("Combine the evidence into a score", "Each measurement receives a coefficient controlling its contribution. A separate offset establishes a starting point. Together they produce one score, which can move in either direction. It is not yet a probability.", strips("Fitting learns the coefficients and offset.",[["Contributions",["From height","From weight"]],["Combine",["Add the offset"]],["Result",["One unrestricted score"]]],true)),
    step("Convert the score smoothly", "An S-shaped function places the estimate between zero and one. Very negative and very positive scores approach opposite ends. Near the middle, a small score change noticeably changes the estimate.", plot("The sigmoid's shape, not a fit to a dataset.",[],"Score","Probability estimate",{paths:[Array.from({length:25},(_,i)=>{const x=i/3-4;return[x,1/(1+Math.exp(-x))];})]})),
    step("Choose the decision separately", "A threshold turns the estimate into a category. Moving that threshold changes decisions while the estimates stay fixed. The choice should reflect the consequences of the different mistakes.", strips("Illustrative estimates held fixed under two decision rules.",[["Estimate",["Low","Middle","High"]],["Permissive threshold",["No","Yes","Yes"],[1,2]],["Strict threshold",["No","No","Yes"],[2]]]))
  ], "The probability model and decision rule have different jobs", ["We can now name the linear score, sigmoid function, and threshold. Fitting adjusts the score's coefficients using labeled examples and a probability-based loss.","The full model shows the resulting estimates and boundary. Those estimates still need evaluation and calibration checks before we trust them as accurate frequencies."]),

  "judging-a-classifier": story(["A review system can miss a case needing attention or send an unnecessary alert. These are different mistakes. One percentage of correct answers does not tell us which mistake the system makes.","First sort predictions by what happened. Then choose a measurement that answers the question we care about."], [
    step("Keep the prediction beside the answer", "For one observation, record both the predicted decision and the known answer. Neither alone tells us whether the decision was useful. Together they identify the outcome.",strips("An illustrative review task.",[["Prediction",["Flag for review"]],["Known answer",["Review was needed"]]])),
    step("There are four possible outcomes", "A needed case can be found or missed. An unneeded case can be left alone or falsely flagged. Keep these in separate boxes so that one improvement cannot hide another kind of deterioration.",strips("These four boxes form the confusion matrix.",[["Review needed",["Flagged: found","Not flagged: missed"]],["Review not needed",["Flagged: false alarm","Not flagged: correctly left alone"]]])),
    step("Choose which group to ask about", "Someone opening alerts wants to know how often alerts are right. Someone responsible for finding needed cases wants to know how many were found. These questions start from different groups of observations.",strips("Precision and recall use different denominators.",[["Precision starts from",["All flagged cases"],[0]],["Recall starts from",["All cases needing review"],[0]]])),
    step("Follow both effects of a threshold change", "A more permissive threshold sends more cases for review. It can find additional needed cases while creating additional false alarms. Track both outcomes when deciding whether the change helped.",strips("A tradeoff to measure, without invented performance scores.",[["Stricter",["Fewer alerts","Potentially more missed cases"]],["More permissive",["More alerts","Potentially more false alarms"]]]))
  ],"Count the outcomes before naming the metric",["Precision, recall, specificity, and accuracy each summarize a particular part of the same basic evidence. Their formulas become readable once the question behind each fraction is clear.","The full classifier supplies actual predictions to count. Its threshold can change while its underlying scores remain fixed."]),
  "statistics": story(["Five people's measurements fit in a small table. Thousands do not. We need to describe where values gather, how much they differ, and what an observed group can tell us about a larger one.","Start with the observations. A summary is useful only when we know what information it keeps."],[
    step("A row is one person; a column is one quantity","Reading across describes one person. Reading down compares the same quantity across people. We will summarize one column before asking how the columns vary together.",strips("The five people used in the primer.",[["Heights, centimetres",["160","165","170","175","180"]],["Weights, kilograms",["58","66","68","74","74"]]])),
    step("A centre needs a spread beside it","Two groups can share a centre while one is tightly gathered and the other widely scattered. Reporting only their average would hide that difference. A spread measure answers a different question.",strips("Illustrative groups with the same centre and different spreads.",[["Close together",["9","10","11"]],["Farther apart",["2","10","18"]]])),
    step("Pair the columns to see a relationship","Put each person's measurements back together. In this sample, taller people tend to be heavier. Both the overall direction and the departures from it are visible. The pattern alone does not establish a cause.",plot("Every point keeps one person's measurements paired.",people,"Height","Weight")),
    step("Another sample can give another summary","The observed people are a sample. A different group will usually have different summaries. Sampling and probability help describe that variation and how cautiously we should extend a result to a population.",strips("Different hypothetical samples, not repeated measurements of the same people.",[["Sample one",["A","B","C"]],["Sample two",["D","E","F"]],["Question",["How much would the summary vary?"]]]))
  ],"Describe the sample, then consider uncertainty",["First we will calculate centres, spreads, and paired relationships for the measured group. Then probability and repeated sampling will help us ask what changes when another group is observed.","Keeping those questions separate prevents a sample average from quietly becoming a claim about everyone."]),
  "linear-algebra": story(["A person may arrive as height, weight, and age; an image arrives as many pixels. A model needs to keep related numbers together without losing what each position means.","Linear algebra describes those arrangements and the operations connecting them. We will start with the objects before the notation."],[
    step("Keep one observation together","Put a person's measurements in a fixed order. This ordered list is a vector. Exchanging height and age would change what it says, even though the same numbers remain.",strips("Illustrative measurements for one person.",[["Positions mean",["Height","Weight","Age"]],["Values",["170","68","30"]]])),
    step("Stack observations consistently","Give each person a row and each measurement a column. That rectangular arrangement is a matrix. Every added row must preserve the same column meanings.",strips("Rows identify people; the three columns retain their meanings.",[["Person A",["170","68","30"]],["Person B",["160","58","24"]],["Person C",["180","74","42"]]])),
    step("See what a transformation does","For a geometric vector, a rule can turn its direction or change its length. A matrix can encode that rule so we apply it consistently to other inputs. Here a chosen rotation turns the green direction into the rose direction.",plot("A geometric rotation, with no fitted model.",[],"First coordinate","Second coordinate",{paths:[[[0,0],[3,1]],[[0,0],[-1,3]]]})),
    step("Organize several weighted combinations","A model may need several answers from the same observation. Arrange each answer's weights consistently. Matrix multiplication organizes which weights meet which inputs and where each answer goes.",strips("Roles are shown before numerical multiplication.",[["Input",["Height","Weight","Age"]],["Separate rules",["Rule A","Rule B"]],["Output",["Answer A","Answer B"]]],true))
  ],"The notation describes recognizable arrangements",["A scalar is one value, a vector an ordered list, and a matrix a rectangular arrangement. Their dimensions tell us how many observations or coordinates an operation receives and returns.","We will build dot products and matrix multiplication from those objects, then use transformations and decompositions to describe structure in data."]),
  "calculus": story(["Imagine turning a knob and watching an error meter. We want the error to fall but do not know the best setting. A small change could tell us which way the meter responds.","Calculus makes that question precise: how does one quantity respond when another changes?"],[
    step("Start at one setting","The curve shows illustrative errors at different settings. The dot marks where we are now. Knowing the current error does not yet tell us which direction to move.",plot("A simple bowl-shaped error curve.",[[1,4]],"Knob setting","Error",{paths:[Array.from({length:61},(_,i)=>[i/10,(i/10-3)**2])]})),
    step("Compare a nearby reading","Move slightly right and check the meter. Here the error falls. Comparing the two nearby readings describes the average change across that small interval.",plot("Two nearby settings reveal a local response.",[[1,4],[1.5,2.25]],"Knob setting","Error",{paths:[Array.from({length:61},(_,i)=>[i/10,(i/10-3)**2])],guides:[[1,4,1.5,2.25]]})),
    step("Direction depends on where we stand","On the other side of the bowl, moving right increases the error. The local response belongs to the current setting. It is not one direction that works everywhere.",plot("The same curve inspected from its other side.",[[5,4]],"Knob setting","Error",{paths:[Array.from({length:61},(_,i)=>[i/10,(i/10-3)**2])]})),
    step("Direction and step size are different choices","A downhill direction suggests a small improvement. It does not guarantee an enormous move will help. A large step can cross the low point and climb the other side.",plot("Green shows a modest improvement; rose shows an overshoot.",[[1,4],[2,1],[6,9]],"Knob setting","Error",{paths:[[[1,4],[2,1]],[[1,4],[6,9]]]}))
  ],"A derivative answers the small-change question",["We will measure change across an interval, then shrink that interval to define an instantaneous rate. For several parameters, we collect their partial derivatives into a gradient.","For a sequence of operations, we connect local responses using the chain rule. Each formula will have a concrete question to answer."]),
  "centring-on-the-mean": story(["Suppose we want to describe how someone differs from a measured group. Raw height is measured from zero, far from everyone in the group. The average person may be a more useful reference.","Centring changes the reference point without changing who is taller or how far apart two people are."],[
    step("Begin with the original ruler","These heights use the ruler's original zero. That zero is not the centre of this particular group. Each position in the list identifies the same person throughout.",strips("The worked group's original heights.",[["Centimetres",["160","165","170","175","180"]]])),
    step("Put zero at the average","The average here is 170 centimetres. Make it the new zero. Values below it become negative and values above it become positive. We can now describe departure from the group.",strips("The same people, with a different reference.",[["Original",["160","165","170","175","180"],[2]],["Centred",["−10","−5","0","5","10"],[2]]])),
    step("Keep the gaps and ordering","The shortest person is still shortest. The gaps between people are unchanged. Moving the origin for everyone together did not stretch the ruler or add information about anyone.",strips("Identity and ordering survive the translation.",[["Before",["A","B","C","D","E"]],["After",["A","B","C","D","E"]]])),
    step("Reuse the training reference","When a new person arrives, use the average already stored from training. Recalculating the reference for each arriving group would change the coordinate system the model learned to read.",strips("The training reference travels with the model.",[["Training",["Learn and store the mean"]],["Prediction",["Reuse the stored mean"]]],true))
  ],"Subtraction has a geometric purpose",["Subtracting the training mean places the origin at the average training observation. Scaling is a separate operation that changes the unit rather than just the starting point.","The detailed examples show which calculations depend on that origin and which remain unchanged."]),
  "the-standard-score": story(["Being ten units above average means something different in a tightly gathered group than in a widely scattered one. We need a ruler that accounts for the variation in the quantity we measure.","A standard score chooses the average as zero, then uses the training standard deviation as the unit."],[
    step("Raw units do not describe unusualness","An orchard records trunk girth and water supplied in different units. Larger written numbers do not automatically deserve more influence. Their size partly comes from the choice of unit.",strips("Two physical quantities with different recording units.",[["Trunk girth",["Millimetres"]],["Water supplied",["Metres"]]])),
    step("First describe departure from average","Put the training average at zero. Negative coordinates now mean below average and positive ones mean above it. The original units and unequal spreads still remain.",strips("Centring identifies the direction of departure.",[["Below average",["Negative"]],["At average",["Zero"]],["Above average",["Positive"]]])),
    step("Use spread as the unit","Express each departure in units of that column's standard deviation. One unit above average then has the same numerical description in either column, although the physical measurements differ.",strips("A common description of relative position.",[["Description",["Below average","At average","Above average"]],["Standardized coordinate",["−1","0","+1"]]])),
    step("Store both parts of the ruler","Keep the training mean and standard deviation for later inputs. Standardizing changes centre and scale while preserving the distribution's shape. It does not make every dataset bell-shaped.",strips("Both stored quantities are reused during prediction.",[["Learn from training",["Mean","Standard deviation"]],["Apply later",["Same centre","Same scale"]]],true))
  ],"The formula combines two separate changes",["Subtracting changes the reference point; dividing changes the unit. We will calculate those steps separately before combining them.","The orchard example shows how standardized coordinates affect neighbour comparisons. A constant column requires an explicit rule because its standard deviation is zero."]),
  "feature-scaling": story(["Rewrite someone's height from metres into centimetres. The person stays the same, but the number becomes much larger. A distance calculation can suddenly give height much more influence.","Scaling lets us choose how numerical differences should enter a model instead of letting recording units make that choice silently."],[
    step("The person is different from the written number","A unit conversion changes the record without changing the observation. We should understand whether our prediction rule is meant to notice that change.",strips("Two records of the same illustrative height.",[["Metres",["1.70"]],["Centimetres",["170"]]])),
    step("Large coordinate differences can dominate","A model reads the supplied numbers. It does not know why one column's differences are much larger. A comparison can be dominated by scale rather than predictive usefulness.",bars("Illustrative contribution sizes, not measured feature importance.",[["First coordinate",9,"Large contribution"],["Second coordinate",1,"Small contribution"]])),
    step("Choose what the ruler should preserve","A standardizer uses average and spread. Range scaling uses endpoints. A robust alternative uses the middle of the distribution. These choices behave differently when an extreme observation arrives.",strips("Different rulers answer different questions.",[["Standard scaling",["Mean","Standard deviation"]],["Range scaling",["Minimum","Maximum"]],["Robust scaling",["Median","Middle spread"]]])),
    step("Carry the same ruler into prediction","Fit the transformation on training data and keep it fixed for later inputs. A new extreme can fall outside the training range. It should not silently change the ruler during evaluation.",strips("Training determines the transformation on both routes.",[["Training",["Fit scaler","Fit model"]],["New input",["Use stored scaler","Use fitted model"]]]))
  ],"Scaling is part of defining the input",["The detailed lesson compares specific transformations and the models that notice them. The goal is a sensible representation, not a universally best scaling rule.","Evaluate preprocessing together with fitting. Scaling alone does not establish which feature matters for prediction."]),
  "polynomial-features": story(["A thrown ball rises and then falls. A straight line can rise or fall, but cannot follow both parts of the trajectory. Could another description of time give a simple model more useful shapes to work with?", "Polynomial features create additional inputs from measurements we already have."],[
    step("See the pattern a line misses","These illustrative points rise and then fall. A horizontal or sloping line leaves a systematic pattern of misses. The limitation is the available shape, not merely an unlucky tilt.",plot("A hand-built trajectory and a candidate straight rule.",arc,"Time","Height",{paths:[[[0,2],[4,2]]]})),
    step("Give the model another building block","Alongside time, create an input that grows like time squared. The two columns change differently as time advances, so the model can give them separate contributions.",strips("Both features come from the same original clock reading.",[["Original",["Time"]],["Expanded",["Time","Time squared"]]],true)),
    step("Combine those blocks into a curve","A rising time contribution and a negative squared-time contribution can make the result rise and then fall. The model still chooses coefficients, but the graph against the original time axis is curved.",plot("A quadratic can express this illustrative trajectory.",arc,"Time","Height",{paths:[Array.from({length:17},(_,i)=>{const t=i/4;return[t,4*t-t*t];})]})),
    step("More shapes include more ways to follow noise","Higher powers add flexibility. That may express useful structure, but it can also follow accidental irregularities in a sample. Check predictions on excluded observations before treating the extra complexity as an improvement.",strips("Flexibility is a choice to evaluate.",[["Lower degree",["Fewer shapes"]],["Higher degree",["More shapes","More ways to follow noise"]]]))
  ],"The new inputs create the shape choices",["We will now introduce powers and products as features, then show how a linear model chooses their coefficients. Linear in the coefficients does not require a straight graph in the original measurements.","The full experiments examine useful expansions, their storage cost, and the difference between fitting a sample and predicting new data."]),
  "multiple-polynomial-regression": story(["Height provides one clue about weight. Another measurement may distinguish people whose heights are the same. We may also need a relationship whose effect changes as an input grows.","Separate adding a new measurement from calculating a new feature from measurements already available."],[
    step("One input offers one kind of evidence","A height-only rule must give the same prediction to two people of the same height. It cannot use a difference that was never supplied.",strips("The input limits the distinctions a model can make.",[["Person A",["Same height"]],["Person B",["Same height"]],["Height-only rule",["Same prediction"]]])),
    step("A second measurement can distinguish the cases","Add waist girth. The model can assign a separate contribution to each measurement and give different answers when the second measurement differs.",strips("Measured inputs now provide two kinds of evidence.",[["Person A",["Height","Smaller waist"]],["Person B",["Height","Larger waist"]]])),
    step("An extra column need not be a new measurement","Create height squared or a product of height and waist. This changes the available rule shapes using information already present. It does not collect another observation about the person.",strips("Measured features and derived features have different origins.",[["Measured",["Height","Waist"]],["Derived",["Height squared","Height times waist"]]])),
    step("Judge the contributions together","The fitting objective reads the combined prediction. Changing one coefficient can change what the others need to do, especially when features carry overlapping information.",strips("Several feature contributions produce one answer.",[["Inputs",["Measured features","Derived features"]],["Combine",["Separate coefficients","Offset"]],["Result",["One prediction"]]],true))
  ],"Every added column needs a reason",["We can now arrange features as matrix columns and write the combined prediction. Matrix notation organizes the same job of combining evidence.","The later sections examine redundant inputs, flexibility, and evaluation. More columns do not automatically provide more useful information."]),
  "gradient-descent-regression": story(["Suppose a model has adjustable settings and an error meter, but no convenient formula giving the best settings immediately. We can still improve it by finding a direction, taking a small step, and checking the result.","For a line, the settings control its tilt and vertical position. First connect changing those settings with changing a visible prediction."],[
    step("A setting identifies one candidate line","The observations stay fixed while the prediction rule changes. Choosing one line means choosing its settings. We need a way to judge that candidate before deciding how to move it.",plot("A deliberately low candidate on the measured five.",people,"Height","Weight",{paths:[[[160,50],[180,66]]]})),
    step("Ask what a small adjustment would do","Most observations lie above this candidate. A small upward change is worth investigating. A gradient answers this local question precisely for every adjustable parameter under the chosen error measure.",plot("A modest upward move brings this candidate closer.",people,"Height","Weight",{paths:[[[160,55],[180,71]]]})),
    step("Recheck at the new setting","After an update, the useful direction can change. Evaluate again, calculate the current direction, and move again. Repeating this loop gradually changes the fitted rule.",strips("Each direction belongs to the current settings.",[["Current model",["Make predictions"]],["Current errors",["Find a downhill direction"]],["Updated model",["Evaluate again"]]],true)),
    step("A large step can pass the useful region","The learning rate controls the distance moved. Even if a small upward move helps, an enormous one may make every prediction too high. Direction and step size are separate choices.",plot("This candidate moved too far upward.",people,"Height","Weight",{paths:[[[160,80],[180,96]]]}))
  ],"The derivative chooses a direction; the learning rate sets the distance",["The detailed lesson puts the line's parameters on their own coordinate plot. Error becomes a surface, and moving downhill corresponds to changing prediction lines.","We will calculate one update before running many. Convergence, stopping, and feature scaling become easier to interpret once that step is concrete."]),
  "pca": story(["When two measurements tend to rise together, storing both may describe much of the same variation twice. Could we give each observation one position along the main direction of the cloud instead?","Imagine points casting shadows onto a ruler. Different ruler directions preserve different amounts of their spread. PCA chooses directions from that spread without consulting labels."],[
    step("Inspect the cloud before choosing a ruler","The points stretch mainly along a diagonal. Their two coordinates overlap in the variation they describe. We want a direction following that cloud before reducing it to one coordinate.",plot("A hand-built cloud with a clear main direction.",cloud,"First measurement","Second measurement")),
    step("Drop each point onto a candidate direction","Projection finds a point's position along the ruler while discarding its perpendicular displacement. The dashed segments show what keeping only the projected position would lose.",plot("Green is the candidate ruler; amber marks discarded displacement.",cloud,"First measurement","Second measurement",{paths:[[[0,0],[6,6]]],guides:cloud.map(([x,y])=>[x,y,(x+y)/2,(x+y)/2])})),
    step("Compare a poorly aligned ruler","Across the narrow direction, the projected points bunch together. That ruler retains less variation. The first principal component chooses the direction with greatest projected variance after centring.",plot("This ruler runs across the narrow direction of the same cloud.",cloud,"First measurement","Second measurement",{paths:[[[0,6],[6,0]]],guides:cloud.map(([x,y])=>{const t=(x-y)/2;return[x,y,3+t,3-t];})})),
    step("Keep the information needed to reconstruct","One position per observation is a deliberate approximation. Drawing it back requires the retained direction and original centre. Displacement perpendicular to the retained direction is gone.",strips("Compression keeps some information and discards the rest.",[["Per observation",["One projected position"]],["Stored with the transformation",["Direction","Original centre"]],["Discarded",["Perpendicular displacement"]]]))
  ],"Now the matrix has a geometric question to answer",["Covariance and eigenvectors provide a way to find the ruler we just described. The geometric objective comes first: preserve the greatest projected spread.","PCA preserves variance in its chosen coordinates. Small-variance information can still matter for prediction, so evaluate the reduced representation for the task that uses it."]),
  "ridge-lasso": story(["A flexible model can follow accidental noise and rely on large contributions that nearly cancel. Its training predictions may look good while small data changes produce a very different rule.","Regularization adds a preference for restrained coefficients. We will see that tradeoff before writing the penalty formulas."],[
    step("A close training fit is only one goal","An elaborate rule has many ways to follow a small sample. Training error rewards those details whether or not they repeat in new data. Stability asks a different question.",strips("Two goals that can pull in different directions.",[["Fit this sample",["Small training errors"]],["Remain stable",["Limited unnecessary sensitivity"]]])),
    step("Notice contributions pulling against each other","Similar features can receive large coefficients with opposite signs. Their contributions may cancel on observed cases. A modest final prediction can therefore hide large individual contributions.",bars("Illustrative signed contributions, not a fitted result.",[["First contribution",9,"Large positive"],["Second contribution",-8,"Large negative"]])),
    step("Charge for using large coefficients","A penalty makes coefficient size costly as well as useful. Fitting balances prediction error against that cost. A stronger penalty may accept more training error for a more restrained combination.",strips("Regularization changes the fitting objective.",[["Without penalty",["Judge prediction errors"]],["With penalty",["Judge errors","Charge for coefficient size"]]])),
    step("Different penalties produce different restraint","Ridge tends to shrink coefficients smoothly. Lasso can set some exactly to zero. Their strength needs evaluation on excluded observations; neither guarantees better future predictions.",strips("Typical effects, not promises for every dataset.",[["Ridge",["Smaller contributions","Often keeps many inputs"]],["Lasso",["Smaller contributions","Can remove contributions"]]]))
  ],"A penalty is a preference to evaluate",["The squared-coefficient and absolute-value penalties explain the different behaviour of ridge and lasso. Their formulas now have a visible purpose.","Use suitable feature scales and validation data to choose the strength. The full experiments show actual coefficient paths and prediction errors."]),
};

