import { bars, plot, step, story, strips, tiles, type LessonIntuition } from "./types";

export const modern: Record<string, LessonIntuition> = {
  "transformer-blocks": story([
    "Consider the sentence: The cat lay on the blanket because it was tired. To make sense of it, we need to connect the final words with something mentioned earlier. Reading each word in isolation would leave out that connection.",
    "We already have an operation that lets tokens gather information from other tokens: attention. Now we need to place it inside a larger component that can preserve information, combine what it gathers, and pass the result onward. That component is a transformer block."
  ], [
    step("Give every token a place to keep information", "Each token receives a vector, a row of numbers that the model can update. Position information accompanies that row so the model can distinguish the order of the tokens. These rows are the information being processed, not separate little models.", strips("A schematic view of the rows before a block.", [["Token", ["cat", "was", "tired"]], ["Its representation", ["Row for cat", "Row for was", "Row for tired"]]])),
    step("Let a row gather relevant context", "Attention compares the current row with permitted rows and combines their value vectors. In a decoder used to predict the next token, a row can read earlier positions and itself. It cannot read later positions, because that would reveal the continuation we want it to predict.", strips("The highlighted rows are available to the middle position.", [["Reading was", ["cat", "was", "tired"], [0, 1]], ["Contribution", ["Context gathered by attention"]]])),
    step("Keep the original information alongside the contribution", "Attention contributes an update. We add it to the row that entered the branch, using a residual connection. This gives later operations access to the earlier representation as well as the newly gathered context. Normalization helps control the scale of the values entering the branch.", strips("The shortcut and attention contribution meet at an addition.", [["Shortcut", ["Original row"]], ["Attention branch", ["Context contribution"]], ["Combined", ["Updated row"]]], true)),
    step("Process what each row now contains", "A feed-forward network applies the same learned transformation to each updated row separately. It combines coordinates within a row; attention was the operation that exchanged information between rows. Another residual connection adds this new contribution before the next block.", strips("Two different jobs inside one block.", [["Across positions", ["Attention gathers context"]], ["Within each position", ["Feed-forward network processes coordinates"]], ["Next block", ["Receives the resulting rows"]]], true))
  ], "Now assemble the block in the order information travels", [
    "The numerical example follows those connections through one small block. Change the last token and check that earlier rows cannot change through access to the future.",
    "Its randomly initialized parameters expose the architecture. Learning useful representations requires training, which the next-token lesson explains."
  ]),
  "next-token-prediction": story([
    "If we read The cat sat on the, we can suggest several words that might come next. We use the words already present to decide which continuations make sense. A language model turns that kind of continuation task into a numerical prediction.",
    "We need three things: the text the model is allowed to read, a set of possible next tokens, and a way to compare its prediction with the token that actually followed. Repeated over many examples, that comparison provides a training signal."
  ], [
    step("Hide the continuation we want to predict", "Start with a piece of existing text. Show the model a prefix and reserve the following token as the target. We do not need a person to label each next word; its position in the original text supplies the target.", strips("One training example taken from an existing sentence.", [["Visible prefix", ["the", "cat"]], ["Hidden next token", ["sat"]]])),
    step("Keep several continuations possible", "A model returns a score for every vocabulary token. Softmax converts the scores to probabilities. Even when the training text uses sat, slept could be a reasonable continuation in another sentence. We are fitting a distribution, not declaring that only one sentence can exist.", bars("Illustrative probabilities, assigned to show alternatives.", [["sat", 0.5, "50%"], ["slept", 0.3, "30%"], ["ran", 0.2, "20%"]])),
    step("Measure the probability given to the observed token", "The training objective asks how much probability the model assigned to the actual next token. Low probability incurs a larger loss. Gradients then tell the optimizer how to adjust parameters so the model does better on this kind of example.", strips("Prediction, observation, and correction have separate roles.", [["Model", ["Probabilities for candidate tokens"]], ["Text", ["Observed target: sat"]], ["Learning", ["Measure loss", "Adjust parameters"]]], true)),
    step("Create another target at every position", "The same sentence provides several prefix-and-target pairs. A causal mask lets a transformer process their input positions together while keeping each position from reading its own future target. Across a corpus, the model repeatedly practices the same task on different contexts.", strips("Targets are shifted one position beyond their inputs.", [["Input positions", ["<start>", "the", "cat", "sat"]], ["Target positions", ["the", "cat", "sat", "<end>"]]]))
  ], "The loss makes a continuation task trainable", [
    "We will calculate the probability and loss at each target, then separate training from generating new text.",
    "A large language model extends this setup with many parameters, many examples, and substantial computation. Those resources do not change what the next-token target means."
  ]),
  "autoregressive-generation": story([
    "A next-token model gives us a distribution for one following token. A reader asking for a paragraph needs much more than one token. How do we turn that single prediction into a longer response?",
    "We can repeat the operation. Select a token, add it to the text we already have, and ask the model for the next distribution. Each choice becomes part of the context for the choices that follow."
  ], [
    step("Start with the user's text", "The prompt supplies the initial context. The tokenizer converts it into token IDs, and the model reads the whole available prefix. We use a short sentence here so the growing context is easy to follow.", strips("Illustrative starting context.", [["Prefix", ["the", "cat"]], ["Next position", ["?"]]])),
    step("Choose from the first distribution", "The model produces possible next tokens and their probabilities. A selection rule chooses one. Always selecting the largest probability is called greedy decoding; sampling instead makes a random choice according to the distribution.", strips("The choice shown here is illustrative, not a trained model result.", [["Candidates", ["sat", "slept", "ran"], [0]], ["Selected", ["sat"]]])),
    step("Make the selected token part of the input", "Now the prefix includes sat. The next forward pass therefore answers a different question: what follows this longer prefix? The model does not need to update its weights to do this. The input changes while the parameters stay fixed.", strips("The new token becomes visible on the next pass.", [["Before selection", ["the", "cat"]], ["After appending", ["the", "cat", "sat"], [2]], ["Next position", ["?"]]])),
    step("Stop when the response reaches a boundary", "Repeat until an end token is selected or a length limit is reached. A different early choice can produce a different later context and continuation. The loop has no guarantee that a plausible sequence is factually correct.", strips("A loop needs a stopping rule.", [["Continue", ["Predict", "Select", "Append"]], ["Stop", ["End token", "Length limit"]]]))
  ], "Follow the changing prefix, not changing weights", [
    "The full example runs this loop through the SDK's tiny untrained decoder and displays every prefix and selection probability.",
    "Its incoherent output is useful here: the loop alone cannot supply learned language. Architecture, training, and token selection play different roles."
  ]),
  "sampling-and-temperature": story([
    "Suppose a model thinks both The cat sat and The cat slept are plausible continuations. Always choosing the most probable token can repeat the same wording. Choosing any token equally would ignore what the model learned. We need a way to control how we select from its predictions.",
    "Temperature changes how concentrated the probabilities are. A second control, top-p, restricts sampling to a group of likely candidates. Neither control trains the model or adds new knowledge."
  ], [
    step("Begin with more than one plausible choice", "A prediction distribution divides probability among vocabulary tokens. Sampling draws from that distribution, so a less probable token can still be selected. A token's probability describes its share of repeated draws, not a guarantee about one draw.", bars("An assigned distribution for intuition.", [["sat", 0.5, "50%"], ["slept", 0.3, "30%"], ["ran", 0.15, "15%"], ["sang", 0.05, "5%"]])),
    step("Make the leading choices more or less dominant", "A lower positive temperature makes high-scoring tokens more dominant. A higher temperature spreads probability more evenly. The order of the candidates stays the same. Think of this as changing the strength of the preference, not changing which token ranks first.", strips("The direction of the change, before calculating it.", [["Lower temperature", ["More concentrated shares"]], ["Higher temperature", ["More even shares"]]])),
    step("Choose a candidate set by cumulative probability", "Top-p sorts candidates from most to least probable and keeps adding them until their combined probability reaches a chosen threshold. It includes the token that crosses the threshold. The number retained depends on how concentrated this particular distribution is.", bars("With a threshold of 80%, the first two assigned shares fill the candidate set.", [["sat, retained", 0.5, "50%"], ["slept, retained", 0.3, "30%"], ["ran, excluded", 0.15, "15%"], ["sang, excluded", 0.05, "5%"]])),
    step("Sample again within the retained set", "Excluded candidates receive no chance of selection. The retained probabilities are rescaled to total one before the random draw. This changes the selection distribution, so it is useful to inspect both the original shares and the final ones.", strips("The order of operations in this implementation.", [["Model output", ["Logits"]], ["Selection policy", ["Temperature", "Top-p filter", "Renormalize", "Sample"]]], true))
  ], "Compare both controls on the same scores", [
    "The table below holds four logits fixed. It shows the temperature-scaled distribution, which candidates survive top-p, and the final probabilities.",
    "Increasing variety is a selection preference. It does not measure creativity, correctness, or quality by itself."
  ]),
  "autoencoders": story([
    "Imagine recording two sensors that usually move together. Saving every reading from both might be wasteful if one shared value describes most of their behavior. But if the sensors disagree, a single value may lose the difference. What information should a compact representation preserve?",
    "An autoencoder tackles this by trying to reconstruct its input from a smaller or otherwise constrained code. The reconstruction tells us whether the information kept in that code was enough for the task."
  ], [
    step("Look for structure we can reuse", "When both sensor readings are similar, observations lie near a diagonal line. A position along that line can describe their shared level. The important starting point is a pattern in the data, not the assumption that all information can always be compressed.", plot("Illustrative readings that move together.", [[0,0],[1,1],[2,2],[3,3]], "Sensor A", "Sensor B", { paths: [[[0,0],[3,3]]], equalScale: true })),
    step("Use an encoder to make a compact code", "An encoder maps the input readings to a code. In our deliberately simple example, it keeps their average. Both readings influence this number, but the code no longer records them separately.", strips("Two input entries become one code entry.", [["Input", ["Sensor A", "Sensor B"]], ["Encoder", ["Keep their average"]], ["Code", ["One shared level"]]], true)),
    step("Ask a decoder to reconstruct the input", "The decoder maps the code back to the original number of entries. Our chosen decoder copies the shared level into both readings. When the input readings are equal, this reconstruction preserves them exactly.", strips("Returning to the original width does not restore lost information automatically.", [["Code", ["Shared level"]], ["Decoder", ["Copy into each output"]], ["Reconstruction", ["Estimated A", "Estimated B"]]], true)),
    step("Expose the information the code discarded", "Now let one sensor read above the shared level and the other below it. Their average stays the same, so the encoder produces the same code. The decoder has no way to distinguish this observation from equal readings with that average. Reconstruction error makes this loss visible.", plot("The off-diagonal input and its reconstruction are different observations.", [[2,0,0],[1,1,1]], "Sensor A", "Sensor B", { paths: [[[0,0],[3,3]]], guides: [[2,0,1,1]], labels: ["Input", "Reconstruction"], equalScale: true }))
  ], "Train the code by asking what it can reconstruct", [
    "A learned autoencoder adjusts its encoder and decoder together to reduce reconstruction error under a constraint. The example fixes both transformations so the lost difference is easy to see.",
    "We will then ask why reconstructing inputs does not automatically give us a reliable way to generate new ones."
  ]),
  "variational-autoencoders": story([
    "An autoencoder gives each input a code. We might try generating a new example by choosing a new code and decoding it. But which codes should we choose? A decoder trained on isolated codes may behave poorly in the spaces between them.",
    "A variational autoencoder gives us a more deliberate arrangement. For each input, the encoder describes a distribution of possible codes. Training balances reconstruction with a preference for code distributions that stay close to a simple shared prior."
  ], [
    step("Replace one code with a distribution of codes", "Instead of emitting a single latent value, the encoder describes a range of likely values. In the Gaussian case, each coordinate has a mean and a standard deviation. The mean sets the center; the deviation describes how spread out possible samples are.", strips("Two outputs describe one latent coordinate.", [["Encoder reads", ["One input example"]], ["Encoder returns", ["Mean", "Standard deviation"]], ["These describe", ["A distribution of possible codes"]]], true)),
    step("Draw a code before decoding", "A sample gives the decoder one concrete code to use. Different samples from the same distribution can produce different reconstructions. The reconstruction part of training asks the encoder and decoder to keep the input recoverable despite this variation.", strips("A distribution is not itself the decoder's input sample.", [["Distribution", ["Possible codes"]], ["Random draw", ["One sampled code"]], ["Decoder", ["A reconstruction"]]], true)),
    step("Give the code space a shared reference", "The prior is a distribution we choose as the source of codes when generating new examples. A common choice is a standard normal distribution. A KL-divergence term penalizes each inferred code distribution for differing from that prior. It competes with reconstruction, rather than replacing it.", strips("The two training pressures serve different purposes.", [["Reconstruction term", ["Preserve information about the input"]], ["KL term", ["Stay near the chosen prior"]]])),
    step("Generate without an input to reconstruct", "After training, we can draw a code from the prior and pass it to the decoder. The encoder is used to infer codes from existing inputs during training and reconstruction; it is not needed for this prior-sampling route.", strips("Two routes through the trained system.", [["Reconstruction", ["Input", "Encoder", "Sample", "Decoder"]], ["Generation", ["Prior sample", "Decoder", "New output"]]]))
  ], "Make the random draw differentiable with respect to its parameters", [
    "The next calculation separates the random noise draw from the mean and deviation. That is the reparameterization step used to train the encoder.",
    "The interactive example isolates that step and the KL term. A full VAE also needs an encoder, decoder, and reconstruction likelihood."
  ]),
  "generative-adversarial-networks": story([
    "Suppose we want a model to create handwritten digits. A classifier could tell us which digit an existing image resembles, but that does not tell a generator exactly which pixels to produce. We need feedback on the examples it creates.",
    "A generative adversarial network, or GAN, learns that feedback with a second model. The generator creates candidate examples. The discriminator learns to distinguish those candidates from examples in the training data. Each model gives the other a changing problem to solve."
  ], [
    step("Give the generator a source of variation", "The generator reads a random input, often a vector sampled from a simple distribution. Its parameters transform that input into an example. Different random inputs allow different outputs; the random vector is not a label saying which exact training example to copy.", strips("The generator is a mapping from a random code to an example.", [["Input", ["Random code"]], ["Generator", ["Learned transformation"]], ["Output", ["Candidate example"]]], true)),
    step("Teach the discriminator what it is comparing", "The discriminator receives both real training examples and generated examples. Its training target says which source each example came from. In the basic GAN setup, these source labels are constructed automatically; the images do not require human-written digit labels.", strips("Real and generated identify sources in this learning task.", [["Training collection", ["Real examples", "Target: real"]], ["Generator", ["Generated examples", "Target: generated"]], ["Discriminator", ["Estimate the source"]]])),
    step("Use the discriminator to guide the generator", "While updating the generator, hold the discriminator's parameters fixed. The generator is rewarded when the discriminator gives its outputs a higher real score. The gradient passes through the discriminator to tell the generator how its outputs affected that score.", strips("A gradient can pass through a model without updating that model's parameters.", [["Forward", ["Generator", "Discriminator", "Generator loss"]], ["Update", ["Change generator parameters only"]]])),
    step("Alternate because both tasks keep changing", "An improved generator gives the discriminator harder examples. An improved discriminator changes the generator's feedback. Alternate their updates instead of treating the discriminator as a fixed grading rule. This interaction also explains why training can oscillate or become unstable.", strips("One complete alternation.", [["First update", ["Fix generator", "Train discriminator"]], ["Second update", ["Fix discriminator", "Train generator"]], ["Repeat", ["Both now face a changed opponent"]]]))
  ], "Start with a distribution we can inspect directly", [
    "The numerical GAN generates single numbers rather than images. It learns to shift a Gaussian distribution toward the training distribution while a sigmoid discriminator learns to tell them apart.",
    "This lets us inspect real updates and their losses before discussing larger image generators or training failures such as mode collapse."
  ]),
  "diffusion-models": story([
    "Imagine adding a little random interference to a simple picture, then adding more until its structure is difficult to see. Creating corrupted examples is easy because we control the noise. Could those examples teach a model how to move in the other direction?",
    "Diffusion models use this idea to construct a learning problem. We start with real examples, create noisy versions, and train a model to estimate information needed to remove noise. Generation then begins with random noise and repeatedly uses a learned reverse process."
  ], [
    step("Begin with a recognizable signal", "Take a small picture with a bright region against a dark background. Its pixel values are the clean example we want the training process to preserve information about. We know those values when preparing training data.", tiles("Illustrative pixel grids, not outputs of a trained diffusion model.", [["Clean signal", [[0,0,1],[1,0,0]]]])),
    step("Mix in noise at a known strength", "A schedule specifies how strongly to corrupt the example. Early steps retain more of the clean signal. Later steps retain less. We keep track of the step because a lightly corrupted input and a heavily corrupted input need different treatment.", tiles("A schematic corruption, with the same pixel positions kept visible.", [["Clean", [[0,0,1],[1,0,0]]], ["Corrupted", [[0.3,0.1,0.7],[0.8,0.2,0.4]]]])),
    step("Turn our known noise into a training target", "Because we created the corruption, we know which random noise was used. One common training objective asks a network to predict that noise from the noisy input and the step. It is learning a statistical estimate across many examples, not receiving the exact hidden noise at generation time.", strips("The target comes from the corruption process.", [["Network inputs", ["Noisy example", "Noise step"]], ["Network output", ["Predicted noise"]], ["Training target", ["Actual noise used"]]])),
    step("Use a learned estimate repeatedly when generating", "At generation time there is no original clean picture to consult. Start with random noise and apply reverse updates using the trained predictor. Each update uses the current signal and its noise level. An estimate at one step is part of a sequence, not a guarantee of perfect recovery in one move.", strips("The reverse route needs a trained model.", [["Start", ["Random noise"]], ["Repeated update", ["Predict", "Take a reverse step"]], ["Finish", ["Generated sample"]]], true))
  ], "Separate known training noise from a model's estimate", [
    "The example supplies a controllable fraction of the exact noise as an oracle. It shows why an accurate estimate matters and why heavy corruption can amplify estimation errors.",
    "It does not train a denoiser or run a reverse sampler. The equations below identify where those components belong."
  ]),
  "supervised-fine-tuning": story([
    "A model trained to continue text may continue a question with another question, a quoted conversation, or an answer in an unsuitable format. We want to show it what responding to our kind of request should look like.",
    "Supervised fine-tuning starts with an already trained model and examples of desired behavior. Each example contains a prompt and a target response. We train on those pairs so the model becomes more likely to produce the demonstrated kind of response."
  ], [
    step("Decide what behavior the examples should teach", "Suppose a model should complete a short prefix and stop at an explicit end token. A training pair supplies both that prompt and the desired completion. For an assistant, the prompt might instead contain an instruction and the target might be a carefully written answer.", strips("The toy example is completion formatting, not a full assistant conversation.", [["Prompt", ["<start>", "the", "cat"]], ["Desired response", ["sat", "<end>"]]])),
    step("Let the response read the prompt", "The prompt provides context for predicting the response. A causal model must still hide future response tokens from earlier positions. During training, it reads the provided earlier response tokens while predicting the next one.", strips("Predicting the end token can use the provided sat token.", [["Available prefix", ["<start>", "the", "cat", "sat"], [0,1,2,3]], ["Next target", ["<end>"]]])),
    step("Choose which target predictions contribute to loss", "In response-only training, we score the predictions for response tokens and leave prompt-token predictions out of the loss. This is a loss mask. It does not erase the prompt from the context or stop the response from attending to it.", strips("Mask target positions, not access to the prompt.", [["Targets", ["the", "cat", "sat", "<end>"], [2,3]], ["Scored", ["Response targets only"]]])),
    step("Update an existing model toward the demonstrated behavior", "Backpropagation carries the response loss through the model, and an optimizer adjusts the trainable parameters. The starting model already contains learned representations. The quality and coverage of the new examples determine what behavior this additional training encourages.", strips("Fine-tuning changes parameters using labeled prompt-response pairs.", [["Start", ["Pretrained parameters"]], ["Training", ["Prompt-response examples", "Response loss"]], ["Result", ["Adapted parameters"]]], true))
  ], "The loss mask and the attention mask solve different problems", [
    "The worked example makes that distinction visible through per-token losses and derivatives. It isolates the objective rather than training a complete assistant.",
    "After understanding full-parameter fine-tuning, we can ask how LoRA reduces the number of parameters that need updates."
  ]),
  "reinforcement-learning": story([
    "Imagine a delivery robot at a junction. It can go left, straight, or right. We want it to choose a useful route, but we have not given it a list of correct turns to copy. Instead, we can let it try a route and report what happened.",
    "A quick delivery should count as a better outcome than a slow delivery. A blocked route should count as a poor outcome. We need a way for that feedback to change what the robot tries next. Start with just this one junction, so we can follow every part of the decision.",
  ], [
    step("Give the robot a decision to make", "The robot is the agent: the part that makes the choice. The simulated junction is its environment: the part that responds. Its observation tells it that it is at this junction. Its available actions are the three routes. For now, each route leads directly to an outcome and ends the attempt.", strips("One observation, three possible actions. The robot has no route preference yet.", [["Observation", ["At the junction"]], ["Actions", ["Left", "Straight", "Right"]]], true)),
    step("Describe what it is likely to try", "We need a rule for choosing an action. This rule is the policy. Our starting policy gives each route the same probability. Sampling from those probabilities lets the robot try different routes. The policy describes the robot's choices, not how likely a route is to be safe.", bars("Starting policy. Each action has one third of the probability.", [["Left", 1 / 3, "One third"], ["Straight", 1 / 3, "One third"], ["Right", 1 / 3, "One third"]])),
    step("Turn an outcome into feedback", "Suppose this attempt samples Straight and reaches the destination quickly. We assign that outcome a reward of 1. Our simulator assigns 0.2 to a slow delivery on Left and -1 to a blocked route on Right. These scores express our chosen priorities. On this attempt, the learning rule receives only the reward for Straight.", strips("A chosen action produces one observed reward. These outcomes and scores are assigned for this example.", [["Selected action", ["Straight"], [0]], ["Outcome", ["Quick delivery"]], ["Observed reward", ["1"]]], true)),
    step("Let the feedback change the next choice", "The update raises the probability of the action that received a positive reward. Some probability must come from the other actions because the total stays fixed. The bars show the calculated result of this one Straight update with learning rate 0.1 and a zero baseline. It is a small change, not a declaration that Straight is always best.", bars("One worked update from the equal starting policy. Percentages are rounded; the full calculation follows below.", [["Left", 0.3220434644, "32.20%"], ["Straight", 0.3559130712, "35.59%"], ["Right", 0.3220434644, "32.20%"]])),
    step("Collect another experience", "Reset the robot to the junction and sample again, now using the updated probabilities. A negative reward will reduce the chosen route's probability under our zero-baseline rule. Trying actions gathers experience; favoring rewarding actions uses that experience. The live example repeats this loop, with a sampling seed so you can reproduce a run.", strips("Each attempt ends after one action. The next attempt starts at the same junction with an updated policy.", [["Choose", ["Sample from the policy"]], ["Observe", ["Receive the selected reward"]], ["Learn", ["Update the policy"]], ["Repeat", ["Return to the junction"]]], true)),
  ], "From a route choice to learning from consequences", [
    "Reinforcement learning improves decisions using rewards from interaction. This single-decision example is called a bandit. Longer tasks add another problem: an early action can help or hurt an outcome that arrives much later.",
    "For a language model, the available actions can be tokens, and the outcome can be an assessment of the completed response. We will connect those pieces after following the small robot example through its update.",
  ]),
  "low-rank-adaptation": story([
    "A large model can contain far more weights than we can afford to update and store separately for every task. Yet adapting it may not require an independent change to every connection. Could we describe a useful change with fewer adjustable numbers?",
    "Low-rank adaptation, or LoRA, keeps an existing weight matrix frozen and learns an additional transformation through two smaller matrices. The update travels through a narrow intermediate space. Its width determines the rank limit."
  ], [
    step("Keep the original projection available", "A projection combines input coordinates into output coordinates using a weight matrix. The pretrained matrix already does useful work, so LoRA preserves it as a fixed route. Freezing it means the optimizer does not update its entries.", strips("The base route keeps its pretrained parameters.", [["Input", ["Input vector"]], ["Base projection", ["Frozen weights"]], ["Base result", ["Original output"]]], true)),
    step("Send an update through a smaller intermediate space", "A second route first projects the input into a small number of coordinates, then projects those coordinates back to the output width. Both matrices on this route can be trained. They jointly describe the change we add to the original output.", strips("An example with a narrow adapter.", [["Adapter input", ["Four coordinates"]], ["Intermediate", ["One coordinate"]], ["Adapter output", ["Four coordinates"]]], true)),
    step("Add the two routes", "The adapter contribution is scaled and added to the base output. The model therefore uses both its existing transformation and the learned adjustment. Because the adapter is linear here, its two matrices can also be multiplied and merged into a copy of the base matrix for inference.", strips("The frozen result and learned correction meet at an addition.", [["Base route", ["Original output"]], ["Adapter route", ["Scaled correction"]], ["Combined", ["Adapted output"]]], true)),
    step("Check whether the narrower route actually saves parameters", "A smaller rank restricts the possible updates and usually reduces their parameter count. But narrow is relative to the matrix dimensions. On a tiny matrix, increasing the rank can make the adapter as large as, or larger than, a full update.", bars("Illustrative counts for a four-by-four projection.", [["Full update", 16, "16 parameters"], ["Rank one adapter", 8, "8 parameters"], ["Rank two adapter", 16, "16 parameters"]]))
  ], "Calculate the update before treating rank as a tuning shortcut", [
    "The example displays the assembled weight change, its effect on an input, and both parameter counts.",
    "The factors are chosen values. Training an adapter requires a task objective, gradients, and a decision about which model projections receive adapters."
  ]),
  "retrieval-augmented-generation": story([
    "Suppose someone asks an assistant when a library opens on Saturday. The answer lives in the library's current schedule, but we cannot assume it is correctly stored in the model's parameters. We need to give the model relevant information when answering.",
    "Retrieval-augmented generation, or RAG, separates finding that information from writing an answer. A retriever selects useful passages from a collection. Those passages accompany the question as context for a language model."
  ], [
    step("Keep the source information outside the model", "Store the schedule and related material as passages with identifiable sources. The passages can be updated without retraining the language model. We still need a way to locate the passage relevant to a particular question.", strips("An invented library collection.", [["Source 1", ["Weekday opening hours"]], ["Source 2", ["Saturday opening hours"]], ["Source 3", ["How to renew books"]]])),
    step("Search for passages that might answer the question", "A retriever compares the question with the collection and ranks candidate passages. Our small example uses shared words. More capable retrieval systems can use learned text vectors, but a high similarity score still does not prove that a passage contains the answer.", strips("For a Saturday question, the Saturday passage is the desired evidence.", [["Question terms", ["library", "Saturday"]], ["Candidate passages", ["Weekday hours", "Saturday hours", "Renewals"], [1]]])),
    step("Put the question and evidence into the model's context", "The language model receives both the question and the selected passages. It can use those passages while composing the answer. Retrieving information changes the input context; it does not by itself update the model's weights.", strips("The retrieval result becomes part of the input.", [["Prompt", ["Instructions", "Question", "Source passages"]], ["Language model", ["Generate an answer"]]], true)),
    step("Check whether the answer is actually supported", "A fluent answer can still misread a passage, omit a qualification, or cite irrelevant evidence. Check that the sources support the answer. If retrieval found no useful passage, the system needs an explicit missing-evidence behavior rather than an invented fact.", strips("Two separate checks are needed.", [["Retrieval check", ["Did we find the needed evidence?"]], ["Answer check", ["Does the response agree with that evidence?"]]]))
  ], "Inspect retrieval before adding fluent generation", [
    "The full example lets you search the small collection and see the exact passages a model would receive. It deliberately stops before text generation.",
    "Try Saturday, renew, and a word absent from the collection. The results expose both the useful behavior and the limits of exact word overlap."
  ]),
  "evaluating-generative-models": story([
    "Two models can both produce fluent responses while making different mistakes. One may predict ordinary text well but invent a source. Another may answer correctly but fail to follow the requested format. A single impression of quality cannot tell us which behavior improved.",
    "Evaluation begins by deciding what success means for the task. Then we need examples the model was not trained or tuned on, a measurement that matches the question, and a way to inspect the failures hidden by an average."
  ], [
    step("Turn a broad claim into a question we can measure", "If we care about continuing text, we can measure probability assigned to held-out tokens. If we care about answering from documents, we need to check answer correctness and source support. The task determines which evidence is useful.", strips("Different questions require different measurements.", [["Continuation", ["Probability of observed next tokens"]], ["Document answers", ["Correctness", "Source support"]], ["Instructions", ["Requested behavior", "Format"]]])),
    step("Keep the evaluation examples separate", "A model can look successful by remembering examples it saw during training. Use a held-out test set, and avoid repeatedly choosing changes by its results. Near duplicates, shared documents, or benchmark material inside training data can weaken that separation.", strips("Give each split a different role.", [["Training", ["Learn parameters"]], ["Validation", ["Choose settings"]], ["Test", ["Estimate final performance"]]])),
    step("Inspect confidence as well as the selected token", "For next-token scoring, the probability of the observed token matters. Being confidently wrong should receive a larger penalty than being uncertain. Negative log likelihood provides that behavior; perplexity expresses the same average loss on another scale.", strips("Confidence is useful only in relation to the target.", [["More probability on target", ["Lower token loss"]], ["More probability on wrong token", ["Higher token loss"]]])),
    step("Read failures before interpreting a single average", "Compare results by task, input length, topic, and difficulty. For open-ended answers, use a clear rubric and inspect disagreements between evaluators. A gain in token probability does not automatically imply better factual answers, and a few attractive samples do not establish broad improvement.", strips("An evaluation report connects scores with examples and conditions.", [["Report", ["Metric", "Test data", "Failure cases", "Evaluation procedure"]]]))
  ], "Use perplexity for the question it actually answers", [
    "The numerical example contrasts confident correct and confident wrong token scores. The following sections explain what perplexity measures and what additional checks text and image generators need.",
    "These assigned scores teach the metric. They are not a benchmark comparison between real models."
  ]),
};
