import { plot, step, story, strips, tiles, type LessonIntuition, type Point } from "./types";
const neighbours: Point[] = [[1,1,0],[1.6,1.3,0],[2,0.7,0],[4,3.5,1],[4.7,4,1],[5,3,1],[2.5,2,2]];
const groups: Point[] = [[1,1],[1.5,1.3],[2,0.7],[4,3.5],[4.7,4],[5,3]];
const shape = [[0,1,0],[1,1,1],[0,1,0]];
const damaged = [[0,1,0],[1,0,1],[0,1,0]];
export const models: Record<string, LessonIntuition> = {
  "distance-metrics": story(["The nearest shop might be the closest by a straight line or the quickest to reach along streets. Both answers can be sensible because they use different meanings of distance.","A model also needs an explicit rule for nearness. That rule can change which observations count as neighbours."],[
    step("Start with the same two places","The endpoints are fixed. We want one number describing how far apart they are, but first we must decide what movement the ruler allows.",plot("Two illustrative positions on a grid.",[[0,0],[3,2]],"East-west position","North-south position")),
    step("Allow a direct route","Straight-line distance measures the direct gap between the endpoints. It is useful when that geometry matches what our inputs represent.",plot("The green route connects the endpoints directly.",[[0,0],[3,2]],"East-west position","North-south position",{paths:[[[0,0],[3,2]]]})),
    step("Require travel along the grid","If movement follows horizontal and vertical streets, the route must account for both legs. The points have not changed, but the permitted movement gives a different distance.",plot("The same endpoints with a grid-following route.",[[0,0],[3,2]],"East-west position","North-south position",{paths:[[[0,0],[3,0],[3,2]]]})),
    step("Use that ruler consistently","Once a rule is chosen, use it for every candidate neighbour. Different coordinate units also affect the comparisons, so choose appropriate scaling before interpreting the resulting neighbourhood.",strips("A neighbourhood depends on both representation and ruler.",[["Inputs",["Coordinates","Their scales"]],["Comparison",["Chosen distance rule"]],["Result",["Neighbour ordering"]]],true))
  ],"Nearness needs a definition",["We can now compare named distance functions and calculate the routes they represent. Their properties determine which algorithms can use them.","The full example shows how changing the rule can change a prediction even when the stored observations stay fixed."]),
  "k-nearest-neighbours": story(["A new observation arrives without a label. We have examples whose labels are known. A simple approach is to find the examples most like the new one and let their answers guide us.","Before a formula, follow which observations are consulted and how their answers become one prediction."],[
    step("Separate stored examples from the new case","Blue and amber points have supplied labels. The green point is the new observation. Its position is known, but its category is the question we are trying to answer.",plot("An illustrative set of labeled examples and one query.",neighbours,"First measurement","Second measurement")),
    step("Find a local neighbourhood","Compare the query with stored inputs using a chosen distance rule. Here the nearby blue group supplies the closest examples. Their labels are consulted only after nearness is measured.",plot("Dashed connections identify three selected neighbours.",neighbours,"First measurement","Second measurement",{guides:[[2.5,2,1,1],[2.5,2,1.6,1.3],[2.5,2,2,0.7]]})),
    step("Combine the neighbours' answers","For classification, neighbours can vote for their labels. For regression, their numerical answers can be averaged. The query receives an answer from the selected examples rather than from a single global fitted line.",strips("A schematic classification vote.",[["Neighbour labels",["Blue","Blue","Blue"]],["Combined answer",["Predict blue"]]],true)),
    step("Changing the neighbourhood changes the evidence","A small neighbourhood reacts strongly to individual examples. A larger one includes farther examples and can smooth local detail. Choose its size through evaluation rather than assuming one choice always wins.",strips("The neighbour count controls how local the answer is.",[["Fewer neighbours",["More local","More sensitive to individual examples"]],["More neighbours",["Broader evidence","May mix distinct regions"]]]))
  ],"Store, compare, then combine",["The algorithm needs stored labeled examples, a distance rule, and a neighbour count. These three components explain most of its behaviour.","The full playground lets you move the query and change which examples answer it. Scaling and evaluation determine whether its idea of similarity is useful."]),
  "decision-trees": story(["Imagine identifying an object by asking yes-or-no questions. Each answer rules out some possibilities and tells you which question to ask next. A decision tree makes predictions in that same inspectable sequence.","The questions must be useful for the data, and we need to know when to stop asking."],[
    step("One question divides the examples","Ask whether a measurement exceeds a chosen threshold. Every observation goes to one of two groups. A tree starts with this split rather than with a smooth prediction curve.",strips("A schematic threshold question.",[["Question",["Is the measurement above the threshold?"]],["Two routes",["No: left group","Yes: right group"]]],true)),
    step("A useful question makes answers less mixed","If both resulting groups still contain the same mixture of labels, the question did little. A useful split makes at least some of the groups more consistent about their answers.",strips("Illustrative label groups after two possible questions.",[["Weak split",["Blue and amber","Blue and amber"]],["Useful split",["Mostly blue","Mostly amber"]]])),
    step("Ask another question where it is needed","A mixed group can be divided again. Each route accumulates its own conditions. The model becomes a sequence of local decisions, rather than one question applied repeatedly to everyone.",strips("Only the unresolved route needs another question.",[["First split",["Clear group","Mixed group"]],["Within the mixed group",["Second question"]],["New groups",["Left answer","Right answer"]]],true)),
    step("Stop at an answer","A new observation follows the questions until it reaches a terminal group, called a leaf. The leaf supplies its prediction. Growing ever smaller leaves can memorize the training sample, so stopping is part of the model.",strips("Prediction follows one route through the fitted tree.",[["New input",["Answer first question"]],["Selected route",["Answer next question"]],["Leaf",["Read the stored prediction"]]],true))
  ],"The split score formalizes a useful question",["We can now introduce impurity as a measure of how mixed a group is, then measure how much a candidate split reduces it. The tree searches for questions using that score.","The worked examples show both the route a prediction takes and the limits of growing a very detailed tree."]),
  "bagging": story(["A small change in training data can make a decision tree ask a different first question. We might prefer a prediction that does not depend so strongly on which particular sample arrived.","Bagging asks several models trained on different resamples of the available data, then combines their answers."],[
    step("One model can depend strongly on its sample","Two slightly different collections can produce different trees. This is the instability we hope to reduce. We have not collected a new population, so we must make careful use of the observations already available.",strips("Different fitted rules can come from small sample changes.",[["Sample version one",["Tree A"]],["Sample version two",["Tree B"]]])),
    step("Draw training rows with replacement","Create a resample by drawing observations from the original data. A row can appear several times and another can be omitted. Repeat to give each model a different training collection.",strips("An illustrative bootstrap draw.",[["Original rows",["A","B","C","D"]],["First resample",["A","C","C","D"]],["Second resample",["B","B","D","A"]]])),
    step("Let each fitted member answer","Fit one model per resample. For a new input, ask all members for a prediction. Differences between their answers are expected because their training collections differed.",strips("Schematic votes from three members.",[["Member answers",["Blue","Amber","Blue"]],["Combination",["Majority vote: blue"]]],true)),
    step("A shared mistake survives the vote","Combining answers can reduce variability when members differ. If every model repeats the same mistake, averaging cannot remove it. More members do not automatically supply new information.",strips("Agreement can be useful or consistently wrong.",[["Different errors",["Some variation can average out"]],["Shared error",["The same error remains"]]]))
  ],"Resampling and aggregation perform different jobs",["Resampling produces varied members; voting or averaging combines their predictions. The next sections measure those operations separately.","Out-of-bag observations offer an evaluation route for members that did not train on them. That idea also needs a clear account of which rows were omitted."]),
  "random-forests": story(["Resampled trees can still repeatedly choose the same dominant feature. Their votes may agree because their rules are very similar, limiting what a committee gains.","A random forest adds another source of variation: it limits which features a tree may consider at each split."],[
    step("Notice the repeated first question","Even with different resamples, a strong feature can keep winning. The resulting trees may share many decisions and errors. We want useful differences between members, not just more copies.",strips("A schematic committee with similar opening questions.",[["Tree A",["Ask about height"]],["Tree B",["Ask about height"]],["Tree C",["Ask about height"]]])),
    step("Offer each split a subset of features","At a split, draw a subset of available features. The tree searches only among those candidates. Another split draws another subset, so the restriction is applied during growth.",strips("Illustrative feature menus at separate splits.",[["Split one may inspect",["Height","Age"]],["Split two may inspect",["Weight","Waist"]]])),
    step("Alternative questions create different routes","A tree denied the dominant feature must consider another way to divide its data. The resulting rule may be weaker alone but can make different errors from the other members.",strips("Different permitted features can lead to different questions.",[["Tree A",["Question about height"]],["Tree B",["Question about weight"]],["Tree C",["Question about age"]]])),
    step("Balance individual strength and useful disagreement","Restricting features too much can weaken members. Restricting too little can leave them very similar. The final vote depends on both member quality and how their errors overlap.",strips("Two properties need evaluation together.",[["Individual trees",["Make useful predictions"]],["Across trees",["Avoid identical errors"]]]))
  ],"The forest changes which questions are available",["The detailed lesson compares resampling with feature subsampling and follows the resulting trees. Both are sources of diversity, with different mechanisms.","Feature count and ensemble size are settings to validate. A random forest is not guaranteed to improve on every simpler model."]),
  "gradient-boosting": story(["Suppose a first prediction gets the broad pattern but leaves systematic mistakes. Instead of throwing it away, we could fit another small model to what remains wrong.","Boosting builds a prediction through successive corrections. Each new member depends on the current combined model."],[
    step("Start with a simple guess","For regression, a constant prediction gives us a baseline to inspect. The observations above it need an upward correction; those below need a downward correction.",plot("An illustrative curve compared with a constant guess.",[[0,0],[1,3],[2,4],[3,3],[4,0]],"Time","Height",{paths:[[[0,2],[4,2]]]})),
    step("Make the remaining error the next target","With squared-error regression, the next learner can fit the residuals: how far each observation lies above or below the current guess. It learns a correction to the existing prediction.",strips("The correction target belongs to the current model.",[["Current prediction",["Too high at the ends","Too low in the middle"]],["Needed correction",["Down at the ends","Up in the middle"]]])),
    step("Add only part of the correction","A learning rate controls how much of the new member's answer is added. Smaller corrections can make the sequence more gradual. We then calculate what is still wrong with the updated prediction.",strips("Each round changes the combined prediction before the next fit.",[["Current model",["Existing answer"]],["New member",["Scaled correction"]],["Updated model",["Recalculate remaining errors"]]],true)),
    step("Stop when more correction stops helping new cases","Training error may keep improving while validation error gets worse. The number of rounds is part of the model choice. A longer sequence can begin correcting sample noise rather than reusable structure.",strips("Both readings matter when deciding how long to continue.",[["Training",["Fit the observed examples"]],["Validation",["Check whether another round helps"]]]))
  ],"The next member answers what is still wrong",["The residual picture is exact for squared-error regression. Other losses use a corresponding local direction of improvement, which motivates gradient boosting's more general formulation.","The full experiment shows the members, their corrections, and the combined prediction separately."]),
  "feature-importance": story(["A fitted model uses several measurements. We want to know which ones it relies on, but counting how often a feature appears is different from asking whether prediction gets worse without its information.","We will distinguish those questions before assigning an importance score."],[
    step("Inspect what the model consulted","A tree can ask about one feature many times. That tells us how often it was used, but not whether those questions made useful improvements.",strips("Usage is one observable property of a fitted tree.",[["Questions encountered",["Height","Weight","Height","Height"]]])),
    step("Count the improvement credited to splits","A split-based score credits a feature for reductions in the tree's fitting criterion. It describes what happened while growing this model, under that particular criterion.",strips("Credit follows the feature used for each split.",[["Split",["Chosen feature","Reduction in the fitting criterion"]],["Aggregate",["Credit assigned to each feature"]]],true)),
    step("Break one column's alignment on purpose","Shuffle a feature across evaluation observations while leaving the fitted model fixed. Its values remain present, but they no longer belong to the right cases. Compare predictions before and after this disruption.",strips("Permutation preserves values while breaking their row associations.",[["Original column",["A's value","B's value","C's value"]],["Shuffled column",["C's value","A's value","B's value"]]])),
    step("Interpret the question you actually asked","If another feature carries similar information, the model may cope with one column being disrupted. Importance depends on the model, metric, data, and available alternatives. It is not automatically a causal effect.",strips("A useful score must retain its context.",[["Specify",["Which model?","Which metric?","Which evaluation data?"]],["Check",["Could another input substitute?"]]]))
  ],"Importance is a measurement with a defined question",["The next sections compare split credit and permutation-based evaluation. Neither should be presented as a context-free property of the feature.","Correlated inputs and the choice of evaluation data can change the interpretation substantially."]),
  "grid-search": story(["A fitting procedure can choose model parameters while still leaving settings for us, such as how many neighbours to consult. We need a fair way to compare those choices.","Grid search writes down candidates, fits each under the same evaluation arrangement, and compares their results."],[
    step("Identify the setting fitting will not choose","For a neighbour model, the stored data do not choose how many neighbours should vote. That is a configuration decision outside the fitted parameters.",strips("Candidate neighbour counts, before any comparison.",[["Candidates",["One neighbour","Three neighbours","Five neighbours"]]])),
    step("Give candidates the same evaluation conditions","Use the same training and validation divisions for each candidate. Otherwise a candidate may look better because it received an easier evaluation sample.",strips("The same folds are reused across candidates.",[["Candidate A",["Fold 1","Fold 2","Fold 3"]],["Candidate B",["Fold 1","Fold 2","Fold 3"]]])),
    step("Compare, then choose","For each candidate, aggregate its validation results using the chosen metric. Select according to that rule. The comparison has now used the validation answers to guide a decision.",strips("Selection happens after candidate evaluation.",[["Each configuration",["Fit on training folds","Score on validation folds"]],["Selection",["Choose using the stated metric"]]],true)),
    step("Save a separate test for the chosen procedure","The best validation score helped choose the winner, so it is not an untouched final test. Refit the selected configuration as planned, then assess the whole procedure on data reserved for that purpose.",strips("The winner's selection score and final test have different roles.",[["Validation",["Select configuration"]],["Final test",["Assess the selected procedure"]]]))
  ],"Search is an evaluation procedure around fitting",["We can now build a grid of settings and count the fits it requires. The arrangement of folds is as important as the candidate list.","The detailed experiments examine selection optimism and how nested evaluation can account for the search itself."]),
  "pipelines": story(["A model trained on standardized measurements needs the same transformation when new observations arrive. If training and prediction follow different preparation steps, even a correctly fitted model can receive the wrong kind of input.","A pipeline keeps the ordered preparation steps and final model together."],[
    step("Include preparation in the prediction process","Raw input is not necessarily what the model was trained to read. The transformation before it is part of the route from measurements to predictions.",strips("One input follows the whole chain.",[["Raw measurement",["Original units"]],["Preparation",["Transform using stored settings"]],["Model",["Predict from prepared input"]]],true)),
    step("Learn each preparation step on training data","A scaler needs training statistics. A feature selector may need training labels. Fit each step using only the observations permitted for that training run.",strips("Training data determines both preparation and model parameters.",[["Training rows",["Fit preparation"]],["Prepared training rows",["Fit model"]]],true)),
    step("Reuse fitted steps for new observations","Prediction applies the stored transformations in the same order. It does not relearn them from the arriving batch. This preserves the meaning of the inputs the model expects.",strips("The new input reuses fitted state.",[["New rows",["Apply stored preparation"]],["Prepared new rows",["Apply fitted model"]]],true)),
    step("Repeat the whole fit inside each fold","During cross-validation, each training fold needs its own fitted preparation. Preparing the complete dataset before splitting can let validation information influence the model's inputs.",strips("Each fold owns an independent fitted chain.",[["Fold A training rows",["Scaler A","Model A"]],["Fold B training rows",["Scaler B","Model B"]]]))
  ],"The order and fitted state belong to one chain",["The full examples trace inputs through each step and compare correct fold-local fitting with leaked preparation.","A pipeline makes the intended process easier to repeat. It still needs sensible split boundaries and properly implemented steps."]),
  "k-means": story(["Suppose observations arrive without category labels. We see several clumps and want a compact way to describe them. We could place representative centres and assign each observation to a nearby centre.","K-means alternates between deciding membership and improving those representatives."],[
    step("Begin without supplied categories","All points start unlabeled. We choose how many groups to seek, but the algorithm is not told that a point is a child, adult, or any other semantic category.",plot("A simple unlabeled cloud with two visible clumps.",groups,"First measurement","Second measurement")),
    step("Offer initial representatives","Place a chosen number of centres. Each point is assigned to whichever centre is nearest under the method's distance. The starting positions can affect where the process ends.",plot("Green points are two illustrative starting centres.",[...groups,[1,2,2],[5,2,2]],"First measurement","Second measurement")),
    step("Move each centre toward its assigned group","Replace a centre with the mean of its assigned observations. The representative now describes that group better under squared distance. Assignments may change after the movement.",plot("The representatives move into their assigned clumps.",[...groups.map((p,i)=>[p[0],p[1],i<3?0:1] as Point),[1.5,1,2],[4.57,3.5,2]],"First measurement","Second measurement")),
    step("Repeat assignment and movement","Continue until the stopping rule is met. The result is a grouping under this representation and objective. It does not establish that the groups are naturally occurring categories.",strips("The two alternating operations define the procedure.",[["Current centres",["Assign observations"]],["Current groups",["Update centres"]],["Repeat",["Check the stopping rule"]]],true))
  ],"A representative and an assignment are different objects",["We can now calculate distances, means, and the within-group objective. The same geometric picture explains why scaling and initialization matter.","The full example lets you inspect the iterations and compare different group counts rather than treating the first clustering as ground truth."]),
  "kernel-ridge": story(["A straight regression line cannot follow a relationship that rises and falls. Richer features can help, but there may be too many transformed coordinates to build explicitly.","Kernel ridge compares observations in a richer representation, then restrains the fitted combination so it cannot chase the sample freely."],[
    step("Start with a shape a line cannot follow","The observations form an arc. A straight candidate leaves systematic errors, even if we move or tilt it. We need a different family of prediction shapes.",plot("A schematic arc and a straight candidate.",[[0,0],[1,3],[2,4],[3,3],[4,0]],"Input","Target",{paths:[[[0,2],[4,2]]]})),
    step("Describe a point by its comparisons","Compare a new input with stored training inputs through a kernel. Each comparison describes a relationship in the kernel's feature representation. It does not predict the target by itself.",strips("The kernel supplies comparisons for the model to use.",[["New input",["Query"]],["Compare with",["Training A","Training B","Training C"]],["Obtain",["Comparison A","Comparison B","Comparison C"]]],true)),
    step("Learn how those comparisons contribute","Give each comparison a learned coefficient and combine their contributions. Their signs and sizes let predictions vary with the query. Ridge fitting penalizes complexity in feature space while fitting the targets.",strips("A learned combination produces the prediction.",[["Comparisons",["A","B","C"]],["Learned coefficients",["Contribution A","Contribution B","Contribution C"]],["Answer",["One predicted value"]]],true)),
    step("Choose flexibility and restraint together","The kernel determines available relationships. Regularization controls the fitting tradeoff. More elaborate or more local comparisons do not automatically improve predictions on new observations.",strips("Two settings perform different jobs.",[["Kernel",["Available relationships"]],["Regularization",["Restraint during fitting"]],["Validation",["Check the combined choice"]]]))
  ],"The kernel supplies relationships; ridge fits the combination",["The worked calculation builds a training comparison table and solves for coefficients without explicitly constructing the corresponding feature columns.","The lesson distinguishes the SDK's offset convention from other formulations and evaluates actual predictions."]),
  "kernel-pca": story(["PCA looks for straight directions through a cloud. In a circular pattern, such a ruler may miss the distinction between points near the centre and those farther away.","A different feature representation can make another kind of variation visible. Kernel PCA asks for principal directions in that representation."],[
    step("Notice a pattern without one preferred direction","A ring spreads in many directions. Distance from the middle may describe its structure better than either original coordinate. The picture motivates another representation.",plot("An illustrative centre and surrounding ring.",[[0,0],...Array.from({length:12},(_,i)=>[2*Math.cos(i*Math.PI/6),2*Math.sin(i*Math.PI/6)] as Point)],"First coordinate","Second coordinate")),
    step("Change how relationships are measured","A kernel defines comparisons corresponding to a feature representation. That representation can express relationships absent from ordinary straight-coordinate PCA. Choosing it still requires judgment.",strips("Change the representation before asking about its variation.",[["Original inputs",["Coordinates"]],["Kernel",["Feature-space comparisons"]]],true)),
    step("Centre in the space where PCA will operate","PCA describes variation around a centre. Kernel PCA centres its comparison table in feature space. Simply centring the original input columns does not generally perform the same operation.",strips("The location of the centring operation matters.",[["Training comparisons",["Uncentred kernel table"]],["Feature-space centring",["Centred table"]]],true)),
    step("Keep positions along the main directions","Retained components give each observation fewer coordinates. These summarize variation in the chosen feature space. A visually clear grouping still needs evaluation for the intended task.",strips("The result is a representation, not a supplied category.",[["Centred comparisons",["Find principal directions"]],["Each observation",["Retained component coordinates"]]],true))
  ],"The PCA question stays; the representation changes",["The next calculation finds components from the centred Gram matrix. Its eigenvectors determine training component coordinates.","New observations must reuse training centring information. Reconstructing an original input is a separate problem and may lack a simple exact answer."]),
  "hebbian-pca": story(["PCA can find a main direction after inspecting an entire dataset. What if observations arrive one at a time and we want to adjust a direction incrementally?","A local learning rule can update a unit's weights after each observation. First follow the direction those weights represent."],[
    step("Read the weights as a direction","For two coordinates, two weights define a direction. The unit responds to how an input aligns with it. The initial direction need not follow the data's main spread.",plot("An illustrative starting direction and centred cloud.",[[1,1],[2,1.8],[-1,-1],[-2,-1.8]],"First coordinate","Second coordinate",{paths:[[[-2,2],[2,-2]]]})),
    step("Let one observation influence it","The arriving observation and current response guide a small weight change. Repeated aligned activity can reinforce a direction. Reinforcement alone can also make weights grow without bound.",strips("One presentation provides a local learning opportunity.",[["Observe",["Input vector"]],["Respond",["Current unit output"]],["Update",["Adjust weights"]]],true)),
    step("Control growth while allowing direction to change","Oja's rule adds a stabilizing subtraction. The aim is to learn a useful direction rather than merely increasing its length. The learning rate controls each presentation's influence.",strips("The update balances two effects.",[["Reinforcement",["Respond to the observation"]],["Stabilization",["Limit unchecked growth"]]])),
    step("Compare with the batch direction","Under suitable conditions, repeated updates can approach a leading principal component. Preparation, learning rate, and enough presentations matter. One update is not an eigensolver result.",plot("The intended direction follows the cloud's spread.",[[1,1],[2,1.8],[-1,-1],[-2,-1.8]],"First coordinate","Second coordinate",{paths:[[[-2,-2],[2,2]]]}))
  ],"Learning direction differs from growing response",["The equations explain reinforcement and stabilization separately, with a purpose already established for each term.","The full experiment compares trajectories and agreement with batch PCA across learning settings."]),
  "self-organising-map": story(["Clustering can divide observations into groups without showing how the groups relate. We may want a small map where neighbouring cells represent similar observations.","A self-organising map couples its representatives through a fixed neighbourhood layout."],[
    step("Give each map cell a representative","Cells occupy fixed grid positions and hold changing representative vectors. A grid location and the measurements stored there are different objects.",strips("Map positions hold representatives in data space.",[["First grid row",["Cell A","Cell B"]],["Second grid row",["Cell C","Cell D"]]])),
    step("Find the closest representative","Compare an input with the vectors stored in the cells. The closest is the winning cell for this presentation. Its grid position tells us where the input currently lands.",strips("B is the illustrative winner.",[["First row",["A","B"],[1]],["Second row",["C","D"]],["Input",["Most similar to B's representative"]]])),
    step("Move the winner and nearby representatives","The winner moves toward the observation. Nearby grid cells also move, usually less strongly. This shared learning encourages map neighbours to represent related inputs.",strips("Grid proximity controls the shared update.",[["Winner",["Stronger movement"]],["Nearby cells",["Smaller movement"]],["Distant cells",["Little or no movement"]]])),
    step("Refine the map gradually","Broad early neighbourhoods organize the map. Smaller later ones refine local representatives. The resulting layout approximates relationships and can distort original distances.",strips("The schedule changes the scale of organization.",[["Earlier",["Broad neighbourhood"]],["Later",["Local refinement"]]]))
  ],"Neighbouring cells learn related representatives",["The next sections calculate the winner, neighbourhood influence, and update. Grid distance and data distance must remain distinct.","The full map shows what each cell holds and how well map proximity reflects the original observations."]),
  "hopfield-network": story(["A familiar symbol can remain recognizable after a few pixels are damaged. We would like a memory that can start from an incomplete pattern and settle toward a stored one.","A Hopfield network stores relationships between parts of patterns and uses them during recall."],[
    step("Start with something to remember","The pattern is a collection of cell states. Each state describes whether one cell is active. Remembering the pattern means preserving relationships between these states.",tiles("A small illustrative pattern.",[["Stored example",shape]])),
    step("Present a damaged cue","The cue differs from the example in one cell. We want the network to use relationships learned from complete patterns, rather than being told which cell needs repair.",tiles("The middle cell is missing from the cue.",[["Example",shape],["Damaged cue",damaged,[4]]])),
    step("Let cells respond to one another","A cell receives influence from other cell states through learned connections. Updating cells can move the whole pattern toward a stable configuration. The recall rule does not simply look up a saved image file.",strips("The current pattern drives each recall update.",[["Current states",["Read other cells"]],["Learned relationships",["Compute local influence"]],["Next state",["Update a cell"]]],true)),
    step("A stable result still needs inspection","A stable configuration may resemble a stored pattern, but can also be an unwanted state. Storing too many interfering patterns or using a poor cue can make recall fail.",tiles("A successful illustrative repair, not a guarantee for every cue.",[["Cue",damaged],["Desired recalled pattern",shape]]))
  ],"Recall uses interactions, not an exact answer key",["The energy function and update rule explain when a recall step moves toward stability. Their guarantees depend on the connection and update assumptions.","The full experiment tests multiple patterns and damaged cues, including failures and unwanted stable states."]),
  "restricted-boltzmann-machine": story(["A collection of binary patterns may share regularities without being identical. Instead of keeping only a list of examples, we might learn a distribution that can describe plausible patterns.","A restricted Boltzmann machine connects observed cells to hidden units that capture dependencies among them."],[
    step("Separate visible data from hidden description","Visible units hold an observed pattern. Hidden units provide another layer through which the model describes dependencies. They are not supplied semantic labels.",strips("Two groups of units with different roles.",[["Visible units",["Observed cells"]],["Hidden units",["Learned latent representation"]]])),
    step("Connect the layers with a restricted pattern","Connections run between visible and hidden units, not within either layer. This restriction makes conditional updates of one layer given the other manageable.",strips("Only cross-layer connections are present.",[["Visible layer",["Cell A","Cell B","Cell C"]],["Hidden layer",["Unit 1","Unit 2"]]],true)),
    step("Go from an observation to a reconstruction","Use a visible pattern to infer hidden activity, then use hidden activity to produce another visible pattern. The result is a sample or conditional estimate under the model, not an automatic exact copy.",tiles("An illustrative observation and possible imperfect reconstruction.",[["Observed",shape],["Reconstructed",damaged]])),
    step("Adjust the model's preferences","Training changes connections so observed patterns receive more support relative to alternatives produced by the model. Practical learning uses approximations to this comparison and does not guarantee exact likelihood optimization.",strips("Training compares data-driven and model-driven statistics.",[["Data route",["Observed patterns"]],["Model route",["Patterns generated by the current model"]],["Update",["Adjust relative preferences"]]]))
  ],"The goal is a learned distribution over patterns",["The detailed steps introduce energy, conditional probabilities, and the learning approximation after the two-layer picture is established.","A reconstructed grid is one diagnostic. It is not enough on its own to prove that the model learned a good distribution."]),
  "multiclass-classification": story(["A two-category classifier answers one yes-or-no question. If an observation might belong to several possible categories, we need a way to compare alternatives and produce one coherent prediction.","The first decision is how to organize the category questions."],[
    step("List the possible answers","A single-label multiclass problem gives each observation one category from a fixed set. That differs from a multilabel task where several answers can be true at once.",strips("An illustrative single-label shape task.",[["Possible answers",["Circle","Square","Triangle"]],["Required output",["Choose one category"]]])),
    step("Ask one question for each category","One approach fits a separate category-versus-rest model for each answer. Each compares its category with all the other observations, producing scores that need an explicit combination rule.",strips("One-versus-rest decomposes the task into binary questions.",[["Model A",["Circle or rest?"]],["Model B",["Square or rest?"]],["Model C",["Triangle or rest?"]]])),
    step("Or make the alternatives compete together","A joint model can produce one score per category and convert them into shares that sum to one. Increasing one category's share affects the others. Training evaluates the supplied correct category.",strips("A joint model reads all alternatives together.",[["Scores",["Circle score","Square score","Triangle score"]],["Normalize together",["Competing category shares"]]],true)),
    step("Inspect which categories get confused","A final category can hide the alternatives that were close. Evaluate both overall performance and which true categories are repeatedly mistaken for which predicted categories.",strips("A multiclass confusion table preserves specific mistakes.",[["Known category",["Circle"]],["Predicted category",["Square"]],["Record",["Circle mistaken for square"]]],true))
  ],"Several categories require an explicit comparison rule",["The full lesson contrasts independent binary decompositions with a joint multiclass formulation and explains how scores become predictions.","Class imbalance and different error costs can make one overall accuracy score insufficient."]),
  "markov-chains": story(["Knowing today's weather may change our expectation for tomorrow. We could keep the entire weather history, or start with a simpler assumption: the current state contains all the history our model will use.","A Markov chain records how likely each next state is from each current state."],[
    step("Choose the states","States are the categories the process can occupy. They might be sunny and rainy, or vowel and consonant in the lesson's text example. The state definition determines what information the model retains.",strips("A small illustrative state sequence.",[["Observed states",["Sunny","Sunny","Rainy","Sunny"]]])),
    step("Count what follows each state","Read adjacent pairs. Keep transitions out of sunny separate from transitions out of rainy. A single overall frequency would discard that conditioning information.",strips("The current state chooses which outgoing transitions we inspect.",[["After sunny",["Sunny or rainy?"]],["After rainy",["Sunny or rainy?"]]])),
    step("Turn outgoing counts into a next-state rule","For each current state, distribute probability across its possible successors. Those outgoing probabilities form one row of the transition table. The current state selects the row used next.",strips("Each row describes one conditional next-state distribution.",[["Current: sunny",["Probabilities of sunny and rainy"]],["Current: rainy",["Probabilities of sunny and rainy"]]])),
    step("Repeat while keeping the assumption visible","Choose a next state, make it the current state, and apply the rule again. Older history influences the future only through that current state under the model's assumption.",strips("A generated route repeatedly applies the same transition rule.",[["Current state",["Choose next state"]],["New current state",["Choose another state"]]],true))
  ],"A transition table describes conditional movement",["The detailed text example measures how the preceding letter category changes next-letter probabilities, then calculates multi-step behaviour.","The Markov assumption is a modeling choice. It can miss dependencies requiring a richer state or longer history."]),
};
