import { bars, plot, step, story, strips, tiles, type LessonIntuition } from "./types";
const cross = [[0,0,1,0,0],[0,0,1,0,0],[1,1,1,1,1],[0,0,1,0,0],[0,0,1,0,0]];
const square = [[0,0,0,0,0],[0,1,1,1,0],[0,1,0,1,0],[0,1,1,1,0],[0,0,0,0,0]];
export const networks: Record<string, LessonIntuition> = {
  "neurons-and-activations": story(["A model needs a small component that can combine several measurements and decide what signal to pass onward. An artificial neuron fills that role.","Before combining anything, separate its three fundamental components: weights control input contributions, a bias supplies an offset, and an activation function converts the resulting score into an output."],[
    step("Start with the measurements","Height and body mass are inputs in our example. They describe the person being read. The neuron's internal settings are separate from those measurements.",strips("Body mass is an input; model weights are coefficients.",[["Observation",["Height","Body mass"]],["Neuron",["Reads both measurements"]]],true)),
    step("Give each input its own influence","A weight acts like a separate gain control on an input. Its size controls contribution strength; its sign controls direction. Changing a model weight changes how the neuron responds without changing the person.",strips("Each input has its own coefficient.",[["Height route",["Height","Its model weight"]],["Mass route",["Body mass","Its model weight"]]])),
    step("Add a starting offset","The bias raises or lowers the combined score independently of the current inputs. It changes the starting level rather than the relative influence of height and body mass.",strips("The bias contributes separately from the input-dependent terms.",[["Combine",["Weighted input contributions"]],["Shift",["Add the bias"]],["Result",["One score"]]],true)),
    step("Choose how the score becomes an output","An activation function reads the score and applies an output rule. One common rule keeps positive scores and replaces negative ones with zero. Other activations respond differently. The activation does not choose the input weights.",strips("An illustrative rectifier response before its formula.",[["Negative score",["Output becomes zero"]],["Positive score",["Output keeps the score"]]])),
    step("Follow the whole component in order","The inputs meet their weights, the bias shifts the combined score, and the activation produces the output. During training, the weights and bias are adjusted to improve the larger model's task.",strips("Three component roles produce one neuron output.",[["Inputs",["Apply weights"]],["Combined score",["Add bias"]],["Output rule",["Apply activation"]]],true))
  ],"Now each symbol can name a component we understand",["The next calculation writes the weighted sum, bias, and activation separately. You can trace which component caused a change in the score or output.","The full neuron playground compares activation shapes after the basic roles are established."]),
  "dense-layers": story(["One neuron gives one response to an observation. We may want several different responses, each reading the same measurements in its own way.","A dense layer places several neurons beside one another and gives every neuron the same input vector."],[
    step("Keep the input observation together","The row contains one observation's measurements. Its entries retain their meanings and order as they travel through the layer.",strips("One row arrives as a unit.",[["Input row",["Height","Body mass"]]])),
    step("Send the same row to several neurons","Each neuron receives both measurements. The input is shared, but the neurons have separate weights and biases, so they can respond differently.",strips("Every neuron reads the entire same row.",[["Neuron A reads",["Height","Body mass"]],["Neuron B reads",["Height","Body mass"]],["Neuron C reads",["Height","Body mass"]]])),
    step("Keep the responses as another row","The three neuron outputs form the next representation of that observation. We have changed its description from two input numbers to three responses, while keeping it one observation.",strips("One observation can change width without becoming several observations.",[["Input",["Two measurements"]],["Output",["Response A","Response B","Response C"]]],true)),
    step("Pass that row to the next layer","A later layer reads the new responses as its inputs. Its expected width must match what the previous layer produces. Repeating this process is a forward pass through a network.",strips("The output width of one layer must fit the next layer's input.",[["First layer",["Three responses"]],["Next layer",["Reads three inputs"]]],true))
  ],"Matrix multiplication organizes the parallel neurons",["The numerical calculation performs the same weighted-sum operation for each neuron. A matrix stores those weights in a consistent arrangement.","The full example traces one row through several layers before introducing batch shapes and matrix notation."]),
  "backpropagation": story(["A network makes a prediction through several layers, and we measure how far that prediction missed. To improve it, we need to know how a small change to each internal parameter would affect the final loss.","A hidden weight acts indirectly through later operations. Backpropagation works backward through that chain of effects."],[
    step("Give the backward pass something to follow","First trace the forward calculation from input through hidden responses to prediction and loss. Keep the intermediate values because the later sensitivity calculation needs them.",strips("The forward route produces both an answer and saved intermediates.",[["Input",["Measurements"]],["Hidden layer",["Scores","Activations"]],["Output",["Prediction"]],["Compare with target",["Loss"]]],true)),
    step("Ask a small-change question","Choose one hidden weight. It changes a hidden response, which changes the output, which changes the loss. We want the sensitivity along this route, not a guess based on the weight's size.",strips("One parameter influences the loss through several links.",[["Hidden weight",["Hidden response"]],["Later operations",["Prediction"]],["Objective",["Loss"]]],true)),
    step("Combine local responses backward","Start with how loss responds to the prediction. Then ask how each earlier operation changes its output when its input changes. The chain rule connects these local sensitivities along each dependency path.",strips("Backward information follows the forward dependencies in reverse.",[["Loss sensitivity",["At the prediction"]],["Earlier sensitivity",["At the hidden response"]],["Parameter sensitivity",["At the selected weight"]]],true)),
    step("Add contributions when paths meet","An earlier value can influence loss through several later units. All those path contributions must be combined. Backpropagation reuses intermediate results so it need not perturb and rerun the whole network for every weight.",strips("Several downstream routes can contribute to one earlier gradient.",[["Downstream routes",["Contribution A","Contribution B"]],["Earlier parameter",["Combine both contributions"]]],true)),
    step("Let the optimizer use the gradients","Backpropagation computes sensitivities. An optimizer uses them to change parameters. Run a new forward pass afterward to see whether the finite update actually improved the loss.",strips("Gradient calculation and parameter updating are separate operations.",[["Backpropagation",["Compute gradients"]],["Optimizer",["Choose an update"]],["New forward pass",["Check the changed loss"]]],true))
  ],"Local sensitivities explain a distant parameter's effect",["The detailed example now calculates the output gradient, follows one hidden path, and combines contributions where paths meet.","Numerical gradient checks compare this backward calculation with small parameter perturbations. They test the sensitivities, not a causal explanation of the training data."]),
  "loss-functions": story(["A prediction can miss in several ways. A small numerical error, one extreme mistake, and a confident wrong category may deserve different treatment.","A loss function turns those outcomes into a fitting objective. We need to decide what should be costly before choosing its formula."],[
    step("Keep guesses beside known answers","A loss starts from a prediction and a target. The difference describes what went wrong on one example. Across a batch, those individual outcomes must be combined under a stated rule.",strips("An illustrative comparison before assigning a cost.",[["Prediction",["A little too high","Far too low"]],["Known answer",["The target for each example"]]])),
    step("Do not let opposite mistakes disappear","An overestimate and an equally sized underestimate are both mistakes. Adding signed errors could make them cancel, so a regression loss must price their size rather than accidentally erase them.",bars("Opposite signed misses, both requiring a cost.",[["Overestimate",4,"Positive miss"],["Underestimate",-4,"Negative miss"]])),
    step("Choose how strongly large mistakes should matter","Absolute error increases steadily with miss size. Squared error makes large misses grow in cost more quickly. A robust alternative can change its response for large errors. These are different priorities.",strips("Different loss shapes express different fitting preferences.",[["Absolute error",["Steady cost growth"]],["Squared error",["Large errors cost disproportionately more"]],["Robust alternatives",["Limit the influence of large misses"]]])),
    step("Distinguish current cost from useful direction","The loss value says how costly the current prediction is. Its derivative says how a small prediction change would alter that cost. Training needs the second quantity to decide how to adjust the model.",strips("Value and slope answer different questions.",[["Loss value",["How costly is this prediction?"]],["Derivative",["What would a small change do?"]]]))
  ],"Choose the error meaning before the formula",["The full lesson calculates regression and classification losses and their derivatives separately, with the input conventions made explicit.","The objective used for fitting and the metric used to judge practical performance need not be identical."]),
  "embedding-layers": story(["A token ID identifies a vocabulary entry. Two neighbouring IDs do not tell us that their words have similar meanings. We need another representation for the network to use.","An embedding layer gives each ID a row of numerical values that training can adjust."],[
    step("Treat the ID as an address","The word cat might receive ID 103. That number tells us which entry to select, much like a numbered drawer. Its size is not a measurement of the word.",strips("An illustrative ID assignment.",[["Text piece",["cat"]],["Vocabulary address",["103"]]],true)),
    step("Open the corresponding row","The layer stores a table with one row per vocabulary entry. The ID selects its row. Lookup does not calculate the word's meaning from the digits in its ID.",strips("A row is selected by identity.",[["Table entries",["Row 102","Row 103","Row 104"],[1]],["Lookup result",["The values stored in row 103"]]],true)),
    step("Pass the row's values into the network","The retrieved values form a vector. Later layers can compare and transform it. A sequence of token IDs becomes a sequence of vectors, with one position for each token occurrence.",strips("Repeated IDs select the same table row.",[["IDs",["103","104","103"]],["Vectors",["Cat row","Dog row","Cat row"]]])),
    step("Let training adjust selected rows","The task's loss sends gradients back to the retrieved entries. Repeated occurrences contribute to the same row's update. Useful relationships emerge from training and data, not from the original numbering scheme.",strips("The task determines how the table changes.",[["Selected vector",["Used by later layers"]],["Loss gradient",["Returns to the selected row"]]],true))
  ],"An embedding is a learned table lookup",["We can now inspect the table, output shape, and accumulation of gradients for repeated IDs.","A stored vector need not have a human meaning attached to each coordinate. Its usefulness depends on what the larger model learns to do with it."]),
  "attention": story(["The word bank can refer to a river bank or a place holding money. The surrounding words help us interpret it. One fixed starting vector for bank does not identify which context applies.","Attention lets a token gather information from other tokens, with different contributions for different contexts."],[
    step("Keep the same word and change its context","Read the two sentences. Bank is the same token, but river and money suggest different uses. We need its representation to incorporate relevant surrounding information.",strips("The words are familiar examples, not outputs of a trained model.",[["Sentence one",["we","sat","on","the","river","bank"],[4]],["Sentence two",["we","kept","money","in","the","bank"],[2]]])),
    step("Give the gathering token a query","Before collecting information, we need a way to decide which sources are relevant. A learned transformation of bank's current vector produces its query. Think of it as a numerical request for information, not a question written in English.",strips("The query belongs to the token receiving information.",[["Receiving token",["bank"]],["Transform its current vector",["Query vector"]]],true)),
    step("Give possible sources a key","Each available token also produces a key vector. Comparing bank's query with these keys gives a score for each possible source. Query and key transformations have separate jobs, so the model can learn how requests and sources should match.",strips("The same query is compared with several keys.",[["Compare",["bank query","river key"]],["Compare",["bank query","sat key"]],["Compare",["bank query","other available keys"]]])),
    step("Collect information using the comparison scores","Each source supplies a value vector containing the information it can contribute. Convert the comparison scores into shares, then combine the values using those shares. Several sources can contribute to the result; the layer does not have to choose just one.",strips("A schematic combination, without claiming trained language weights.",[["Comparison scores",["How much should each source contribute?"]],["Value vectors",["Information from the available tokens"]],["Weighted combination",["Information gathered for bank"]]],true)),
    step("Restrict access when the task requires it","A next-token predictor must not read future tokens during training. A causal mask blocks those contributions. This access rule is separate from choosing which allowed tokens receive more influence.",strips("A position may read itself and earlier positions under the causal convention used here.",[["Available",["Earlier tokens","Current token"],[0,1]],["Blocked",["Future tokens"]]]))
  ],"The arithmetic implements comparison followed by combination",["The next sections build queries, keys, and values from input vectors, calculate comparison scores, and show how their shares combine values.","The colour-vector experiment uses assigned projections so every calculation is inspectable. It is not a trained demonstration of language understanding."]),
  "positional-encoding": story(["The dog chased the cat and the cat chased the dog contain the same words but describe different events. A representation listing only which words occurred has lost information.","Position information gives a model access to where each token appears, alongside what token it is."],[
    step("Hold the words fixed and change their order","The vocabulary entries are unchanged, but the actor and recipient change. Order is information the task may need.",strips("The same words in different positions.",[["First sentence",["dog","chased","cat"]],["Second sentence",["cat","chased","dog"]]])),
    step("A lookup alone does not identify the position","An embedding table returns the same starting row for dog wherever it appears. Something else must supply position if later operations are to distinguish its placement.",strips("Token identity and occurrence position are separate.",[["Dog at the beginning",["Dog embedding"]],["Dog at the end",["Dog embedding"]]])),
    step("Supply a position-dependent description","Associate each sequence position with a vector and combine it with the token vector. The resulting input carries information from both sources. Sinusoidal encoding uses a fixed pattern rather than fitting a separate row here.",strips("The layer combines content and position information.",[["Position one",["Token vector","Position-one vector"]],["Position two",["Token vector","Position-two vector"]]])),
    step("Do not confuse order with permission to look","Position encoding describes where tokens occur. A causal mask determines which tokens may interact. Supplying positions does not, by itself, stop a token from reading future information.",strips("Two mechanisms answer different questions.",[["Position encoding",["Where is this token?"]],["Causal mask",["Which positions may it read?"]]]))
  ],"Content and location become available together",["The numerical example constructs the position vectors and shows their addition to token embeddings.","A model must still learn to use this information. Encoding position does not prescribe a grammatical interpretation."]),
  "recurrent-layers": story(["The latest temperature reading does not say whether the temperature has been rising or falling. Earlier readings can matter even when the current reading is identical.","A recurrent layer carries a state from one step to the next so earlier information can influence the current response."],[
    step("Compare histories with the same ending","Both sequences finish at the same temperature, but one is rising and the other falling. A model seeing only the last reading cannot distinguish them.",strips("Illustrative temperature histories.",[["Rising",["18","19","20"]],["Falling",["22","21","20"]]])),
    step("Carry a summary forward","At each step, combine the new input with the previous state. Produce an updated state and pass it onward. The same update rule is reused across sequence positions.",strips("State connects neighbouring time steps.",[["Previous state",["What has been retained"]],["Current input",["New reading"]],["Updated state",["Information for the next step"]]],true)),
    step("Decide what information to retain","A simple recurrent unit transforms the input and state together. Gated variants add controls for retaining or replacing information. These controls become useful through training rather than predefined meanings.",strips("Gates regulate how information changes.",[["Retain",["Keep useful earlier state"]],["Update",["Incorporate new information"]]])),
    step("Learn across the sequence","A state can affect predictions several steps later. Training follows those dependencies backward through time. Long sequences can make retaining and learning useful information difficult.",strips("An earlier update can influence a later loss.",[["Earlier input",["Changes state"]],["Later states",["Carry its influence"]],["Later prediction",["Produces a loss"]]],true))
  ],"The state is the link between observations",["We can now calculate one state update, then compare the recurrent variants and their gates.","The full experiment distinguishes outputs at each position from the final state, and explains how gradients travel across time."]),
  "residual-connections": story(["An earlier layer may already produce useful information. A later layer might need only a small correction, yet an ordinary chain asks it to produce the entire next representation.","A residual connection carries the input forward and lets another route learn an adjustment."],[
    step("Start with information worth keeping","Imagine a representation already describing an image reasonably well. The next stage may need to refine it without rebuilding every useful part from scratch.",strips("A representation can already be useful before the next block.",[["Input representation",["Existing information"]]])),
    step("Send it along two routes","One route carries the input directly. The other passes through a learned transformation. Both routes originate from the same input.",strips("Two routes have different jobs.",[["Shortcut route",["Carry the input"]],["Learned route",["Calculate an adjustment"]]])),
    step("Add the adjustment to the carried input","Combine corresponding entries from both routes. Their shapes must match for addition. If the learned adjustment is zero, the block can pass the input through unchanged.",strips("A zero adjustment gives an identity route.",[["Shortcut",["Original representation"]],["Adjustment",["Zero change"]],["Combined output",["Original representation"]]],true)),
    step("Keep both routes available during learning","Gradients can reach earlier layers through the shortcut as well as the learned route. This helps construct deep networks, but does not guarantee that every block improves its representation.",strips("The backward calculation includes both paths.",[["Arriving gradient",["Shortcut contribution","Learned-route contribution"]],["Earlier input",["Combine contributions"]]],true))
  ],"Learn a correction around an explicit identity route",["The worked block shows the addition and its backward pass. It also distinguishes an identity shortcut from a learned projection used when dimensions differ.","A residual block still requires suitable initialization, training, and evaluation."]),
  "dropout": story(["A network may lean heavily on particular internal responses that happen to work on its training examples. We can make that reliance less convenient by temporarily removing some responses during training.","Dropout changes which activations are available on a training pass. It does not permanently delete neurons."],[
    step("Begin with several available responses","A later layer reads the outputs of earlier units. With all responses present, it can learn combinations that depend strongly on specific units.",strips("An illustrative row of hidden responses.",[["Available activations",["A","B","C","D"]]])),
    step("Draw a temporary mask","Randomly set some activations to zero for this pass. The mask is a draw, not a judgment about which units are useful. A later pass may keep a different subset.",strips("One illustrative mask.",[["Before",["A","B","C","D"]],["This training pass",["A","Zero","C","Zero"],[0,2]]])),
    step("Learn under changing availability","Repeated masks make the next layer train with different available responses. In inverted dropout, retained activations are scaled during training to preserve their expected value under the mask.",strips("Different passes expose different subsets.",[["Pass one",["A","C"]],["Pass two",["B","C","D"]],["Pass three",["A","B"]]])),
    step("Use the evaluation convention deliberately","At prediction time, the usual inverted-dropout convention disables masking and uses all activations without another rescaling. Training and evaluation behaviour are intentionally different.",strips("The mode determines whether masking occurs.",[["Training",["Random mask and survivor scaling"]],["Evaluation",["All activations available"]]]))
  ],"Temporary missing responses change the training problem",["The detailed calculation explains mask sampling, scaling, and the backward pass.","The full experiment measures whether dropout helps its particular task. More dropout is not automatically better, and it does not prove memorization was prevented."]),
  "normalisation-layers": story(["The numbers passed between network layers can differ greatly in centre and scale. A later layer has to work with those changing inputs while its own parameters are also being learned.","Normalization layers transform groups of activations using a defined reference, then usually provide learned scale and offset parameters."],[
    step("Choose which values belong to one group","Before normalizing, identify the axes used to compute statistics. Batch normalization and layer normalization group values differently. The grouping determines what one value is compared with.",strips("The statistics depend on the chosen axes.",[["Batch-oriented grouping",["Compare a feature across examples"]],["Layer-oriented grouping",["Compare features within an example"]]])),
    step("Move the group to a reference centre and scale","Use the selected group's statistics to centre and rescale its values. A small stabilizing term prevents division by an unusably small denominator. This is an operation on activations, not new training labels.",strips("A normalization pass changes the numerical reference.",[["Input activations",["Original centre and spread"]],["Normalized activations",["Defined reference scale"]]],true)),
    step("Allow learned scale and offset afterward","The layer can learn how to scale and shift the normalized values. This lets the network choose a useful output range rather than being forced to keep one exact normalized representation.",strips("Learned parameters act after normalization.",[["Normalize",["Use group statistics"]],["Adjust",["Learned scale","Learned offset"]]],true)),
    step("Check how prediction gets its statistics","Batch normalization commonly uses stored running statistics at evaluation. Layer normalization uses the current example's grouped features. The model must follow the convention of the implemented layer.",strips("Training and evaluation conventions must be explicit.",[["Batch normalization",["Training statistics","Stored evaluation statistics"]],["Layer normalization",["Statistics from the current example"]]]))
  ],"The grouping rule is part of the layer",["The formulas now identify which values share statistics, where stabilizers enter, and which parameters are learned.","The full examples compare conventions and observed training behaviour rather than promising a universal improvement."]),
  "training-a-network": story(["A network begins with parameter values that usually do not solve the task. Training repeatedly compares its predictions with supplied answers and changes those parameters.","Follow one complete improvement cycle before discussing epochs, batches, or long loss curves."],[
    step("Make a prediction with the current parameters","The input moves through the layers and produces an output. At this point the model has only expressed what its current settings do.",strips("One forward pass.",[["Input",["Measurements"]],["Current network",["Apply layers in order"]],["Output",["Prediction"]]],true)),
    step("Measure the mismatch","Compare the prediction with the known target using the chosen loss. That loss specifies what the fitting process is trying to reduce.",strips("The target supplies the training answer.",[["Compare",["Prediction","Known target"]],["Objective",["Loss value"]]],true)),
    step("Calculate sensitivities, then update","Backpropagation calculates gradients. The optimizer uses them and its settings to choose parameter changes. A gradient is not itself a guarantee that a finite update will improve the loss.",strips("Two separate stages connect error to a change.",[["Backpropagation",["Parameter gradients"]],["Optimizer",["Parameter update"]]],true)),
    step("Repeat and check examples excluded from fitting","Training repeats over batches and passes through the data. Track validation performance as well as training loss so continued fitting does not silently become better memorization of one sample.",strips("Progress is judged on more than the examples used for updates.",[["Training batches",["Fit parameters"]],["Validation data",["Monitor the chosen procedure"]]]))
  ],"A long training run repeats a small loop",["We can now distinguish a batch, update, and epoch. Learning rate and optimizer settings govern how that loop changes the model.","The full experiment shows both the training trajectory and predictions, since a lower training loss alone does not establish better generalization."]),
  "radial-basis-networks": story(["A machine may work well near a particular temperature and poorly when much colder or hotter. We want a response that is strongest near a useful region rather than increasing forever in one direction.","A radial basis unit describes a region using a centre and a width."],[
    step("Pick the region a unit should respond to","The centre marks the input where a unit responds most strongly. Inputs farther away receive smaller responses under a Gaussian basis function.",plot("A chosen Gaussian response around an illustrative operating point.",[], "Input location","Unit response",{paths:[Array.from({length:25},(_,i)=>{const x=i/3-4;return[x,Math.exp(-x*x/2)];})]})),
    step("Separate location from width","Moving the centre changes where the response peaks. Changing width changes how broadly it responds around that location. These are distinct settings.",strips("Two settings with different geometric roles.",[["Centre",["Where the peak sits"]],["Width",["How broadly the unit responds"]]])),
    step("Use several local responses","Several units can cover different regions of the input. One observation produces a response from each unit, forming a new vector that describes its relation to those regions.",strips("One input can activate several local descriptions.",[["Input",["Current measurement"]],["Basis units",["Near centre A?","Near centre B?","Near centre C?"]]],true)),
    step("Combine local responses into a prediction","A later layer learns how much each response should contribute. The unit responses describe location; the output weights determine how that description serves the prediction task.",strips("Locality and prediction are separate stages.",[["Basis responses",["A","B","C"]],["Learned output combination",["One prediction"]]],true))
  ],"Centres and widths define the local representation",["The next calculation measures distance and converts it into a response, then shows how the relevant parameters can be trained.","Widths, centres, and output weights must be evaluated together. A local response is not automatically a calibrated probability."]),
  "convolution": story(["A small pattern can occur anywhere in a picture. We would like to recognize it using the same local rule rather than relearning a separate rule for every position.","Convolution applies one small set of weights repeatedly across the input."],[
    step("Keep neighbouring pixels together","A picture is a grid, and nearby cells form local patterns. The arrangement matters: shuffling the same pixel values would produce a different image.",tiles("A small illustrative cross.",[["Input picture",cross]])),
    step("Read one local window","Place a small window over part of the image. A filter combines the pixels inside that window using its weights and produces one response for that location.",tiles("The outlined cells identify the first local window.",[["One window",cross,[0,1,2,5,6,7,10,11,12]]])),
    step("Move the window and reuse the weights","Shift the window to another location and apply exactly the same weights. Reuse is the key idea: we ask the same local question wherever the pattern appears.",tiles("The same-sized window moves one column.",[["Next window",cross,[1,2,3,6,7,8,11,12,13]]])),
    step("Keep the responses in their spatial arrangement","Each location contributes a response to an output map. A bank of filters produces several maps, each responding according to its own weights.",strips("Responses retain the locations where they were measured.",[["Repeated local operation",["One response per window position"]],["Output",["A spatial response map"]]],true))
  ],"The filter is shared; the image patches change",["The worked example now multiplies one patch by the filter weights and records its response before completing the sweep.","Stride, padding, and output shape describe how the window travels. They are easier to interpret once one local operation is visible."]),
  "pooling": story(["A feature map may contain many nearby responses to the same local pattern. A later stage may need a smaller description rather than every precise location.","Pooling summarizes small regions. What it keeps depends on the chosen summary rule."],[
    step("Start with a map of local responses","The active cells represent responses from an earlier operation. Pooling reads this map; it does not have to discover the original image pattern again.",tiles("An illustrative four-by-four response map.",[["Responses",[[1,0,0,0],[0,1,0,1],[0,0,1,0],[0,0,0,1]]]])),
    step("Choose a region to summarize","Group neighbouring cells into a window. The operation will replace their detailed arrangement with a smaller amount of information.",tiles("Outlined cells form one pooling window.",[["First window",[[1,0,0,0],[0,1,0,1],[0,0,1,0],[0,0,0,1]],[0,1,4,5]]])),
    step("Decide what the summary should retain","Max pooling keeps the strongest response. Average pooling describes the region's average response. They answer different questions and discard different details.",strips("One region can be summarized in different ways.",[["Maximum",["Was there a strong response here?"]],["Average",["How strong was the response overall?"]]])),
    step("Accept the loss of exact location","The smaller output preserves regional evidence while discarding some within-window detail. Small movements may leave a summary unchanged, but pooling does not guarantee invariance to every shift.",tiles("A max-pooled result from the illustrated non-overlapping windows.",[["Original map",[[1,0,0,0],[0,1,0,1],[0,0,1,0],[0,0,0,1]]],["Smaller map",[[1,1],[0,1]]]]))
  ],"A smaller map is a chosen summary",["The next sections calculate maximum and average outputs, then trace where gradients return through each rule.","Window size, stride, overlap, and ties affect the actual behaviour and output arrangement."]),
  "shapes-and-flattening": story(["Two layers can only connect if the first hands over an arrangement the second knows how to read. Having the same number of values is not always enough.","Shapes describe how values are organized. Flattening changes that arrangement without learning new values."],[
    step("Distinguish the values from their arrangement","A small grid has rows and columns. The order of its entries tells us which cells are neighbours. A shape records that organization.",tiles("A two-by-three illustrative grid.",[["Grid",[[0,1,0],[1,1,0]]]])),
    step("Choose an explicit reading order","Flattening reads the grid in a specified order and places the entries into one row. The values survive, but their grid arrangement is no longer explicit in the row's shape.",strips("A row-major reading of the same grid.",[["First grid row",["0","1","0"]],["Second grid row",["1","1","0"]],["Flattened",["0","1","0","1","1","0"]]])),
    step("Check the next layer's expected input","A dense layer expecting six inputs can read this six-entry row. A layer expecting another width cannot use it without a defined transformation.",strips("Layer connections have an arrangement contract.",[["Flatten output",["Six entries"]],["Next layer expects",["Six inputs"]]],true)),
    step("Keep enough shape information to reverse the arrangement","Backward propagation needs to place arriving derivatives back in the original arrangement. Retaining the original shape makes this a reshape operation rather than a guess.",strips("The shape metadata preserves where entries belong.",[["Forward",["Grid to row"]],["Backward",["Row derivatives to original grid"]]]))
  ],"Shape checks protect meaning as well as size",["The full builder checks layer connections before a data pass. Convolution and pooling need spatial extents, while a dense layer needs a compatible feature width.","The later arithmetic derives those extents and shows which changes are reshapes and which actually calculate new values."]),
  "convolutional-networks": story(["A shape can move within an image while remaining the same kind of shape. A classifier needs local visual evidence that can be reused across positions and combined into a larger judgment.","A convolutional network builds that description through several layers of spatial processing."],[
    step("Begin with an image, not a category name","The network receives pixel values. Cross and square are supplied training labels, not information already written into the pixels as words.",tiles("Two illustrative labeled training examples.",[["Label: cross",cross],["Label: square",square]])),
    step("Read local patterns across the image","Early convolutional layers apply shared local filters. Their responses form maps showing where particular learned patterns occur. What a filter detects depends on training.",strips("The same local rule is applied at many positions.",[["Image",["Neighbouring pixels"]],["Shared filters",["Local responses across positions"]]],true)),
    step("Combine local evidence over larger regions","Later layers read earlier response maps. Their inputs can therefore carry information from a larger part of the original picture. Pooling or other reductions can make the representation smaller.",strips("Depth builds on earlier spatial descriptions.",[["Earlier maps",["Local evidence"]],["Later maps",["Combinations over larger regions"]]],true)),
    step("Train the final answer through the entire network","A final prediction is compared with the known category. Gradients pass through the output and earlier layers, adjusting filters for the task. A plausible-looking filter is not proof of good classification.",strips("The supplied label supervises the whole trained chain.",[["Representation",["Category prediction"]],["Known label",["Training loss"]],["Backward pass",["Adjust earlier filters"]]],true))
  ],"The layers learn a hierarchy of spatial descriptions",["The full model traces image shapes, response maps, and classification training. It shows how the assembled network uses the pieces introduced in the convolution and pooling lessons.","Evaluation uses pictures excluded from fitting, including changes in position and appearance that the training examples may not cover."]),
  "u-net": story(["An image classifier can say that a picture contains a shape. Sometimes we need a different answer: which pixels belong to that shape? The output must then be a picture-sized set of decisions.","U-Net learns this segmentation task from labeled images paired with target masks. The mask supplies the desired answer at each pixel."],[
    step("Show the answer the task requires","The input is an image. Its training target is a mask marking foreground and background at corresponding locations. A single category name would not provide these pixel-level answers.",tiles("A schematic labeled image-mask pair.",[["Input image",square],["Target mask",square.map(row=>row.map(v=>v?3:0))]])),
    step("Gather context by reducing the spatial representation","The contracting path builds broader descriptions while reducing spatial resolution. This helps the network identify what is present, but some precise location detail becomes harder to retain.",strips("The downward path trades resolution for broader context.",[["Fine image",["Local details"]],["Reduced representations",["Broader context"]]],true)),
    step("Restore resolution while bringing details back","The expanding path increases spatial resolution. Skip connections bring corresponding earlier feature maps alongside the expanding representation, helping it combine location detail with broader context.",strips("Two sources meet during reconstruction.",[["Expanding path",["Broader learned context"]],["Skip connection",["Earlier spatial detail"]],["Combined representation",["More precise spatial decisions"]]],true)),
    step("Compare the predicted mask with the labeled mask","Training measures pixel-level prediction errors against the supplied target. At evaluation, inspect masks on new images and compare with simple baselines, rather than assuming a larger network must win.",tiles("Desired output retains the target's spatial arrangement.",[["Target foreground",square.map(row=>row.map(v=>v?3:0))],["Per-pixel prediction task",square]]))
  ],"Context and spatial detail meet on the way back up",["The detailed architecture shows which feature maps are joined and how their shapes match. The output is evaluated against labeled masks.","The lesson also compares the trained model with a threshold baseline and tests image types and sizes absent from training."]),
};
