import { step, story, strips, type LessonIntuition } from "./types";
export const segmentation:Record<string,LessonIntuition>={
  "maximum-matching":story(["If writing contains no helpful spaces, a dictionary can suggest which character runs might be words. We still need a rule for choosing among entries that fit at the current position.","Maximum matching takes a locally longest matching entry, then continues from the next uncovered position."],[
    step("Start with text and a word list","The list supplies candidates. Without an entry for a word, this dictionary-based procedure cannot select it as a known word, however obvious it may look to a reader.",strips("An illustrative unspaced string and small dictionary.",[["Input",["nowhere"]],["Known entries",["now","here","nowhere"]]])),
    step("Compare entries at the current position","Several dictionary entries may match the beginning of the remaining text. A longest-match rule selects the longest permitted one at that location.",strips("Two possible entries begin at the first character.",[["Candidates here",["now","nowhere"],[1]]])),
    step("Commit, advance, and repeat","After selecting an entry, move beyond it and repeat. The procedure does not normally reconsider an earlier choice because a later continuation would have made a better whole reading.",strips("Local commitment defines the greedy scan.",[["Current position",["Choose longest matching entry"]],["Next position",["Continue after the chosen entry"]]],true)),
    step("Recognize dictionary gaps and local-choice errors","A long local match can lead to an awkward continuation in other examples. Missing words are a different failure: they were never candidates. Better path search can address the first problem without supplying the missing dictionary knowledge.",strips("Two limitations require different remedies.",[["Greedy choice",["A poor combination of available entries"]],["Coverage gap",["The needed entry is absent"]]]))
  ],"The dictionary proposes; the scan commits",["The full examples compare forward and backward matching and inspect ambiguous segmentations.","A whole-path method changes how candidates are selected. It cannot automatically recover words absent from the vocabulary."]),
  "the-word-lattice":story(["A locally longest word can leave an awkward remainder. Instead of committing immediately, we can keep several possible word boundaries and compare complete readings.","A word lattice represents those alternatives as routes through the character positions."],[
    step("Keep more than one reading available","A dictionary can cover the same text using different sequences. Retain those routes long enough to judge the complete segmentation.",strips("Illustrative complete readings of the same characters.",[["Route one",["now","here"]],["Route two",["nowhere"]]])),
    step("Connect positions with candidate words","Each dictionary entry covers a stretch from one character position to another. A complete path must connect the beginning to the end without leaving gaps.",strips("Each candidate spans a definite region of the input.",[["One route",["Beginning","now","here","End"]],["Another route",["Beginning","nowhere","End"]]])),
    step("Score the whole route","Use a stated model to score candidate words or transitions. A path's score combines the relevant local terms. The strongest complete route can differ from the one made by longest local choices.",strips("Selection compares complete covers.",[["Candidate routes",["Complete path A","Complete path B"]],["Decision",["Best path under the stated score"]]],true)),
    step("Reuse partial results","Dynamic programming keeps the best partial score at a position under the model's assumptions. Shared prefixes need not be solved again for every route. The dictionary still limits which edges exist.",strips("Shared subproblems reduce repeated work.",[["At a position",["Best compatible partial result"]],["Continue",["Extend through available entries"]]],true))
  ],"Delay commitment until the whole reading is scored",["The detailed lattice shows candidate spans, path scores, and the dynamic-programming recurrence.","Its best path is best under the specified model and available entries, not a guarantee of the intended linguistic reading."]),
  "segmenting-with-a-hidden-model":story(["A dictionary-based segmenter cannot choose a word missing from its list. Another approach labels each character's role inside a word, allowing boundaries to be inferred without requiring every complete word as an entry.","A hidden-state model connects those role labels across the sequence."],[
    step("Give characters positions within words","A character may begin a word, lie inside it, end it, or be a complete one-character word. The observed text contains the characters; their role sequence is hidden.",strips("An illustrative two-word segmentation.",[["Characters",["c","a","t","s","i","t","s"]],["Word roles",["Begin","Inside","End","Begin","Inside","Inside","End"]]])),
    step("Learn which role sequences and characters fit","Labeled training sequences provide evidence about role transitions and observed characters. The model uses those regularities to score a possible hidden role path.",strips("Two kinds of evidence guide a hidden-state model.",[["Transitions",["Which role can follow which?"]],["Observations",["Which characters occur in each role?"]]])),
    step("Choose a compatible sequence together","A role decision affects which roles can plausibly follow. Score the complete sequence rather than choosing each character's role independently. Dynamic programming finds a strongest path under the model.",strips("The sequence must form compatible word boundaries.",[["Candidate roles",["Begin","Inside","End"]],["Whole-path search",["Choose a compatible scored sequence"]]],true)),
    step("Read boundaries from the selected roles","The chosen roles determine where words end. This can propose words absent from a whole-word list, but depends on training coverage, transition assumptions, and treatment of unfamiliar characters.",strips("The selected hidden sequence produces the segmentation.",[["Role sequence",["End of word","Beginning of next"]],["Output",["Word boundaries"]]],true))
  ],"The hidden objects are the characters' word roles",["The detailed example estimates transition and observation probabilities, then follows the best-path calculation.","Avoiding a complete-word dictionary does not remove the need for labeled examples or a policy for unseen observations."]),
  "learning-boundaries-from-examples":story(["We can phrase segmentation as a question at every gap: does a word end here? Labeled examples can teach a classifier which local evidence makes a boundary likely.","This approach makes each boundary decision inspectable, while giving up some of the whole-sequence constraints used by a hidden-state model."],[
    step("Put the prediction at a gap","The target belongs between neighbouring characters. A label says whether that gap is a word boundary in the training example.",strips("The question concerns a particular gap.",[["Context",["last character of one word","GAP","first character of another"],[1]]])),
    step("Describe the gap using available context","Nearby characters, character categories, or other defined features describe the gap. Features must be computable from text available during prediction, not from the answer label.",strips("The classifier receives a description of the gap.",[["Possible evidence",["Left context","Right context","Character types"]]])),
    step("Learn from labeled boundary examples","Training supplies positive and negative examples of gaps. The classifier learns how their features relate to the presence of a boundary under the chosen objective.",strips("Both kinds of labeled gap are needed.",[["Positive example",["Boundary here"]],["Negative example",["No boundary here"]]])),
    step("Inspect local decisions and their limitations","Apply the classifier across the text and combine its gap decisions into pieces. Independently plausible boundaries need not form the best globally coherent analysis, so evaluate the resulting segmentation.",strips("Local predictions assemble into a sequence.",[["Each gap",["Boundary decision"]],["Whole text",["Resulting pieces"]]],true))
  ],"The prediction unit changes from a word to a gap",["The detailed example shows the selected features, learned boundary scores, and the decisions they produce.","It compares local inspectability with the constraints and context a whole-path model can use."]),
};

