import { step, story, strips, type LessonIntuition } from "./types";
export const textPieces:Record<string,LessonIntuition>={
  "byte-pair-encoding":story(["Whole-word vocabularies need a plan for unfamiliar spellings. Starting with smaller units gives broader coverage, but long sequences can be costly.","Byte pair encoding learns reusable larger pieces by repeatedly merging adjacent units that occur together often."],[
    step("Begin with pieces that can spell the training words","Start with a small alphabet, such as characters in this illustration. The words are still reconstructible, but each may require many pieces.",strips("A simplified character-starting example.",[["low",["l","o","w"]],["lower",["l","o","w","e","r"]]])),
    step("Count adjacent pairs across the training text","A pair appearing repeatedly is a candidate for a reusable piece. Counts come from the corpus, with a defined tie rule when several pairs are equally frequent.",strips("Adjacent pairs, before selecting a merge.",[["Candidates in low",["l + o","o + w"]],["Candidates in lower",["l + o","o + w","w + e","e + r"]]])),
    step("Replace a chosen pair consistently","Suppose the procedure chooses l followed by o. Replace that pair with lo wherever the merge applies. The new piece can participate in later merges.",strips("One illustrative merge, without claiming a unique tie winner.",[["low after the merge",["lo","w"]],["lower after the merge",["lo","w","e","r"]]])),
    step("Keep the learned merge order for new text","The stored merge sequence determines how compatible new text is processed. Reusable pieces can occur inside words absent from training, provided the starting alphabet and fallback policy support them.",strips("Training learns operations that encoding later reuses.",[["Training",["Learn ordered merges"]],["Encoding",["Apply those stored merges"]]],true))
  ],"Frequent local combinations build the vocabulary",["The detailed example counts actual pairs, applies each merge, and inspects the resulting vocabulary and sequence length.","The name BPE does not guarantee a particular starting alphabet or unknown-character policy. Those choices are explicit in this implementation."]),
  "wordpiece":story(["A frequent adjacent pair may be frequent mainly because each of its pieces appears everywhere. We might prefer a pair that occurs together more strongly relative to its parts.","This teaching WordPiece implementation uses an association-style score when growing pieces, then a defined vocabulary matching rule during encoding."],[
    step("Separate pair frequency from association","Two common pieces can meet often without having a particularly distinctive relationship. Comparing a pair with the frequencies of its parts asks a different question from counting the pair alone.",strips("Two kinds of evidence about a candidate pair.",[["Raw count",["How often do they meet?"]],["Relative association",["How distinctive is that meeting?"]]])),
    step("Choose a merge under the stated score","Score candidate adjacent pairs using the implementation's rule, then merge a selected pair. A changed score can produce a different vocabulary even from the same corpus.",strips("The selection criterion changes which piece is added.",[["Same corpus",["Same candidate pairs"]],["Different scoring rule",["Potentially different selected merge"]]],true)),
    step("Mark pieces that continue a word","Continuation markers distinguish a piece inside a word from one allowed at its beginning. The marker is tokenizer notation, not literal text that was necessarily present in the input.",strips("A familiar illustrative continuation convention.",[["Word",["playing"]],["Possible pieces",["play","##ing"]]])),
    step("Encode with the learned vocabulary's matching rules","Vocabulary learning and word segmentation are separate procedures. The encoder must specify longest-match behaviour and what happens when a word cannot be fully covered.",strips("The fitted vocabulary still needs an encoding policy.",[["Learned pieces",["Vocabulary"]],["Encoder",["Matching rule","Unknown-word policy"]]],true))
  ],"A vocabulary objective and an encoder are different choices",["The detailed lesson calculates the score used here and compares the learned pieces with BPE.","WordPiece implementations can differ. This lesson describes the SDK's explicit scoring, continuation, and fallback conventions."]),
  "sentencepiece":story(["Many tokenizers first split text into whitespace-delimited words. That makes a boundary decision before subword learning begins, and it can be awkward for writing without those spaces.","SentencePiece-style processing learns from a text representation that can include whitespace as an explicit symbol."],[
    step("Keep the input as text","Start with the sentence rather than assuming a prior word split. The representation should account for separators as well as letters.",strips("The original small example.",[["Text",["the cat"]]])),
    step("Make the space visible to the tokenizer","Represent a space with a marker so it can travel through the piece sequence. This marker is a reversible convention only to the extent that earlier normalization preserved the original distinctions.",strips("A simplified marked representation without a dummy prefix.",[["Marked text",["the▁cat"]]])),
    step("Learn pieces in the marked representation","A vocabulary method can learn pieces involving letters and the space marker. The marker allows information about spacing to remain attached to the learned representation.",strips("One possible piece sequence for the illustrative text.",[["Pieces",["the","▁cat"]]])),
    step("Decode under the same conventions","Reassemble the pieces and interpret the marker as spacing. Compare with the normalized input and, separately, with the exact original. Normalization can prevent a byte-for-byte round trip.",strips("Decoding reverses the marker convention, not arbitrary earlier information loss.",[["Pieces",["the","▁cat"]],["Reconstructed text",["the cat"]]],true))
  ],"Whitespace becomes part of the representation",["The full example shows the SDK's marking, vocabulary learning, and normalization choices explicitly.","A framework for learning pieces is different from a single universal segmentation algorithm; the selected learning method still matters."]),
  "the-unigram-language-model":story(["The same word can be spelled by several sequences of vocabulary pieces. Instead of committing to one sequence of merges, we can give pieces probabilities and compare complete segmentations.","The unigram tokenizer chooses among possible piece sequences under its fitted probability model."],[
    step("Keep multiple spellings available","Suppose the vocabulary includes low, er, lo, and wer. Lower can then be covered by more than one sequence. Both routes reproduce the same characters.",strips("Illustrative vocabulary alternatives.",[["Route A",["low","er"]],["Route B",["lo","wer"]]])),
    step("Attach a probability to each piece","The model estimates how frequently useful pieces should be chosen. A complete segmentation receives a score from the probabilities of its pieces under the model's independence assumption.",strips("The model scores whole candidate sequences.",[["Piece probabilities",["Probability of low","Probability of er","Other piece probabilities"]],["Sequence score",["Combine the pieces' probabilities"]]],true)),
    step("Find the strongest complete route","A locally attractive piece can leave a poor ending. Compare complete paths through the text. Dynamic programming reuses the best partial results instead of enumerating every full segmentation.",strips("The whole word must be covered.",[["Candidate A",["low","er"]],["Candidate B",["lo","wer"]],["Decision",["Best complete path under the fitted scores"]]])),
    step("Prune pieces by what losing them would cost","Vocabulary learning can remove pieces whose absence harms the model least, while maintaining required coverage. Probabilities and segmentations interact, so fitting alternates estimation and vocabulary decisions.",strips("Removing a piece can change several possible paths.",[["Current vocabulary",["Available segmentations"]],["Consider removal",["How much does the model lose?"]]],true))
  ],"The vocabulary supports competing complete explanations",["The detailed calculation writes sequence probabilities as additive log scores and follows the best path.","This is a tokenizer model over pieces. It is not a claim that natural language words occur independently in a complete language model."]),
  "greedy-coverage":story(["If a vocabulary has room for only a few additions, which pieces should we keep? One possible answer is to choose pieces that cover as much useful material as possible.","Coverage must be defined first. Once a piece has covered something, another piece should receive credit only for what it adds."],[
    step("Define the units to cover","The units might be occurrences or positions, depending on the objective. Name them explicitly before comparing candidates. A guarantee about one definition need not apply to another.",strips("Letters stand for illustrative coverage units.",[["Uncovered units",["A","B","C","D","E"]]])),
    step("Mark what each candidate covers","Each candidate covers a subset of units. Some candidates overlap, so their standalone coverage cannot simply be added to estimate the value of keeping both.",strips("Candidate coverage overlaps on B and C.",[["Candidate one",["A","B","C"]],["Candidate two",["B","C","D"]],["Candidate three",["E"]]])),
    step("Choose a candidate, then update the remaining gains","After selecting candidate one, A, B, and C are already covered. Candidate two now adds D rather than receiving fresh credit for its entire set.",strips("Only newly covered units contribute to the next gain.",[["Already covered",["A","B","C"]],["Candidate two adds",["D"],[0]]])),
    step("Repeat within the budget","Keep choosing the largest remaining gain under the specified objective. The resulting set serves that coverage goal. Its quality as a tokenizer still needs a separate evaluation.",strips("Greedy selection repeatedly updates what remains.",[["Select",["Best current additional coverage"]],["Update",["Remaining gains"]],["Stop",["Budget reached"]]],true))
  ],"Additional coverage differs from total coverage",["The detailed examples calculate the marginal gains and compare the objective with alternatives.","A bound on coverage does not automatically establish shorter token sequences, linguistic quality, or downstream model accuracy."]),
  "morfessor":story(["Related words often reuse parts: walk, walked, and walking share visible structure. A learner could store every whole word, or try to describe them using reusable pieces.","Morfessor balances the cost of a piece inventory against the cost of expressing a corpus with those pieces."],[
    step("Notice repeated structure","The repeated spelling suggests a reusable piece, but we should not assume every frequent substring is a grammatical unit. The learning objective decides which reuse is worthwhile.",strips("A small family of related words.",[["Words",["walk","walked","walking"]]])),
    step("Compare whole words with reusable parts","Whole-word entries avoid spelling each word from several pieces, but require a larger inventory. Shared parts can reduce inventory repetition while making individual descriptions longer.",strips("Two possible ways to describe the same words.",[["Whole entries",["walk","walked","walking"]],["Reusable inventory",["walk","ed","ing"]]])),
    step("Price both the inventory and the corpus","A description-length objective accounts for storing the pieces and using them to encode the observed words. Neither the smallest inventory nor the fewest pieces per word wins automatically.",strips("The objective balances two costs.",[["Inventory cost",["Store the reusable pieces"]],["Corpus cost",["Describe all observed words"]]])),
    step("Inspect what the statistical pieces mean","The fitted pieces may resemble morphemes, but compression does not guarantee linguistic correctness. Check actual segmentations, especially irregular forms and unfamiliar words.",strips("A useful statistical piece is not automatically a grammatical analysis.",[["Inspect",["Reused spellings","Irregular words","Unseen forms"]]]))
  ],"Reuse is encouraged through a stated cost",["The full lesson compares candidate splits under the implementation's objective and search procedure.","The simple verb family offers an intuitive reference, while more difficult examples show why morphology cannot be inferred from compression alone."]),
  "finite-state-morphology":story(["Splitting a word into frequent pieces does not tell us what its parts do. A grammatical analyzer may need to identify a stem, an ending, and a spelling change.","A finite-state morphology system connects written forms with analyses through explicit lexical and grammatical rules."],[
    step("Distinguish a written form from an analysis","Cats is a surface spelling. Cat plus a plural label is an analysis of its structure. The analyzer's job is to connect the two under its rules.",strips("An illustrative regular plural.",[["Surface form",["cats"]],["Analysis",["cat","plural"]]])),
    step("List permitted stems and continuations","The grammar needs entries it recognizes and rules for what can follow them. It does not infer every missing stem merely by encountering its spelling.",strips("The lexicon and continuation rules supply explicit knowledge.",[["Known stem",["cat"]],["Allowed continuation",["Plural ending"]]],true)),
    step("Account for written changes","The combination of a stem and ending may alter the spelling. Rules connect the underlying combination with the surface form, rather than treating every spelling as unrelated.",strips("A familiar spelling alternation to motivate a rule.",[["Underlying combination",["city","plural"]],["Surface form",["cities"]]],true)),
    step("Keep ambiguity and missing coverage visible","More than one analysis may fit a form. No analysis may mean the grammar lacks a stem or rule, not that the word is invalid. The output should preserve those limits.",strips("Two different outcomes need different interpretations.",[["Several analyses",["Ambiguity under the grammar"]],["No analysis",["Possibly missing coverage"]]]))
  ],"The grammar makes the analysis inspectable",["The detailed example follows states and transitions through the small grammar implemented here.","Explicit rules provide clear reasoning about accepted forms, while also making missing coverage a central limitation."]),
  "patching-without-a-vocabulary":story(["Bytes can represent unfamiliar text, but one position per byte may leave a long sequence for a later model. We might group nearby bytes so later processing sees fewer positions.","Patching chooses regions of the sequence. Choosing their boundaries is separate from learning a representation for each region."],[
    step("Start with the full byte sequence","The input is already representable. The problem is how many positions later processing must handle, not a missing vocabulary entry.",strips("Illustrative positions in an encoded sequence.",[["Byte positions",["1","2","3","4","5","6","7","8"]]])),
    step("Try fixed-size groups","A simple baseline cuts after a fixed number of bytes. Its boundaries are easy to predict, but they need not align with characters, words, or meaningful changes.",strips("Two fixed-size patches in the illustrative sequence.",[["Patch A",["1","2","3","4"]],["Patch B",["5","6","7","8"]]])),
    step("Let a boundary rule adapt to the text","Another rule can use predictability or uncertainty to decide where to end a patch. The rule needs its own information source and cost; adaptive grouping is not free.",strips("An illustrative variable-size partition.",[["Patch A",["1","2"]],["Patch B",["3","4","5","6","7"]],["Patch C",["8"]]])),
    step("Decide what each patch passes onward","A later stage needs a representation of the bytes inside each patch. Fewer boundaries alone do not specify how information is summarized or what the larger model can recover.",strips("Boundary selection and representation are separate.",[["Choose patches",["Which bytes belong together?"]],["Represent patches",["What information travels onward?"]]]))
  ],"Shorter sequences require a defined grouping and representation",["The full example compares boundary rules and their resulting patch lengths.","It does not claim that boundary selection alone implements a complete language model or guarantees an overall computational saving."]),
  "moving-a-vocabulary":story(["An embedding table is tied to a vocabulary: each token ID selects a particular row. Replacing the vocabulary can make the same row number refer to a different piece.","A transfer procedure must preserve piece identity, rather than treating matching table dimensions as matching meaning."],[
    step("Keep the old piece-to-row relationship","The existing model learned a vector for a specific vocabulary entry. Its row index is only the address used by that vocabulary.",strips("An illustrative original mapping.",[["Old vocabulary",["cat → row 2","dog → row 3"]]])),
    step("Inspect the new vocabulary's identities","The new vocabulary can reorder shared pieces and introduce new ones. Row two may no longer mean cat, even if the table has the same width.",strips("The same numeric address can now name another piece.",[["New vocabulary",["dog → row 2","cat → row 5","kitten → row 6"]]])),
    step("Copy by identity and define a policy for new pieces","Move a shared piece's vector to its new address. For a new piece, choose an explicit initialization or composition rule rather than copying an unrelated row.",strips("Different kinds of entries need different transfer actions.",[["Shared piece",["Copy its existing vector"]],["New piece",["Use a stated initialization rule"]]])),
    step("Evaluate after the transfer","Transferred vectors are an initialization for the revised model. New segmentation patterns can change sequence lengths and context, so matching shared rows does not prove the entire model behaves identically.",strips("A table transfer changes part of a larger pipeline.",[["Check",["Piece identity","Segmentation","Model performance after adaptation"]]]))
  ],"Transfer the association, not the old row number",["The full example reports which rows were copied, constructed, or initialized without a useful match.","Fine-tuning and evaluation determine whether the new vocabulary and transferred representation work together."]),
};
