import { step, story, strips, type LessonIntuition } from "./types";
export const textBasics:Record<string,LessonIntuition>={
  "what-a-token-is":story(["As humans, we can read the letters and words in a sentence. A numerical model needs a representation it can process. We first need to decide which pieces of the text it will receive and how to identify each piece.","A token is one of those pieces. Its ID names the piece; the ID does not supply its meaning."],[
    step("Begin with readable text","Keep a short sentence in view. We understand its words, but the next processing stage needs explicitly identified units. Nothing about a raw character sequence says which units a particular tokenizer should choose.",strips("A small sentence to follow through the steps.",[["Text",["the cat sat"]]])),
    step("Choose the pieces","A simple scheme can use whole words. Other schemes use word parts, characters, or bytes. The token is the unit chosen by that scheme, not necessarily a complete word.",strips("One possible word-based segmentation.",[["Pieces",["the","cat","sat"]]])),
    step("Give each known piece an ID","A vocabulary connects pieces with integer IDs. Cat might be assigned 103. The assignment is an address, so neighbouring numbers do not imply neighbouring meanings.",strips("Illustrative IDs, not an actual learned vocabulary.",[["Pieces",["the","cat","sat"]],["IDs",["12","103","57"]]])),
    step("Read the IDs back through the same vocabulary","Decoding looks up the pieces associated with IDs and reconstructs text under the tokenizer's spacing rules. An unfamiliar piece needs an explicit policy. The IDs alone cannot repair information the tokenizer discarded.",strips("The same table connects identity in both directions.",[["Encoded",["12","103","57"]],["Looked-up pieces",["the","cat","sat"]]],true))
  ],"Piece selection and numbering are separate decisions",["We can now inspect a vocabulary and follow encoding and decoding on a sentence with punctuation and word parts.","Later lessons explain why smaller pieces help with unfamiliar words and what different boundary rules preserve."]),
  "splitting-on-spaces":story(["Written spaces offer an obvious first clue about where text pieces begin and end. A simple rule can cut at whitespace without knowing a dictionary or grammar.","That simplicity is useful, but it leaves punctuation attached and assumes the writing uses gaps in a helpful way."],[
    step("Find the visible gaps","Start with a short sentence and identify whitespace. The rule looks for those gaps; it does not decide whether each resulting piece is a linguistic word.",strips("The raw sentence before splitting.",[["Text",["The cat, slept."]]])),
    step("Cut at the whitespace","Each non-whitespace run becomes a piece. Commas and full stops stay attached because they are not spaces. The output follows the rule even when that is not the segmentation we wanted.",strips("Punctuation remains inside the resulting pieces.",[["Pieces",["The","cat,","slept."]]])),
    step("Keep positions if the original layout matters","Piece text alone may not record how many spaces or line breaks separated it. Character spans can connect pieces back to their positions in the original input.",strips("Offsets preserve a connection to the source text.",[["Piece",["cat,"]],["Source information",["Where it began","Where it ended"]]],true)),
    step("Try writing without those gaps","If the text contains no useful whitespace, this rule may return one long piece. That is a limitation of the boundary assumption, not evidence that the text contains only one word.",strips("One whitespace-free string remains one piece under this rule.",[["Input",["thecatslept"]],["Result",["thecatslept"]]]))
  ],"A simple boundary rule makes a clear assumption",["The full example distinguishes whitespace characters, resulting pieces, and source spans.","More elaborate tokenizers change the boundary rule or add another stage; the vocabulary's ID assignment remains a separate operation."]),
  "unicode-word-boundaries":story(["Spaces are not the only cues around text boundaries. Apostrophes, digits, combining marks, and different scripts need more careful treatment.","Unicode word-boundary rules classify characters and use neighbouring classes to decide where default boundaries belong."],[
    step("Ask about the gap between characters","A boundary decision concerns a position between characters. We need to decide whether the surrounding characters stay together under the rule, rather than simply checking whether the current character is a space.",strips("Potential boundaries lie between input units.",[["Characters",["c","a","t"]],["Question",["Break between these neighbours?"]]])),
    step("Describe character roles","Letters, numbers, marks, and punctuation belong to categories relevant to the rules. The procedure uses those categories to decide which local patterns allow a break.",strips("Character categories provide the rule's vocabulary.",[["Examples of roles",["Letter","Number","Combining mark","Punctuation"]]])),
    step("Apply the ordered boundary rules","Some neighbouring categories stay together; others permit a boundary. Context can require looking beyond an immediately adjacent mark. The result follows the selected standard rules rather than a learned word list.",strips("A rule-based decision process.",[["Character classes",["Inspect relevant neighbours"]],["Boundary rules",["Keep together or separate"]]],true)),
    step("Distinguish default boundaries from linguistic understanding","A default boundary algorithm is not a dictionary or full language analyzer. Some scripts and tasks require additional segmentation. The detailed implementation also has its own documented coverage.",strips("The output is a boundary proposal under specified rules.",[["Provides",["Default text boundaries"]],["May still need",["Language-specific segmentation","Task-specific handling"]]]))
  ],"Character classes make the boundary rule more expressive",["The detailed examples inspect which rule acts at each boundary and compare the result with whitespace splitting.","Use the documented rule version and implementation coverage when interpreting edge cases."]),
  "penn-treebank-rules":story(["A grammatical annotation task may need pieces different from those produced by spaces alone. A contraction can contain parts an annotator wants to label separately, and punctuation may need its own unit.","Penn Treebank-style tokenization applies conventions chosen for that kind of annotation."],[
    step("Start with the annotation question","The aim is to provide units that an annotation scheme can label consistently. The output therefore reflects the scheme's conventions, not one universal definition of a word.",strips("A contraction and punctuation present separate decisions.",[["Text",["They didn't leave."]]])),
    step("Split a contraction into the chosen units","The convention can separate the verbal part from the negation ending. This is a rule about annotation units; it need not preserve a whole contraction as one piece.",strips("A familiar Treebank-style contraction split.",[["Original",["didn't"]],["Pieces",["did","n't"]]])),
    step("Give punctuation its own representation","Other rules separate punctuation and may normalize certain written forms. Each transformation changes what a downstream tagger or parser receives.",strips("A sentence can become word and punctuation units.",[["Pieces",["They","did","n't","leave","."]]])),
    step("Check what can be reconstructed","Normalized output may not preserve the original spelling or spacing exactly. Keep source spans or original text when exact reconstruction is required.",strips("Annotation tokens and source text are different artifacts.",[["Tokens",["Conventional analysis units"]],["Source",["Original spelling and layout"]]]))
  ],"The downstream task explains the token choices",["The full examples show contractions, punctuation, normalization, and implementation limits.","These conventions are useful for a particular processing tradition; they are not a claim that every language should be tokenized the same way."]),
  "moses-rules":story(["A translation system can read a sentence as pieces and later produce another sequence of pieces. Those outputs must be assembled into readable text.","Moses-style rules consider punctuation, escaping, and reconstruction as part of a processing pipeline rather than treating tokenization as the final output."],[
    step("Separate processing units from displayed text","The translation model may need punctuation as separate units even though a reader expects it attached in ordinary writing. The internal representation and final display serve different purposes.",strips("A simple sentence before processing.",[["Readable text",["Hello, world!"]]])),
    step("Prepare consistent internal pieces","Rules separate selected punctuation and handle special characters according to the implementation. The aim is a consistent input representation for the downstream system.",strips("An illustrative punctuation split.",[["Processing pieces",["Hello",",","world","!"]]])),
    step("Remember that output pieces need assembling","After processing, detokenization applies rules to join pieces into readable text. Blindly inserting a space between every piece would put unwanted gaps before punctuation.",strips("Reconstruction has its own rules.",[["Pieces",["Hello",",","world","!"]],["Readable result",["Hello, world!"]]],true)),
    step("Check exactness rather than assuming it","Normalization and escaping may change the original representation. A readable reconstruction is not necessarily a byte-for-byte copy. Test the required round trip under the actual rule set.",strips("Two different reconstruction goals.",[["Readable output",["Natural spacing and punctuation"]],["Exact reconstruction",["Original characters and layout"]]]))
  ],"The input and output conventions belong together",["The detailed examples inspect token boundaries, spans, escaping, and detokenization behaviour.","This SDK implements a stated subset of conventions. Its actual results, rather than the family name alone, define its contract."]),
  "the-pattern-language-models-use":story(["A language-model tokenizer may preserve spaces differently from a word splitter. For example, the space before a word can travel with that word's piece.","A regular-expression pretokenizer groups text before a later vocabulary algorithm processes it. Those preliminary groups are not yet the final model tokens."],[
    step("Keep whitespace in the problem","Dropping all separators can lose information a model or decoder needs. We first decide how whitespace travels through the segmentation process.",strips("A visible space is shown as a marked item for inspection.",[["Text units",["Hello","space","world"]]])),
    step("Attach a leading space under a chosen rule","Some pattern branches can group a space with following letters. This makes a word after a space a different surface piece from the same letters at the beginning of text.",strips("Illustrative preliminary groups. The ␠ symbol makes the space visible here; it is not a literal character inserted by the pattern.",[["Beginning",["Hello"]],["After a separator",["␠world"]]])),
    step("Use different branches for different character runs","Letters, digits, punctuation, and whitespace can follow different pattern branches. Their ordering and exact definitions affect the preliminary groups produced.",strips("The pattern distinguishes types of runs.",[["Branches inspect",["Letters","Digits","Punctuation","Whitespace"]]])),
    step("Pass those groups to the next stage","A subword algorithm can split or merge inside the permitted groups. The pretokenizer constrains where later pieces can form; it does not by itself assign the final vocabulary IDs.",strips("Two distinct stages in the tokenizer.",[["Pattern stage",["Preliminary text groups"]],["Vocabulary stage",["Final pieces and IDs"]]],true))
  ],"The pattern defines boundaries for a later algorithm",["The full lesson follows the specific expression implemented here and shows which branch matches each stretch of text.","Different tokenizer families and regex engines can differ. The example does not claim that every language model uses one universal pattern."]),
  "bytes-and-characters":story(["A word vocabulary can encounter a spelling it never learned. Smaller units can represent unfamiliar words without storing each whole word in advance.","Characters and bytes provide different starting alphabets. We need to see how they relate before calling either one a token."],[
    step("Begin with the text a reader sees","The word café contains a letter outside basic ASCII. Its visible appearance, Unicode code points, and encoded bytes are related but are not the same representation.",strips("One short word to follow.",[["Visible text",["café"]]])),
    step("Inspect the character-level units","A character-oriented procedure can operate on Unicode code points. Even this is not always the same as one visible symbol, since combining marks can participate in a displayed character.",strips("This precomposed spelling has four code points.",[["Code-point pieces",["c","a","f","é"]]])),
    step("Encode the text as bytes","UTF-8 represents the selected é with two bytes. A complete byte alphabet can name both without needing a whole-word or whole-character vocabulary entry for this spelling.",strips("UTF-8 byte values for the displayed precomposed spelling.",[["Bytes",["99","97","102","195","169"]]])),
    step("Trade coverage against sequence length","Byte coverage avoids unknown encoded byte values, but can require more sequence positions. Decoding also needs a valid byte sequence; one byte taken from a multi-byte character may not decode alone.",strips("Coverage does not imply a short sequence or learned meaning.",[["Benefit",["A fixed complete byte alphabet"]],["Cost",["Potentially more positions"]]]))
  ],"Encoding units and model tokens need not coincide",["The full example compares character and byte tokenization, sequence lengths, and reconstruction.","A tokenizer can merge bytes into larger pieces later. That changes the token vocabulary without changing UTF-8 itself."]),
  "hashing-characters":story(["A learned vocabulary can keep expanding as new characters or pieces arrive. Sometimes we want a fixed-size representation regardless of how many different inputs we see.","Hashing assigns inputs to a limited set of buckets using a repeatable rule. The price of bounded storage is possible ambiguity."],[
    step("Choose a fixed set of destinations","Instead of adding a new vocabulary row for every distinct input, allocate a fixed number of buckets. New inputs must use these existing destinations.",strips("A small illustrative bucket set.",[["Available buckets",["0","1","2","3"]]])),
    step("Apply the same rule every time","A deterministic hash sends the same input to the same destination under the same configuration. The destination is computed rather than learned as a meaning.",strips("Illustrative assignments, not this SDK's actual hash output.",[["Input a",["Bucket 2"]],["Input a again",["Bucket 2"]]])),
    step("Notice when different inputs share a bucket","There are more possible inputs than destinations, so different inputs can collide. A bucket ID alone cannot tell us which collided input produced it.",strips("A deliberately chosen collision.",[["Input a",["Bucket 2"]],["Different input b",["Bucket 2"]]])),
    step("Use several hashes without promising uniqueness","Multiple independent hash configurations can provide a larger signature and reduce some collisions. They still do not make every possible input uniquely decodable in a bounded representation.",strips("A signature combines several bucket assignments.",[["One input",["Hash A bucket","Hash B bucket","Hash C bucket"]]]))
  ],"Fixed storage accepts some ambiguity",["The numerical example shows the SDK's actual hashes and collision patterns as bucket counts change.","Keep the configuration fixed across training and prediction. Hash IDs do not learn semantic similarity and generally cannot reconstruct the input uniquely."]),
};
