import { bars, plot, step, story, strips, tiles, type LessonIntuition } from "./types";
const corner=[[0,0,0,0,0],[0,1,1,1,1],[0,1,1,1,1],[0,1,1,1,1],[0,1,1,1,1]];
const cornerTurned=[[0,1,1,1,1],[0,1,1,1,1],[0,1,1,1,1],[0,1,1,1,1],[0,0,0,0,0]];
const cross=[[0,0,1,0,0],[0,0,1,0,0],[1,1,1,1,1],[0,0,1,0,0],[0,0,1,0,0]];
const shifted=[[0,0,0,1,0],[0,0,0,1,0],[0,1,1,1,1],[0,0,0,1,0],[0,0,0,1,0]];
const edge=[[0,0,1,1],[0,0,1,1],[0,0,1,1],[0,0,1,1]];
export const vision:Record<string,LessonIntuition>={
  "filters-and-edges":story(["A bright pixel does not tell us whether it belongs to a shape or simply received more light. A boundary is often better described by how brightness changes between neighbouring pixels.","An edge filter looks for local differences rather than treating brightness alone as the answer."],[
    step("Start with neighbouring brightness values","The dark region and bright region meet at a boundary. The useful clue is their contrast across nearby positions. Neither region's brightness by itself identifies the boundary.",tiles("A small illustrative brightness boundary.",[["Input",edge]])),
    step("Compare the two sides of a local window","A filter can give opposite signs to pixels on opposite sides. Similar brightness on both sides cancels; a difference produces a response. Its weights define which direction it compares.",tiles("Outlined cells straddle the boundary.",[["Local comparison",edge,[5,6,9,10]]])),
    step("Repeat the comparison across the picture","Move the same filter over the image. Locations with the kind of brightness change it measures receive stronger responses. A second directional filter can measure changes along another axis.",strips("Different filters ask different local questions.",[["First direction",["Brightness change left to right"]],["Second direction",["Brightness change top to bottom"]]])),
    step("Interpret a response as evidence of change","Noise, texture, and illumination changes can also produce responses. An edge map is a measurement of local change, not a complete description of which object caused it.",strips("A strong response needs context.",[["Possible causes",["Object boundary","Texture","Noise","Lighting change"]]]))
  ],"The filter weights formalize a local comparison",["The next example calculates one window's response, then shows the complete sweep and border handling.","Gradient magnitude and direction combine the directional responses. Thresholding them is another choice to inspect, not a guarantee of correct object boundaries."]),
  "histogram-of-oriented-gradients":story(["Two images of the same shape can differ in brightness while retaining a similar arrangement of local boundaries. We want a description based on those patterns rather than every raw pixel value.","HOG summarizes directions of brightness change within small regions, then normalizes neighbouring summaries."],[
    step("Look at changes rather than absolute brightness","A vertical boundary produces a left-to-right brightness change. The gradient points in the direction of change, which differs from the direction along the boundary itself.",tiles("The boundary is vertical; brightness changes across it horizontally.",[["Local image",edge]])),
    step("Let local changes vote for directions","Inside one cell, each gradient contributes to direction bins, usually weighted by its strength. The result describes which change directions are common in that region.",bars("Schematic direction votes for a region dominated by a vertical edge.",[["Horizontal brightness change",8,"Strong evidence"],["Diagonal brightness change",1,"Little evidence"],["Vertical brightness change",0,"No evidence in this idealized patch"]])),
    step("Normalize neighbouring cells together","Contrast can change the overall size of the votes. Block normalization compares neighbouring cell summaries on a common scale, reducing sensitivity to some lighting changes.",strips("Local summaries are normalized in spatial blocks.",[["Cells",["Direction counts A","Direction counts B"]],["Block normalization",["Relative directional pattern"]]],true)),
    step("Keep the spatial arrangement of summaries","A descriptor concatenates the normalized summaries in a fixed order. It keeps a coarse account of where directions occur while discarding much pixel-level detail.",strips("Descriptor order preserves a coarse spatial layout.",[["Upper cells",["Their direction summaries"]],["Lower cells",["Their direction summaries"]],["Descriptor",["Ordered collection of summaries"]]],true))
  ],"The descriptor summarizes local structure",["The detailed calculation follows a gradient into bins, handles vote sharing, and applies block normalization.","HOG is not automatically invariant to rotation, deformation, or every lighting change. The full comparison makes those limits visible."]),
  "template-matching":story(["Suppose we have a small picture of a known pattern and want to find it inside a larger image. We are asking where that particular appearance occurs, rather than learning a general category.","Template matching moves the reference patch across the image and compares each candidate location."],[
    step("Keep the reference patch in view","The template records a particular arrangement of pixels. The search image may contain that arrangement somewhere else. Shape, size, and orientation are part of what is being compared.",tiles("An illustrative reference patch.",[["Template",[[0,1,0],[1,1,1],[0,1,0]]]])),
    step("Compare one candidate location","Place the reference over a same-sized image window. A scoring rule compares corresponding values. Different scores respond differently to brightness offsets and contrast changes.",tiles("A candidate window is selected for comparison.",[["Search window",cross,[6,7,8,11,12,13,16,17,18]]])),
    step("Repeat and keep the location scores","Every valid placement receives a score. The best location is the strongest candidate under that rule. A score map lets us inspect whether the match is isolated or one of several similar possibilities.",strips("The search produces scores indexed by position.",[["Candidate windows",["Position A","Position B","Position C"]],["Comparison results",["Score A","Score B","Score C"]]])),
    step("Ask whether the best candidate is good enough","Even an image without the template has a best-scoring location. Check absolute match quality and competing peaks. A changed scale or angle may require a different search strategy.",strips("Best among candidates is not the same as a confirmed match.",[["Check",["Strength of the peak","Other plausible peaks","Expected size and angle"]]]))
  ],"A match score needs a reference and a decision rule",["The full experiment calculates several matching scores and compares them under changed illumination and appearance.","Its exact scan is restricted to the candidate sizes and orientations actually evaluated."]),
  "keypoints-and-descriptors":story(["Two pictures of the same scene may be shifted or viewed differently. We want to know which locations correspond. Comparing every patch is costly, and many blank or repetitive patches are ambiguous.","First choose distinctive locations, then describe their local appearance, then compare those descriptions."],[
    step("Notice which locations are hard to recognize","A uniform patch looks much like nearby uniform patches. Along one straight edge, many locations also resemble one another. Corners or textured regions can provide more distinctive local evidence.",tiles("A cross intersection provides changes in several directions.",[["Candidate location",cross,[12]]])),
    step("Choose repeatable keypoints","A detector scores locations for a specified local property. Retain useful candidates that can potentially be found again in another image. A keypoint is a location, not yet a complete description.",tiles("A selected location in one image.",[["Detected candidate",cross,[12]]])),
    step("Describe the neighbourhood","Build a descriptor from values around the selected location. The descriptor summarizes appearance for comparison; its design controls sensitivity to rotation, scale, brightness, and noise.",strips("Detection and description produce different objects.",[["Keypoint",["Where to look"]],["Descriptor",["What the neighbourhood looks like"]]])),
    step("Compare and check candidate correspondences","Find similar descriptors in the second image. Ambiguous or inconsistent pairs should be rejected or checked geometrically. A nearest descriptor alone does not prove two points correspond.",tiles("The same kind of structure appears at shifted locations.",[["First image",cross,[12]],["Shifted image",shifted,[13]]]))
  ],"Find, describe, and match are separate stages",["The detailed lesson calculates the detector responses and descriptors used by this implementation.","Its matching checks show both successful correspondences and ambiguity from repetitive or weak local evidence."]),
  "image-alignment":story(["Two photographs of one scene, one taken with the camera tilted. The keypoints lesson found corners that survive a turn, and then showed that its descriptions do not, because a patch of brightness is read in the frame of the picture and turning the picture turns the patch.","We want to line the two pictures up. That needs descriptions that survive the turn, matches between them, and a way to read the camera's move off the matches."],[
    step("The same corner, turned","A bright corner in the first picture is the same corner in the second, a quarter turn round. Read as a square patch in the picture's frame, the two patches are different arrangements of the same pixels, and a comparison between them fails.",tiles("One corner before and after a quarter turn.",[["First picture",corner,[6]],["Turned picture",cornerTurned,[16]]])),
    step("Give the corner a direction of its own","The brightness around the corner is heavier on one side. The direction from the corner towards that heavier side belongs to the corner, and when the picture turns, the direction turns with it.",tiles("The bright side is below and to the right in the first picture, and above and to the right after the turn.",[["First picture",corner,[6,12,18,24]],["Turned picture",cornerTurned,[16,12,8,4]]])),
    step("Read the patch in that frame","Instead of reading the patch with the picture's up as up, read it with the corner's direction as its first axis. The turned picture turns the direction too, so the patch is read the same way both times and the two readings agree.",strips("The same reading, two frames.",[["Picture's frame",["Reading before","Reading after, different"]],["Corner's frame",["Reading before","Reading after, the same"]]])),
    step("Two matches fix the move, the rest vote","A turn, a change of size and a shift are four numbers, and two matched corners are enough to fix them. Every other match either lands where that move sends it or does not. The move that the most matches agree with is the one to keep, and the matches that disagree are the mistakes.",strips("A proposal from one pair, and the matches that agree with it.",[["Proposed from",["corner A to A'","corner B to B'"]],["Agree",["C to C'","D to D'","E to E'"]],["Disagree",["F to the wrong corner"]]]))
  ],"Direction first, then description, then the move",["The detailed lesson gives each corner a direction two ways, ORB's centre of brightness and SIFT's dominant gradient, and reads the patch in that frame two ways, as pixel pairs and as a grid of gradient counts.","It then recovers a planted move from the matches, names the matches that were wrong, and carries the second picture back onto the first, with every number computed on the shared scene."]),
  "haar-cascades":story(["Searching every image window with an expensive detector wastes work on obvious nonmatches. We would like to reject easy cases quickly and reserve more checks for plausible candidates.","A cascade places inexpensive decisions early and lets surviving windows continue to later stages."],[
    step("Treat each window as a candidate","The target can occur at different positions, so a detector inspects candidate windows. Most may contain background. The amount of work per rejected window matters.",strips("A schematic set of candidate windows.",[["Candidates",["A","B","C","D","E","F"]]])),
    step("Ask a cheap brightness-contrast question","Haar-like features compare sums over neighbouring rectangles. An integral image makes rectangular sums inexpensive to obtain. The feature measures a selected brightness arrangement, not a semantic object by itself.",tiles("An illustrative bright band among darker rows.",[["Brightness arrangement",[[0,0,0,0],[1,1,1,1],[1,1,1,1],[0,0,0,0]]]])),
    step("Reject easy negatives early","A stage combines feature tests into a decision. Windows rejected at this stage do not pay for later checks. The stage must be chosen carefully because an early rejection cannot be repaired downstream.",strips("Illustrative survivors, not measured detection rates.",[["Initial windows",["A","B","C","D","E","F"]],["After an early stage",["B","D","F"]],["After a later stage",["D"]]],true)),
    step("Evaluate the entire sequence","A useful cascade balances computation, missed targets, and false positives. The order of stages affects cost because early stages see more windows than later ones.",strips("Both accuracy and work depend on the stage sequence.",[["Early stages",["Many windows","Cheap rejection"]],["Later stages",["Fewer survivors","Further checking"]]]))
  ],"The ordering is part of the method",["The full example uses its own labeled bright-band task, not a general-purpose face detector. It measures which windows survive each stage.","The calculations introduce integral-image sums, feature responses, and the cost of the complete scan."]),
  "a-vector-for-a-picture":story(["Two pictures can show the same kind of shape at different positions. Their raw pixel values may differ greatly even when we consider the pictures similar.","A learned image representation can give us a comparison that reflects a training task rather than only pixel-by-pixel agreement."],[
    step("Keep the object idea separate from pixel alignment","These crosses occupy different locations. A raw pixel comparison treats many cells as disagreements. That may be a poor description of the similarity we wanted.",tiles("Illustrative pictures with shifted structure.",[["First picture",cross],["Shifted picture",shifted]])),
    step("Read the picture through a trained network","A classifier transforms pixels into intermediate responses before naming a category. Those responses may contain information useful for distinguishing shape kinds across appearance changes.",strips("Classification training can produce intermediate representations.",[["Pixels",["Image input"]],["Learned layers",["Intermediate responses"]],["Classifier",["Category prediction"]]],true)),
    step("Use an intermediate response as the vector","Choose a layer and retain its output as the picture's representation. Each image becomes a list of values that can be compared using a specified rule.",strips("The chosen layer defines what vector is extracted.",[["Picture A",["Vector A"]],["Picture B",["Vector B"]],["Comparison",["Distance or similarity between vectors"]]])),
    step("Check what the representation actually preserves","A vector trained for known categories may ignore distinctions important for another task. Test neighbours on excluded pictures and unfamiliar types instead of assuming all meaningful similarity was learned.",strips("Useful checks go beyond the training categories.",[["Inspect",["Held-out neighbours","Changed appearance","Unseen shape kinds"]]]))
  ],"A representation inherits the task that shaped it",["The full lesson extracts vectors from a trained shape classifier and compares them with raw pixels.","Layer choice, comparison rule, and training coverage all affect what nearby vectors mean."]),
  "learning-the-metric-itself":story(["A classifier learns to name categories, but its internal distances were not necessarily optimized for finding matches. If matching is the goal, we can train from pairs that explicitly say what should count as similar.","Metric learning adjusts a representation so the pairwise comparisons serve that task."],[
    step("Define similarity with labeled pairs","A matching pair says these two observations should be near under the intended representation. A nonmatching pair says they should be distinguishable. These pair labels provide the supervision.",strips("Illustrative pair labels define the task.",[["Pair one",["Two crosses","Match"]],["Pair two",["Cross and square","Do not match"]]])),
    step("Use the same encoder on both inputs","Both pictures pass through an encoder with shared parameters. This puts their outputs in the same learned coordinate system. Separate unrelated encoders would not automatically make comparable vectors.",strips("One shared transformation reads either side.",[["Left picture",["Shared encoder","Left vector"]],["Right picture",["Shared encoder","Right vector"]]])),
    step("Reward useful distances","A pair-based loss pulls appropriate matches together and discourages unwanted closeness for nonmatches. The loss defines the kind of separation being trained.",plot("A schematic desired arrangement, not fitted coordinates.",[[1,1,0],[1.3,1.2,0],[4,3,1],[4.3,3.2,1]],"Representation coordinate one","Representation coordinate two")),
    step("Prevent a trivial collapse","Putting every input at one point would make all matching distances small, but would also erase distinctions between nonmatches. Inspect both pair types and evaluate new observations.",strips("Both sides of the objective matter.",[["Matches",["Should receive useful closeness"]],["Nonmatches",["Should retain useful separation"]]]))
  ],"The training target is the relationship between inputs",["The detailed contrastive calculation shows how matching and nonmatching pairs contribute differently and where the margin acts.","Shared weights and held-out evaluation are essential to interpreting the learned distance."]),
  "searching-a-collection-of-pictures":story(["Once every picture has a vector, a query picture can ask which stored vectors are nearest. Comparing with every entry is straightforward, but becomes expensive as the collection grows.","An index reduces the candidates examined. That saves work by making an explicit tradeoff about what might be missed."],[
    step("Turn the query into the same representation","Use the same encoder and preprocessing for the query and stored pictures. A nearest-neighbour search needs comparable coordinates before any indexing strategy can help.",strips("Query and collection share one representation.",[["Stored pictures",["Stored vectors"]],["Query picture",["Query vector"]]])),
    step("Establish the exact answer","An exhaustive search compares the query with every stored vector under the chosen metric. This gives a reference result for judging approximate search.",strips("Exact search inspects the entire collection.",[["Candidates checked",["A","B","C","D","E","F"]]])),
    step("Use an index to narrow the candidates","A coarse grouping or hash code can direct the query toward part of the collection. Then compare the surviving candidates more carefully. The index's partition is a search device, not a semantic guarantee.",strips("Illustrative candidate reduction.",[["Collection groups",["Group one","Group two","Group three"],[1]],["Candidates inspected",["C","D"]]],true)),
    step("Measure both speed and missed neighbours","A shorter candidate list saves comparisons but may omit a true nearest neighbour. Compare approximate results with exhaustive results, and evaluate the actual cost rather than assuming an index always helps.",strips("Two outcomes must be measured together.",[["Efficiency",["How much work was avoided?"]],["Recall",["Which exact neighbours were recovered?"]]]))
  ],"An index changes search effort, not the meaning of the vectors",["The full experiment compares exact search with the implemented indexing methods and their recall-cost tradeoffs.","Representation quality remains a separate limitation: fast retrieval cannot repair an inappropriate notion of similarity."]),
};
