"use client";

import { useState } from "react";
import Link from "next/link";
import { Botie,BotieSays } from "@/components/site/Botie";
import { BuildWorkshop } from "./BuildWorkshop";
import { TOOLS } from "@/lib/builds/tools";
import { show,type Data,type Settings } from "@/lib/builds/engine";
import type { JourneyData } from "@/lib/builds/journey";

const button="min-h-11 rounded-lg border border-line bg-raised px-4 py-2 text-sm font-semibold hover:border-accent-fill";
const primary="min-h-11 rounded-lg bg-accent-fill px-5 py-2 text-sm font-semibold text-accent-ink";
const phases=["The problem and its history","Get to know the tools","Build your solution","Explain it and write it"];

export function WorkshopJourney({data}:{data:JourneyData}){
  return <Journey key={data.build.id} data={data}/>;
}

function Journey({data}:{data:JourneyData}){
  const [phase,setPhase]=useState(0),[chapter,setChapter]=useState(0);
  const [openedBuild,setOpenedBuild]=useState(false);
  const guide=data.build.id==="workshop-guide";
  function go(index:number){setPhase(index);if(index===2)setOpenedBuild(true);}
  const block=data.history.blocks[chapter];
  return <div data-testid="workshop-journey" className="min-w-0">
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3 text-sm"><p className="font-mono text-xs text-muted">{data.lesson.section} · A journey with Botie</p>{!guide&&<Link href="/lab/workshop-guide" className="min-h-11 content-center text-accent underline underline-offset-4">First visit? Learn the workshop controls</Link>}</div>
    <nav aria-label="Journey stages" className="mb-7 flex gap-2 overflow-x-auto pb-2">{phases.map((name,i)=><button key={name} onClick={()=>go(i)} aria-current={phase===i?"step":undefined} className={`${button} shrink-0 ${phase===i?"!border-accent-fill !bg-accent-soft text-accent":"text-muted"}`}><span className="mr-2 font-mono text-xs">0{i+1}</span>{name}</button>)}</nav>
    {phase===0&&<div className="mx-auto max-w-3xl"><div className="mb-5 flex items-center gap-4"><Botie size={78}/><div><p className="text-xs text-accent">Botie&apos;s notebook</p><h2 className="mt-1 text-2xl font-semibold">{data.history.title}</h2></div></div><p className="mb-3 text-xs text-muted">Part {chapter+1} of {data.history.blocks.length}</p><div className="rounded-2xl border border-line bg-surface p-5 sm:p-7" aria-live="polite">{typeof block==="string"?<p className="leading-8">{block}</p>:<ol className="list-decimal space-y-5 pl-5">{block.items.map(item=><li key={item.name}><strong>{item.name}.</strong><p className="mt-1 leading-7 text-muted">{item.explanation}</p></li>)}</ol>}</div><div className="mt-5 flex flex-wrap justify-between gap-3"><button className={button} disabled={chapter===0} onClick={()=>setChapter(c=>c-1)}>← Previous part</button><button className={primary} onClick={()=>chapter+1<data.history.blocks.length?setChapter(c=>c+1):go(1)}>{chapter+1<data.history.blocks.length?"Continue with Botie →":"Look at the tools →"}</button></div>{data.history.sources.length>0&&<details className="mt-6 rounded-xl border border-line p-4"><summary className="cursor-pointer text-sm font-semibold">Sources for this history</summary><ul className="mt-3 space-y-3 text-xs leading-6">{data.history.sources.map(source=><li key={source.url}><a href={source.url} target="_blank" rel="noopener noreferrer" className="text-accent underline underline-offset-4">{source.title}</a></li>)}</ul></details>}</div>}
    {phase===1&&<div className="mx-auto max-w-4xl"><BotieSays>{data.build.problem}</BotieSays><p className="mt-4 text-sm leading-7 text-muted">Before we build, try the pieces below. What information does each one need, and which piece could use its result?</p><div className="mt-5 rounded-xl border border-accent-fill/40 bg-accent-soft p-5"><h3 className="font-semibold">The problem we will build for</h3><p className="mt-2 text-sm leading-7">{data.build.challenge}</p></div><div className="mt-6 space-y-4">{data.tools.map(item=><details key={item.key} className="rounded-2xl border border-line bg-surface p-5" open={!item.earlier}><summary className="cursor-pointer font-semibold">{TOOLS[item.key].title}<span className="ml-3 text-xs font-normal text-accent">{item.earlier?"A tool you have used before":"A tool for this part of the journey"}</span></summary><p className="mt-3 text-sm leading-7 text-muted">{TOOLS[item.key].why}</p>{item.earlier&&<p className="mt-2 text-xs">We used this in <a href={item.earlier.href} className="text-accent underline">{item.earlier.title}</a>.</p>}<p className="mt-3 text-xs text-muted">{TOOLS[item.key].inputs.length?`Inputs: ${TOOLS[item.key].inputs.join("; ")}. One round output carries the result.`:"This piece supplies a value without receiving an input."}</p>{item.example&&<ToolExample toolKey={item.key} example={item.example}/>}</details>)}</div>{guide&&<div className="mt-6 rounded-xl border border-line bg-surface p-5"><h3 className="font-semibold">Moving around the workshop</h3><ol className="mt-3 list-decimal space-y-3 pl-5 text-sm leading-7 text-muted"><li>Choose a tool from the shelf to place it. Drag from the shelf if you want a particular spot.</li><li>Start at the round output arrow. Click it and then click a square input, or drag the arrow onto the input. You can reuse an output on more than one input. Escape cancels a connection.</li><li>Move a piece by its name. Select the name to read its purpose and inspect its current calculation. Arrow keys move a focused piece.</li><li>Run one example first. Pause or step through to find where an unexpected result begins. Then test all examples.</li><li>Select a piece or wire and press Delete to remove it. Removing a piece also removes its wires. Undo restores your last edit. You can inspect a worked construction whenever you need one.</li></ol></div>}<button className={`${primary} mt-6`} onClick={()=>go(2)}>Open the empty workshop →</button></div>}
    {openedBuild&&<div hidden={phase!==2}><BuildWorkshop build={data.build} guide={guide}/></div>}
    {phase===2&&<div className="mt-6 flex flex-wrap justify-between gap-3"><button className={button} onClick={()=>go(1)}>← Revisit a tool</button><button className={primary} onClick={()=>go(3)}>Explain what your machine does →</button></div>}
    {phase===3&&<div className="mx-auto max-w-3xl"><BotieSays>Before moving on, follow one example through your construction. Where did the information come from? What did each operation change? Which connection would you inspect first if the answer were wrong?</BotieSays><p className="mt-5 text-sm leading-7 text-muted">{data.build.why}</p>{!guide&&<a href={`${data.lesson.href}#practice`} className={`${primary} mt-5 inline-block`}>Write the calculation in Python →</a>}<p className="mt-3 text-xs leading-6 text-muted">You can return to the construction or read further at any time. The next lesson is available without a score or an account.</p>{data.next&&<a href={data.next.href} className="mt-7 block rounded-xl border border-line bg-surface p-5 hover:border-accent-fill"><span className="text-xs text-muted">Continue the journey with Botie</span><span className="mt-2 block font-semibold text-accent">{data.next.title} →</span></a>}</div>}
    <div className="mt-8 flex flex-wrap justify-between gap-4 border-t border-line pt-5 text-xs">{data.previous?<a href={data.previous.href} className="text-muted hover:text-foreground">← Previous lesson: {data.previous.title}</a>:<Link href="/lab" className="text-muted">← The journey map</Link>}{!guide&&<a href={data.lesson.href} className="text-accent underline underline-offset-4">Read the full lesson and derivations</a>}</div>
  </div>;
}

function ToolExample({toolKey,example}:{toolKey:string;example:{inputs:Data[];settings:Settings;output:Data}}){
  const tool=TOOLS[toolKey];
  const [input,setInput]=useState(example.inputs.map(value=>typeof value==="string"?value:show(value))),[settings,setSettings]=useState(example.settings);
  let output:string;
  try {const values=input.map((value,i)=>typeof example.inputs[i]==="string"?value:JSON.parse(value));const result=tool.run(values,settings);const check=(value:Data):void=>{if(typeof value==="number"&&!Number.isFinite(value))throw Error("This result is not a finite number. Check the inputs, including any divisor.");if(Array.isArray(value))value.forEach(check);else if(value&&typeof value==="object")Object.values(value).forEach(check);};check(result);output=show(result);}catch(e){output=e instanceof Error?e.message:"These inputs cannot be used by this tool.";}
  return <div className="mt-4 rounded-xl border border-line bg-raised p-4"><p className="mb-3 text-xs font-semibold">Try this piece on its own</p>{tool.inputs.map((name,i)=><label key={name} className="mb-3 block text-xs text-muted">{name}<textarea value={input[i]} onChange={e=>setInput(values=>values.map((value,j)=>i===j?e.target.value:value))} rows={Array.isArray(example.inputs[i])?2:1} spellCheck={false} className="mt-2 w-full rounded-lg border border-line bg-background p-3 font-mono text-sm text-foreground" aria-label={`${tool.title} example: ${name}`}/></label>)}{tool.settings?.map(setting=><label key={setting.key} className="mt-3 flex flex-wrap items-center gap-3 text-xs">{setting.label}<input className="min-h-11 rounded border border-line bg-background px-3 text-foreground" type={typeof setting.initial==="number"?"number":"text"} step={setting.step} value={settings[setting.key]} onChange={e=>setSettings(s=>({...s,[setting.key]:typeof setting.initial==="number"?Number(e.target.value):e.target.value}))}/></label>)}<p className="mb-2 mt-3 text-xs text-muted">Output</p><pre className="max-h-40 overflow-auto whitespace-pre-wrap break-words rounded-lg bg-background p-3 font-mono text-sm text-accent" aria-live="polite">{output}</pre></div>;
}
