import { type Mission, dial, num, list, row, mean, dot } from "./types";

const readings = (xs: number[], f: (x: number) => number, target: (x: number) => number) => xs.map((x, i) => row(`Parcel ${i + 1}`, `Measurement: ${x}`, f(x), target(x)));
export const foundations: Mission[] = [
  {
    id: "statistics", title: "Balance the delivery", story: "Botie has five boxes of different masses. If we replaced them with five identical boxes, how heavy would each one need to be to keep the same total? This gives us a reason to care about the mean.",
    task: "Set the replacement mass so the total mass stays the same.", controls: [dial("mass", "Mass of each replacement box", 0, 12, .5)], initial: { mass: 2 }, solution: { mass: 6 },
    hint: "Add the five masses, then share that total equally among five boxes.", success: "The total is unchanged. The mean is the amount each box would have if the total were shared equally; it does not say that the original boxes were identical.", rule: "replacement total = number of boxes × replacement mass",
    run: (v, b) => { const xs = b ? [2, 4, 6, 8, 10] : [3, 5, 6, 7, 9]; return { readings: [row("Total mass", `Original boxes: ${xs.join(", ")}`, num(v, "mass") * xs.length, xs.reduce((a, x) => a + x, 0), `5 × ${num(v, "mass")}`), row("Balance", "Total difference from the replacement mass", xs.reduce((s, x) => s + x - num(v, "mass"), 0), 0)] }; },
  },
  {
    id: "linear-algebra", title: "Wire the mixing machine", story: "Botie needs a machine that combines two measurements for each parcel. A matrix is a convenient way to keep the measurements together. A vector holds the contribution we want from each column.", task: "Make the output count two units for height and subtract one unit for mass.", controls: [dial("h", "Height contribution", -3, 3), dial("m", "Mass contribution", -3, 3)], initial: { h: 1, m: 1 }, solution: { h: 2, m: -1 }, hint: "Each row is one parcel. Multiply its height by two and its mass by negative one, then add the contributions.", success: "The same vector worked on every row. Matrix-vector multiplication repeats that weighted sum without needing a separate rule for each parcel.", rule: "output = height × height weight + mass × mass weight",
    run: (v, b) => ({ readings: (b ? [[2, 5], [4, 1], [0, 3]] : [[1, 2], [3, 1], [2, 2]]).map((x, i) => row(`Parcel ${i + 1}`, `Height, mass: [${x}]`, dot(x, [num(v, "h"), num(v, "m")]), dot(x, [2, -1]), `${x[0]} × ${num(v, "h")} + ${x[1]} × ${num(v, "m")}`)) }),
  },
  {
    id: "calculus", title: "Find the bottom of the bowl", story: "Botie's cart is on a smooth bowl. The slope tells us which direction rises, so moving in the opposite direction can take us downhill. Let us see that before asking an optimiser to do it.", task: "Move the cart to the lowest point. Check both the height and the slope there.", controls: [dial("x", "Cart position", -2, 6, .25)], initial: { x: -1 }, solution: { x: 2 }, hint: "Move right while the slope is negative. When it becomes positive, you have gone past the bottom.", success: "At this bowl's minimum the slope is zero. A zero derivative alone does not always mean a minimum; here the bowl rises on both sides.", rule: "height = (position − 2)²\nslope = 2 × (position − 2)", run: v => ({ readings: [row("Height", "Distance above the bottom", (num(v, "x") - 2) ** 2, 0), row("Slope", "Change in height per small change in position", 2 * (num(v, "x") - 2), 0)], scene: { kind: "plot", x: "Position", y: "Height", points: [[num(v, "x"), (num(v, "x") - 2) ** 2]], line: Array.from({ length: 33 }, (_, i) => [-2 + i / 4, (-4 + i / 4) ** 2]) } }),
  },
  {
    id: "simple-linear-regression", title: "Set the delivery estimate", story: "Botie needs to estimate how long a delivery will take. These small, deliberately tidy examples have a fixed preparation time and an extra cost for each kilometre. Can one line account for both?", task: "Adjust the time per kilometre and the preparation time to fit all the deliveries.", controls: [dial("slope", "Minutes per kilometre", 0, 5, .25), dial("bias", "Preparation time", -3, 5, .25)], initial: { slope: 1, bias: 0 }, solution: { slope: 2, bias: 1 }, hint: "Compare two deliveries one kilometre apart. Their difference gives the slope. Then work out what remains at zero kilometres.", success: "One setting now predicts every example in this toy batch. Real measurements usually contain noise, so fitting a line generally means reducing the errors, rather than eliminating them.", rule: "minutes = kilometres × slope + preparation time",
    run: (v, b) => { const xs = b ? [.5, 2.5, 4.5] : [1, 2, 3, 4]; return { readings: readings(xs, x => x * num(v, "slope") + num(v, "bias"), x => 2 * x + 1), scene: { kind: "plot", x: "Kilometres", y: "Minutes", points: xs.map(x => [x, 2 * x + 1]), line: [0, 5].map(x => [x, x * num(v, "slope") + num(v, "bias")]) } }; },
  },
  {
    id: "held-out-evaluation", title: "Keep a delivery unopened", story: "Botie has already fitted a rule using parcels A, B and C. Testing it on those same parcels lets the rule see questions it has already practised. We need examples that played no part in fitting or choosing it.", task: "Choose only the untouched parcels D and E for the final check.", controls: [{ kind: "select", key: "test", label: "Parcels used for the final test", items: ["A (used to fit)", "B (used to fit)", "C (used to fit)", "D (untouched)", "E (untouched)"] }], initial: { test: ["A (used to fit)", "D (untouched)"] }, solution: { test: ["D (untouched)", "E (untouched)"] }, hint: "Leave every parcel that influenced the fitted rule out of this final test.", success: "These examples were held out. Their score is evidence about similar unseen deliveries, not a promise about every future situation.", rule: "test error = mean of the errors on the selected, untouched examples",
    run: v => { const names = list(v, "test"), errors = [0, 0, 0, 2, 4]; return { readings: [row("Untouched examples", "Choose D and E", [...names].sort(), ["D (untouched)", "E (untouched)"]), row("Mean test error", "Errors: A 0, B 0, C 0, D 2, E 4", mean(names.map(n => errors[n.charCodeAt(0) - 65])), 3)], note: "Changing the test examples changes the reported score. It does not improve the fitted model." }; },
  },
  {
    id: "logistic-regression", title: "Where should the gate open?", story: "Botie's classifier gives each parcel a probability of needing inspection. The probability is not yet an instruction to the gate. We still need a threshold for turning that score into a decision.", task: "Route probabilities of 0.6 or more to inspection and leave lower probabilities on the belt.", controls: [dial("threshold", "Inspection threshold", .1, .9, .1)], initial: { threshold: .3 }, solution: { threshold: .6 }, hint: "A parcel at the threshold is inspected. Look at the parcels just below and just above 0.6.", success: "The threshold changed the decisions without changing the model's probabilities. Choosing it in a real task depends on the costs of the two kinds of mistake.", rule: "inspect when probability ≥ threshold", run: (v, b) => ({ readings: readings(b ? [.15, .55, .6, .85] : [.2, .5, .6, .8], x => +(x + 1e-9 >= num(v, "threshold")), x => +(x >= .6)) }),
  },
  {
    id: "judging-a-classifier", title: "Count the right mistakes", story: "Botie's alarm rang for five parcels. Three really needed inspection; two did not. We want to know how often an alarm was justified, so we need precision. Counting every parcel would answer a different question.", task: "Choose the numerator and denominator for precision.", controls: [dial("top", "Correct alarms", 0, 10), dial("bottom", "All alarms", 1, 10)], initial: { top: 3, bottom: 10 }, solution: { top: 3, bottom: 5 }, hint: "Start with the parcels the model flagged. Of those five, three were correct.", success: "Precision describes the alarms we raised. Recall would instead start with all the parcels that actually needed inspection, including any we missed.", rule: "precision = true positives / (true positives + false positives)", run: v => ({ readings: [row("Numerator", "Three true positives", num(v, "top"), 3), row("Denominator", "Three true positives and two false positives", num(v, "bottom"), 5), row("Precision", "Fraction of alarms that were correct", num(v, "top") / num(v, "bottom"), .6)] }),
  },
  ...([
    ["centring-on-the-mean", "Move the zero point", "subtract", "Botie wants to describe a parcel as heavier or lighter than the usual parcel. We can move the reference point from zero to the training mean.", "Subtract the training mean of 6 from each incoming measurement.", 6, 1],
    ["the-standard-score", "Give the ruler a useful unit", "standardise", "A difference of two units might be ordinary for one measurement and unusual for another. Botie needs a ruler that measures differences in standard deviations.", "Use the training mean of 6 and training standard deviation of 2.", 6, 2],
    ["feature-scaling", "Make the two rulers agree", "scale", "One sensor reports centimetres while another reports metres. A distance rule can mistake a larger number for a more important difference. Let us first give the measurements compatible units.", "Convert centimetres to metres by dividing by 100.", 0, 100],
  ] as const).map(([id, title, mode, story, task, centre, scale]): Mission => ({ id, title, story, task, controls: mode === "scale" ? [dial("scale", "Divisor", 10, 200, 10)] : [dial("centre", "Reference point", 0, 10), ...(mode === "standardise" ? [dial("scale", "Standard deviation", 1, 5)] : [])], initial: { centre: 0, scale: mode === "scale" ? 10 : 1 }, solution: { centre, scale }, hint: mode === "scale" ? "One metre contains one hundred centimetres." : "First subtract the mean. If we want standard scores, divide that difference by the training standard deviation.", success: "The same transformation worked on another input. In a fitted pipeline, learn these settings from the training data and reuse them on new examples.", rule: mode === "scale" ? "metres = centimetres / 100" : "transformed value = (value − training mean) / scale", run: (v, b) => ({ readings: readings(mode === "scale" ? (b ? [50, 150, 250] : [100, 200, 300]) : (b ? [3, 7, 9] : [2, 6, 10]), x => (x - num(v, "centre")) / num(v, "scale"), x => (x - centre) / scale) }) })),
  {
    id: "polynomial-features", title: "Measure the missing feature", story: "Botie sees that the cost of a square panel depends on its area, not just the length of one side. A new feature can make that relationship easy for a linear rule to describe.", task: "Choose the power that turns a side length into an area.", controls: [dial("power", "Power of the input", 1, 4)], initial: { power: 1 }, solution: { power: 2 }, hint: "A square has the same length in two directions. Multiply the side length by itself.", success: "The new feature is nonlinear in the original input. A model can still be linear in the coefficients it multiplies those features by.", rule: "area = side²", run: (v, b) => ({ readings: readings(b ? [1.5, 2.5, 3.5] : [1, 2, 3], x => x ** num(v, "power"), x => x * x) }),
  },
  {
    id: "pca", title: "Turn the camera toward the variation", story: "Botie can keep only one coordinate for these points. Looking across the diagonal squashes different points together. Looking along it preserves their separation. PCA searches for the direction with the greatest variation.", task: "Rotate the measuring axis so that none of this toy dataset's variation is discarded.", controls: [dial("angle", "Axis angle in degrees", 0, 180, 15)], initial: { angle: 0 }, solution: { angle: 45 }, hint: "Both coordinates change together. Try a direction halfway between the horizontal and vertical axes.", success: "The points lie exactly on one line, so a single coordinate preserves them here. Real datasets usually leave some variation outside the retained directions.", rule: "projection = x × cos(angle) + y × sin(angle)", run: (v, b) => { const a = num(v, "angle") * Math.PI / 180, xs = b ? [-3, 0, 3] : [-2, -1, 1, 2]; return { readings: xs.map((x, i) => row(`Point ${i + 1}`, `[${x}, ${x}]`, x * (-Math.sin(a) + Math.cos(a)), 0, "Discarded coordinate")), scene: { kind: "plot", x: "First measurement", y: "Second measurement", points: xs.map(x => [x, x]), line: [-4, 4].map(x => [x * Math.cos(a), x * Math.sin(a)]) } }; },
  },
];
