import { type Mission, dial, choose, num, str, list, row, sequence } from "./types";

/** Editable boundaries construct real pieces; no answer is inferred from a button's label. */
function boundaries(id: string, title: string, story: string, input: string, expected: string[], task: string, hint: string, success: string): Mission {
  const chars = Array.from(input);
  const cuts = expected.slice(0, -1).map((_, i) => String(expected.slice(0, i + 1).reduce((s, x) => s + Array.from(x).length, 0)));
  const labels = chars.slice(0, -1).map((c, i) => `${i + 1}: after ${c === " " ? "space" : c}`);
  const solution = labels.filter((_, i) => cuts.includes(String(i + 1)));
  return { id, title, story, task, controls: [{ kind: "select", key: "cuts", label: "Place a boundary after a character", items: labels }], initial: { cuts: solution.length ? [] : [labels[0]] }, solution: { cuts: solution }, hint, success,
    rule: "Read from left to right; a selected boundary ends the current piece.\nThe pieces must reconstruct the input exactly.",
    run: v => { const selected = new Set(list(v, "cuts").map(s => Number(s.split(":")[0]))), pieces: string[] = []; let part = ""; chars.forEach((c, i) => { part += c; if (selected.has(i + 1) || i === chars.length - 1) { pieces.push(part); part = ""; } }); return { readings: [row("Pieces", "Follow the stated rule or supplied vocabulary", pieces, expected), row("Round trip", "Join the pieces without losing a character", pieces.join(""), input)], scene: { kind: "tokens", input, pieces } }; },
  };
}

export const language: Mission[] = [
  {
    id: "what-a-token-is", title: "Give Botie a vocabulary", story: "Botie can store numbers, but the word cat does not yet have a numerical address. A vocabulary provides that address. The ID identifies a token; its magnitude does not describe what the token means.", task: "Use the supplied vocabulary to encode cat, dog and cat again. The vocabulary is cat: 103, dog: 207.", controls: [dial("cat", "ID for cat", 100, 110), dial("dog", "ID for dog", 200, 210)], initial: { cat: 100, dog: 200 }, solution: { cat: 103, dog: 207 }, hint: "Every occurrence of the same token uses the same vocabulary entry. Do not assign a fresh ID for its second appearance.", success: "Both cats received the same ID. We have identified the pieces, but a later embedding step is needed to associate IDs with useful numerical representations.", rule: "token → vocabulary lookup → token ID", run: (v, b) => { const words = b ? ["dog", "cat", "dog"] : ["cat", "dog", "cat"]; return { readings: words.map((w, i) => row(`Position ${i + 1}`, w, num(v, w), w === "cat" ? 103 : 207)), scene: { kind: "tokens", input: words.join(" "), pieces: words.map(w => `${w} → ${num(v, w)}`) } }; },
  },
  {
    id: "bytes-and-characters", title: "Count what actually goes on the wire", story: "Botie sees one character, é, but UTF-8 stores it in two bytes. A character count and a byte count answer different questions. Let us inspect the encoding instead of assuming they agree.", task: "Choose UTF-8 bytes to encode the displayed character.", controls: [choose("unit", "Encode as", ["Unicode code points", "UTF-8 bytes"])], initial: { unit: "Unicode code points" }, solution: { unit: "UTF-8 bytes" }, hint: "The UTF-8 bytes for é are 195 and 169. The Unicode code point is 233; it is not a UTF-8 byte sequence by itself.", success: "The bytes reconstruct the same character under UTF-8. Even counting Unicode code points is not always the same as counting the visible characters a reader perceives.", rule: "character → UTF-8 encoding → byte sequence", run: (v, b) => { const text = b ? "猫" : "é", bytes = Array.from(new TextEncoder().encode(text)); return { readings: [row("Encoded units", text, str(v, "unit") === "UTF-8 bytes" ? bytes : Array.from(text).map(c => c.codePointAt(0)!), bytes)], scene: { kind: "tokens", input: text, pieces: (str(v, "unit") === "UTF-8 bytes" ? bytes : Array.from(text).map(c => c.codePointAt(0)!)).map(String) } }; },
  },
  {
    id: "splitting-on-spaces", title: "What happens to two spaces?", story: "Botie's message contains a repeated space. Splitting on a literal space and splitting on runs of whitespace are different operations. One can leave an empty piece between the separators.", task: "Extract just the words, treating a run of whitespace as one separator.", controls: [choose("split", "Splitting rule", ["One literal space", "Runs of whitespace"])], initial: { split: "One literal space" }, solution: { split: "Runs of whitespace" }, hint: "Use a rule that consumes the whole separator run. In this exercise we discard separators rather than preserving exact spacing.", success: "We recovered the words but lost the original spacing. That may be fine for some tasks, but it does not permit an exact text round trip.", rule: "split on one or more whitespace characters; discard the separators", run: (v, b) => { const text = b ? "red\tblue  green" : "cat  dog"; const pieces = str(v, "split") === "Runs of whitespace" ? text.split(/\s+/) : text.split(" "); return { readings: [row("Words", JSON.stringify(text), pieces, text.split(/\s+/))], scene: { kind: "tokens", input: text, pieces } }; },
  },
  boundaries("unicode-word-boundaries", "Notice the punctuation in another script", "Botie receives Chinese text separated by a full-width comma. An ASCII-only idea of punctuation can miss it. Unicode-aware processing recognises that punctuation exists beyond the familiar English symbols.", "猫，狗", ["猫", "，", "狗"], "Separate the two animal characters and retain the full-width comma as its own piece.", "The middle character is punctuation, even though it is not the ASCII comma.", "This punctuation boundary is clear. Unicode boundary rules do not by themselves solve linguistic word segmentation for every script."),
  boundaries("penn-treebank-rules", "Keep the contraction convention straight", "A tokenizer's conventions determine what counts as a piece. The Penn Treebank convention separates this English contraction into a stem fragment and a negation fragment. The pieces are a convention, not a claim about visible spaces.", "can't", ["ca", "n't"], "Apply the Treebank-style split into ca and n't.", "Place the boundary after the a. The n belongs with the apostrophe and t.", "The fragments reconstruct the contraction. A different tokenizer can use different pieces, so data and downstream models need compatible conventions."),
  boundaries("moses-rules", "Separate the punctuation before translation", "Botie's translation pipeline should not need a separate vocabulary entry for red followed by a comma. Separating punctuation lets the word appear in several contexts without treating every spelling-plus-punctuation combination as new.", "red,blue", ["red", ",", "blue"], "Separate the comma from both neighbouring words, retaining it as a token.", "Place one boundary before the comma and one after it.", "This demonstrates punctuation separation used in Moses-style processing. The full tokenizer also has language-specific rules and escaping conventions."),
  boundaries("the-pattern-language-models-use", "Keep the word, number and punctuation apart", "Before subword merges, a pattern can divide text into manageable regions. In the convention used here, a leading space stays with a word, while digits and punctuation form separate runs.", " hello42!", [" hello", "42", "!"], "Keep the leading space with hello, the two digits together, and the exclamation mark separate.", "Do not cut after the first space. The boundaries belong after the o and after the 2.", "These are pre-tokenization regions. A later subword algorithm can divide each region further; this pattern is not shared by every language model."),
  boundaries("maximum-matching", "Try the longest piece first", "Botie's dictionary contains the, therapist, rap and ist. Maximum matching starts at the current position and takes the longest dictionary item that fits. It does not compare complete sentence interpretations.", "therapist", ["therapist"], "Use the longest matching dictionary entry at the start of the word.", "The entire input is in the dictionary. Remove the shorter internal cuts.", "The longest match wins here. Greedy choices can be wrong when the intended segmentation requires considering later context."),
  boundaries("the-word-lattice", "Find the cheaper complete route", "There are two routes through Botie's tiny vocabulary: ab followed by cd costs 3 in total; a followed by bcd costs 5. A word lattice keeps alternatives until we compare complete paths.", "abcd", ["ab", "cd"], "Choose the complete segmentation with the smaller supplied cost. Costs: ab 1, cd 2, a 1, bcd 4.", "Add costs across each whole route. A cheap first piece does not guarantee a cheap path.", "The winning route accounts for the whole input. Dynamic programming can find such a path without enumerating every full segmentation."),
  boundaries("segmenting-with-a-hidden-model", "Recover the boundaries behind the characters", "Botie's hidden-state model assigns the states B, E, S to these three characters. B begins a multi-character word, E ends it, and S is a single-character word. The states tell us where the boundaries belong.", "机器人", ["机器", "人"], "Decode the supplied state path B, E, S into word pieces.", "Keep B with the E that closes it. The final S is a word on its own.", "You decoded one state path. A hidden Markov model uses transition and emission probabilities to choose that path, commonly through the Viterbi algorithm."),
  boundaries("learning-boundaries-from-examples", "Turn boundary labels into pieces", "Botie has a supervised boundary detector. For this small example, its labels say not to split after the first character and to split after the second. Training such a detector requires examples with known boundaries.", "南京市", ["南京", "市"], "Apply the supplied after-character labels: no boundary, boundary, end.", "The first two characters stay together. The boundary comes before the last character.", "The labels directly determine these pieces. Whether a trained detector supplies good labels depends on its training examples and the segmentation convention."),
  {
    id: "n-grams", title: "Let Botie see adjacent pairs", story: "One token at a time loses local order. An n-gram keeps a short consecutive window, so cat sat differs from sat cat. Sliding the window gives us overlapping pieces of context.", task: "Set the window size to collect bigrams, including overlapping pairs.", controls: [dial("n", "Tokens per window", 1, 3)], initial: { n: 1 }, solution: { n: 2 }, hint: "Bi means two. Move one token at a time, not two.", success: "The middle token appears in two windows. These local patterns preserve some order without representing an entire sentence.", rule: "window_i = tokens[i : i + n]", run: (v, b) => { const xs = b ? ["the", "dog", "ran", "home"] : ["the", "cat", "sat"]; const grams = (n: number) => xs.slice(0, xs.length - n + 1).map((_, i) => xs.slice(i, i + n).join(" ")); return { readings: [row("Windows", xs.join(" "), grams(num(v, "n")), grams(2))], scene: { kind: "tokens", input: xs.join(" "), pieces: grams(num(v, "n")) } }; },
  },
  boundaries("byte-pair-encoding", "Apply the merge the vocabulary learned", "Botie begins with l, o, w, e, r. The supplied merge table first combines l with o and then lo with w. Applying those learned merges creates a reusable low piece.", "lower", ["low", "e", "r"], "Build the pieces after these two merges only: l+o, then lo+w.", "Remove the boundaries within low. Keep the boundaries before e and r because no merge for them was supplied.", "BPE applies learned merge rules in their order. This replay does not train the merge table, and frequent pieces need not coincide with word meanings."),
  boundaries("wordpiece", "Use a continuation piece", "Botie's WordPiece vocabulary contains play and the continuation entry ##ing. The prefix markers describe where a piece may occur; they are not characters in the original word.", "playing", ["play", "ing"], "Split the word using play followed by the continuation piece ##ing. The preview shows the original characters without the ## notation.", "The continuation begins after the y.", "The two vocabulary entries cover the word. The ## prefix distinguishes a continuation entry from an entry that can start a word."),
  boundaries("the-unigram-language-model", "Compare complete subword paths", "Botie can encode abcd as ab+cd or a+bcd. A unigram tokenizer can score the complete paths using piece probabilities. Here the probabilities are ab 0.4, cd 0.3, a 0.1 and bcd 0.2.", "abcd", ["ab", "cd"], "Choose the path with the larger product of the supplied piece probabilities.", "The products are 0.12 for ab+cd and 0.02 for a+bcd. Keep the first path.", "The complete-path score chooses these pieces. Actual unigram tokenizers learn a vocabulary and probabilities and may also sample alternative segmentations."),
  boundaries("sentencepiece", "Make the space visible", "Botie must preserve the boundary represented by a space even while learning subword pieces. SentencePiece commonly represents spaces with the visible marker ▁. Here the string has already been normalised into that form.", "▁red▁cat", ["▁red", "▁cat"], "Keep each space marker with the word that follows it.", "The only internal cut should come just before the second ▁ marker.", "The markers keep spacing information in the piece stream. Normalisation rules still matter when deciding whether the exact original text can be recovered."),
  boundaries("greedy-coverage", "Spend a piece on the longest match", "Botie must cover the complete string using a fixed vocabulary: abc, ab, cd and d. The greedy rule takes the longest valid piece at the current position, then continues from its end.", "abcd", ["abc", "d"], "Apply longest-first greedy coverage using the supplied vocabulary.", "abc is longer than ab. After consuming it, only d remains.", "The greedy rule covers the input here. It need not find the lowest-cost segmentation when pieces have different costs."),
  sequence("moving-a-vocabulary", "Keep the IDs and embeddings together", "Botie is moving a tokenizer vocabulary to another model. If an ID changes but its embedding row does not move with it, the model can silently read the wrong representation.", "Arrange the migration so token identity remains attached to the correct embedding row.", ["Read the old token-to-ID mapping", "Build the new token-to-ID mapping", "Match old and new entries by token identity", "Copy matching embedding rows and initialise new entries", "Test encoding and embedding lookup together"], "Match by token identity, not by an assumption that the row number still means the same thing.", "The mapping and embedding table must agree. Special tokens and model-specific tokenizer rules need explicit checks too."),
  boundaries("morfessor", "Look for reusable word parts", "Botie sees walk, walked and walking repeatedly. Reusing a walk piece can describe those words more economically than storing each word as unrelated. A morphological segmenter balances reusable pieces against the complexity of its vocabulary.", "walking", ["walk", "ing"], "Show the reusable stem and suffix in this supplied morphological analysis.", "Keep walk together and put the boundary before ing.", "This segmentation exposes a reusable pattern. Morfessor learns a statistical analysis and does not guarantee agreement with every linguistic interpretation."),
  {
    id: "finite-state-morphology", title: "Turn an analysis into a surface word", story: "Botie has the analysis city plus plural. Simply adding s would produce citys. A finite-state morphology system can combine lexical information with spelling rules to produce the surface form.", task: "Apply the consonant-plus-y plural rule to these supplied stems.", controls: [choose("rule", "Plural rule", ["Append s", "Replace final y with ies"])], initial: { rule: "Append s" }, solution: { rule: "Replace final y with ies" }, hint: "All the stems in this batch end in a consonant followed by y. Replace that y before adding the plural ending.", success: "The rule maps these analyses to the correct forms. A complete morphology system needs lexical entries, exceptions and rules for other endings.", rule: "consonant + y + plural → consonant + ies", run: (v, b) => ({ readings: (b ? ["puppy", "story"] : ["city", "party"]).map(w => row(w, "Stem + plural", str(v, "rule") === "Append s" ? w + "s" : w.slice(0, -1) + "ies", w.slice(0, -1) + "ies")) }),
  },
  {
    id: "hashing-characters", title: "Fit characters into a small table", story: "Botie only has four storage buckets. A hash maps character features into that fixed space without storing a complete vocabulary. Different features can collide in the same bucket.", task: "Use modulo 4 to assign the supplied character codes to the four available buckets.", controls: [dial("buckets", "Number of buckets", 2, 8)], initial: { buckets: 3 }, solution: { buckets: 4 }, hint: "The remainder must be one of 0, 1, 2 or 3. Notice that a and e land together.", success: "The fixed table covers every input but loses identity at collisions. Real feature hashing uses a hash function over features rather than this tiny code-point demonstration.", rule: "toy bucket = character code mod number of buckets", run: (v, b) => ({ readings: (b ? ["b", "f", "g"] : ["a", "e", "c"]).map(c => row(c, `Character code ${c.charCodeAt(0)}`, c.charCodeAt(0) % num(v, "buckets"), c.charCodeAt(0) % 4)) }),
  },
  {
    id: "patching-without-a-vocabulary", title: "Group the bytes before processing", story: "Botie can read bytes without a learned word vocabulary, but a long byte stream creates a lot of work. Grouping neighbouring bytes into patches reduces the number of positions processed later.", task: "Group this eight-byte ASCII input into four patches of two bytes each.", controls: [dial("width", "Bytes per patch", 1, 4)], initial: { width: 1 }, solution: { width: 2 }, hint: "Move two bytes at a time. Keep each byte in exactly one patch.", success: "The patches cover the byte stream without a word vocabulary. This fixed-width toy isolates grouping; learned or adaptive patch boundaries can follow different rules.", rule: "patch_i = next fixed-width group of bytes", run: (v, b) => { const text = b ? "redboxes" : "bluecats", bytes = Array.from(new TextEncoder().encode(text)); const chunks = (w: number) => Array.from({ length: Math.ceil(bytes.length / w) }, (_, i) => bytes.slice(i * w, (i + 1) * w).join(" ")); return { readings: [row("Byte patches", text, chunks(num(v, "width")), chunks(2))], scene: { kind: "tokens", input: text, pieces: chunks(num(v, "width")) } }; },
  },
  {
    id: "codebook-quantisation", title: "Pick the nearest stored prototype", story: "Botie has a continuous two-number representation but can transmit only a codebook ID. Vector quantisation replaces the vector with the nearest stored prototype, trading precision for a compact code.", task: "Encode [0.9, 1.1] using the closest prototype.", controls: [choose("code", "Codebook entry", ["0: [0, 0]", "1: [1, 1]", "2: [2, 0]"])], initial: { code: "0: [0, 0]" }, solution: { code: "1: [1, 1]" }, hint: "Compare both coordinates. Entry 1 is only 0.1 away in each direction.", success: "The ID identifies the nearest prototype, and decoding reconstructs that prototype rather than the exact input. The difference is quantisation error.", rule: "code = argmin_j ||input − codebook_j||²", run: (v, b) => { const x = b ? [1.1, .9] : [.9, 1.1], code = Number(str(v, "code")[0]), p = [[0, 0], [1, 1], [2, 0]][code]; return { readings: [row("Codebook ID", `Input [${x}]`, code, 1), row("Squared reconstruction error", `Prototype [${p}]`, p.reduce((s, y, i) => s + (y - x[i]) ** 2, 0), .02)] }; },
  },
  {
    id: "finite-scalar-quantisation", title: "Snap each coordinate to a level", story: "Botie can quantise coordinates independently instead of searching a learned vector codebook. Each coordinate snaps to one of a fixed set of levels, and their combination identifies a discrete representation.", task: "Round each value to its nearest level from -1, 0 and 1. The supplied values are already inside this range.", controls: [choose("rule", "Scalar rounding", ["Floor", "Nearest", "Ceiling"])], initial: { rule: "Floor" }, solution: { rule: "Nearest" }, hint: "Values above 0.5 are nearer 1 than 0. Values close to zero should remain at zero.", success: "The fixed levels define the possible coordinate combinations. Full finite scalar quantisation also bounds continuous inputs before rounding.", rule: "quantised coordinate = nearest allowed scalar level", run: (v, b) => ({ readings: (b ? [-.8, -.1, .7] : [-.7, .2, .8]).map(x => row(`Value ${x}`, "Levels: -1, 0, 1", str(v, "rule") === "Floor" ? Math.floor(x) : str(v, "rule") === "Ceiling" ? Math.ceil(x) : Math.round(x), Math.round(x))) }),
  },
];
