import { type Mission, dial, choose, num, str, list, row, mean, dot, softmax, sequence } from "./types";

export const models: Mission[] = [
  {
    id: "distance-metrics", title: "Give Botie a map he can use", story: "Botie can travel along the workshop aisles, but he cannot drive diagonally through a shelf. A straight-line distance underestimates the journey. What do we need to count instead?", task: "Choose a distance rule that counts horizontal and vertical travel.", controls: [choose("metric", "Distance rule", ["Euclidean", "Manhattan", "Chebyshev"])], initial: { metric: "Euclidean" }, solution: { metric: "Manhattan" }, hint: "Count the horizontal steps, then add the vertical steps.", success: "Manhattan distance matches movement along these aisles. A distance rule is a choice about which differences matter, not a universal definition of similarity.", rule: "aisle distance = |horizontal change| + |vertical change|", run: (v, b) => ({ readings: (b ? [[2, 3], [1, 4], [-2, 2]] : [[3, 4], [2, 2], [4, 1]]).map(([x, y], i) => row(`Delivery ${i + 1}`, `Offset [${x}, ${y}]`, str(v, "metric") === "Euclidean" ? Math.hypot(x, y) : str(v, "metric") === "Manhattan" ? Math.abs(x) + Math.abs(y) : Math.max(Math.abs(x), Math.abs(y)), Math.abs(x) + Math.abs(y))) }),
  },
  {
    id: "multiple-polynomial-regression", title: "Price a panel and its frame", story: "The workshop pays for both the panel's area and the length of its frame. Botie cannot explain the price using only the side length. We need two features, with a separate contribution from each.", task: "The panel costs 2 per square unit and its frame costs 1 per unit of perimeter. Set the two coefficients.", controls: [dial("area", "Area coefficient", 0, 4, .5), dial("edge", "Perimeter coefficient", 0, 4, .5)], initial: { area: 1, edge: 0 }, solution: { area: 2, edge: 1 }, hint: "Calculate area and perimeter first. The coefficients express the price of one unit of each.", success: "The rule combines two features. It is quadratic in side length but linear in the coefficients we set.", rule: "price = area coefficient × side² + perimeter coefficient × 4 × side", run: (v, b) => ({ readings: (b ? [1.5, 2.5, 4] : [1, 2, 3]).map(s => row(`Side ${s}`, `Area ${s * s}; perimeter ${4 * s}`, num(v, "area") * s * s + num(v, "edge") * 4 * s, 2 * s * s + 4 * s)) }),
  },
  ...(["gradient-descent-regression", "gradient-boosting"] as const).map(id => {
    const boosting = id === "gradient-boosting";
    return { id, title: boosting ? "Repair what the first model missed" : "Take a useful step downhill", story: boosting ? "Botie's first model underestimates each delivery. Instead of replacing it, we can add another model that predicts the errors left behind. Here the small correction model has already been fitted." : "Botie has a parameter whose error is a bowl. The gradient points uphill. Subtracting a fraction of it should move the parameter toward the bottom, but an oversized step can pass straight over it.", task: boosting ? "Choose the fraction of the fitted residual to add so this noiseless batch is corrected exactly." : "Set the learning rate so one gradient step reaches the minimum of this particular quadratic.", controls: [dial("rate", boosting ? "Correction multiplier" : "Learning rate", 0, 1.5, .1)], initial: { rate: 0 }, solution: { rate: boosting ? 1 : .5 }, hint: boosting ? "The correction is already the full remaining error. A multiplier of one adds all of it." : "For this quadratic the gradient is twice the distance from the minimum. Take half of that gradient.", success: boosting ? "The second model adds a correction to the first. Real boosting usually uses smaller contributions and many stages; correcting training errors exactly can overfit." : "This rate lands at the minimum for this bowl. It is not a generally correct learning rate; different curvature changes the step we need.", rule: boosting ? "new prediction = old prediction + multiplier × fitted residual" : "gradient = 2 × (parameter − target)\nnew parameter = parameter − rate × gradient", run: (v, b) => ({ readings: (b ? [1, 5, 8] : [0, 4, 6]).map((x, i) => row(`Case ${i + 1}`, `Start ${x}; target 3`, boosting ? x + num(v, "rate") * (3 - x) : x - num(v, "rate") * 2 * (x - 3), 3)) }) } satisfies Mission;
  }),
  {
    id: "ridge-lasso", title: "Which coefficient can disappear?", story: "Botie's fitted model has one large coefficient and one small one. A penalty can shrink both, but lasso can also make a small coefficient exactly zero. Let us isolate that difference with independent, unit-scaled features.", task: "Use lasso with a penalty of 1 to remove the smaller coefficient and shrink the larger one.", controls: [choose("penalty", "Penalty", ["Ridge", "Lasso"]), dial("amount", "Penalty strength", 0, 3, .5)], initial: { penalty: "Ridge", amount: 1 }, solution: { penalty: "Lasso", amount: 1 }, hint: "In this simplified orthonormal example, lasso subtracts the penalty from a coefficient's magnitude and stops at zero.", success: "The small coefficient is now zero. This soft-threshold formula depends on the simplified feature geometry and loss convention used here.", rule: "Toy objective: ½ ||w − c||² + penalty\nridge: w = c / (1 + λ)\nlasso: w = sign(c) × max(|c| − λ, 0)", run: (v, b) => ({ readings: (b ? [3, -.5] : [2, .5]).map((c, i) => row(`Coefficient ${i + 1}`, `Unpenalised value ${c}`, str(v, "penalty") === "Ridge" ? c / (1 + num(v, "amount")) : Math.sign(c) * Math.max(Math.abs(c) - num(v, "amount"), 0), Math.sign(c) * Math.max(Math.abs(c) - 1, 0))) }),
  },
  {
    id: "k-nearest-neighbours", title: "Ask a few neighbours", story: "The nearest labelled parcel has the wrong label. The next two agree with one another. Botie can ask more than one neighbour, but the size of that neighbourhood changes whose opinions count.", task: "Use the three nearest labels to predict the majority class.", controls: [dial("k", "Number of neighbours", 1, 5, 2)], initial: { k: 1 }, solution: { k: 3 }, hint: "The labels are listed from nearest to furthest. Count the first three.", success: "The majority changed when we included more neighbours. Three is useful for this batch; choosing k generally requires evaluation on separate examples.", rule: "prediction = majority label among the k nearest examples", run: (v, b) => ({ readings: (b ? [[1, 0, 0, 1, 1], [0, 1, 1, 0, 0]] : [[0, 1, 1, 0, 0], [1, 0, 0, 1, 1]]).map((labels, i) => row(`Query ${i + 1}`, `Nearest first: ${labels}`, +(mean(labels.slice(0, num(v, "k"))) >= .5), labels[1])) }),
  },
  {
    id: "decision-trees", title: "Ask one useful question", story: "Botie can separate these parcels with a single question about height. The answer sends a parcel to one of two leaves. A tree grows by looking for questions that make its groups more consistent.", task: "Find a height threshold that separates the labelled parcels. Send heights above the threshold to the tall-parcel shelf.", controls: [dial("threshold", "Height threshold", 0, 6, .5)], initial: { threshold: 1 }, solution: { threshold: 3 }, hint: "Look for the gap between the tallest short parcel and the shortest tall parcel.", success: "One split separates this batch. More complex patterns need further questions; an unrestricted tree can eventually memorise the training examples.", rule: "tall-parcel shelf when height > threshold", run: (v, b) => ({ readings: (b ? [1.5, 2.9, 3.1, 5.5] : [1, 2.5, 3.5, 5]).map(x => row(`Height ${x}`, "Labelled by the workshop", +(x > num(v, "threshold")), +(x > 3))) }),
  },
  {
    id: "multiclass-classification", title: "Give three shelves a share", story: "Botie has a score for each of three shelves. Scores can be negative and need not add up to anything useful. Softmax converts them into nonnegative shares that sum to one, while keeping their ordering.", task: "Choose the operation that produces the requested probability distribution.", controls: [choose("operation", "Convert scores using", ["Divide by their sum", "Softmax", "Keep the scores"])], initial: { operation: "Keep the scores" }, solution: { operation: "Softmax" }, hint: "Exponentiate the scores, then divide each result by the sum of those exponentials.", success: "The largest score has the largest probability, and all three probabilities sum to one. That does not by itself mean the probabilities are well calibrated.", rule: "probability_i = exp(score_i) / sum(exp(scores))", run: (v, b) => { const scores = b ? [-1, 0, 2] : [-2, 1, 3]; const actual = str(v, "operation") === "Softmax" ? softmax(scores) : str(v, "operation") === "Keep the scores" ? scores : scores.map(x => x / scores.reduce((s, y) => s + y, 0)); return { readings: actual.map((x, i) => row(`Shelf ${i + 1}`, `Scores: [${scores}]`, x, softmax(scores)[i])) }; },
  },
  {
    id: "bagging", title: "Let the estimators share the load", story: "Three models trained on different resamples disagree about a parcel. Botie can average their numerical predictions. This reduces the influence of a single model's peculiar fit, especially when their errors differ.", task: "Combine all three regression predictions with equal weights.", controls: [dial("a", "First model weight", 0, 3), dial("b", "Second model weight", 0, 3), dial("c", "Third model weight", 0, 3)], initial: { a: 1, b: 0, c: 0 }, solution: { a: 1, b: 1, c: 1 }, hint: "The controls are normalised by their total. Give every model the same nonzero weight.", success: "The ensemble uses every model equally. This is aggregation; the different bootstrap training samples are what make the models a bagged ensemble.", rule: "combined prediction = weighted sum / sum of weights", run: (v, b) => { const w = [num(v, "a"), num(v, "b"), num(v, "c")]; return { readings: (b ? [[3, 6, 9], [8, 2, 5]] : [[2, 4, 9], [7, 1, 4]]).map((x, i) => row(`Parcel ${i + 1}`, `Predictions: ${x}`, dot(x, w) / w.reduce((s, x) => s + x, 0), mean(x))) }; },
  },
  sequence("random-forests", "Grow trees with different views", "If every tree sees the same examples and always picks the same dominant feature, the trees can make the same mistakes. Botie needs a reason for the trees to disagree before their votes can help.", "Arrange the training process for this random forest. Feature sampling happens again at each split.", ["Draw a bootstrap sample for each tree", "At a node, sample candidate features", "Choose a split from those candidates", "Repeat at child nodes until stopping", "Combine the fitted trees' predictions"], "The bootstrap sample comes before growing a tree. Sampling candidate features belongs inside the split-building process.", "The forest combines bootstrap sampling with random feature choices. Those choices reduce dependence between the trees, though they cannot guarantee independent errors."),
  {
    id: "k-means", title: "Move the collection points", story: "Botie has two clusters of parcels on a straight aisle. He needs a collection point for each group. Moving each centre to its assigned group's mean is the update used by k-means.", task: "Place the centres at the means of the left and right groups.", controls: [dial("left", "Left centre", 0, 5, .5), dial("right", "Right centre", 5, 10, .5)], initial: { left: 0, right: 10 }, solution: { left: 2, right: 8 }, hint: "The left group balances at 2 and the right group balances at 8. Check the sums rather than choosing an outermost point.", success: "These centres are stable for this assignment. K-means alternates assignment and centre updates; its result can depend on the starting centres.", rule: "new centre = mean of the points assigned to it", run: (v, b) => { const xs = b ? [1.5, 2, 2.5, 7.5, 8, 8.5] : [1, 2, 3, 7, 8, 9]; return { readings: [row("Left centre", `Assigned: ${xs.slice(0, 3)}`, num(v, "left"), mean(xs.slice(0, 3))), row("Right centre", `Assigned: ${xs.slice(3)}`, num(v, "right"), mean(xs.slice(3)))], scene: { kind: "plot", x: "Aisle position", y: "Group", points: xs.map(x => [x, 0, +(x > 5)]), line: [[num(v, "left"), .5], [num(v, "right"), .5]] } }; },
  },
  {
    id: "kernel-trick", title: "Give the gate a different view", story: "Botie's special parcels form a ring around the ordinary ones. A straight boundary in the original coordinates cannot enclose that ring. A new coordinate, squared distance from the centre, puts inner and outer parcels at different heights.", task: "Use squared distance as the feature, then put the dividing plane between the inner and outer parcels.", controls: [choose("feature", "Feature shown to the gate", ["Horizontal position", "Squared distance"]), dial("cut", "Threshold", 0, 5, .5)], initial: { feature: "Horizontal position", cut: 2 }, solution: { feature: "Squared distance", cut: 2 }, hint: "Squaring and adding the two coordinates gives the same value on a circle, regardless of direction.", success: "The transformed feature makes one threshold sufficient. This is an explicit feature map; the kernel trick goes further by computing feature-space comparisons without constructing every transformed coordinate.", rule: "new feature = x² + y²\nouter shelf when new feature > threshold", run: (v, b) => { const pts = b ? [[.5, .5], [-.5, -.5], [1.5, 1.5], [-1.5, -1.5]] : [[0, 1], [0, -1], [2, 0], [-2, 0]]; return { readings: pts.map(([x, y], i) => row(`Parcel ${i + 1}`, `Position [${x}, ${y}]`, +((str(v, "feature") === "Squared distance" ? x * x + y * y : x) > num(v, "cut")), +(x * x + y * y > 2))), scene: { kind: "plot", x: "x", y: "y", points: pts.map(([x, y]) => [x, y, +(x * x + y * y > 2)]) } }; },
  },
  {
    id: "kernel-ridge", title: "Keep a kernel fit from shouting", story: "In this deliberately simple kernel matrix, the training examples are independent: the matrix is the identity. Botie can see the effect of ridge regularisation without first solving a large system.", task: "Use a ridge penalty of 1, which halves the fitted coefficients for this identity kernel.", controls: [dial("lambda", "Ridge penalty", 0, 4, .5)], initial: { lambda: 0 }, solution: { lambda: 1 }, hint: "Adding the penalty to the diagonal makes each diagonal entry 2. Solve each independent equation by dividing by 2.", success: "The coefficients shrink because we solved the regularised system. With a general kernel matrix the examples interact, so this elementwise division would no longer work.", rule: "(K + λI)α = y\nfor K = I: α_i = y_i / (1 + λ)", run: (v, b) => ({ readings: (b ? [3, -1, 5] : [2, 4, -2]).map((y, i) => row(`Coefficient ${i + 1}`, `Target ${y}`, y / (1 + num(v, "lambda")), y / 2)) }),
  },
  {
    id: "kernel-pca", title: "Centre the comparisons", story: "PCA describes variation around a centre. Botie has only pairwise kernel comparisons, so he cannot simply subtract a mean from visible coordinates. He can still centre the kernel matrix using its row, column and overall means.", task: "Enable both mean subtractions and restore the overall mean once.", controls: [{ kind: "select", key: "terms", label: "Terms in the centred kernel", items: ["Subtract row mean", "Subtract column mean", "Add overall mean"] }], initial: { terms: ["Subtract row mean"] }, solution: { terms: ["Subtract row mean", "Subtract column mean", "Add overall mean"] }, hint: "Subtracting both means removes the overall mean twice. Add it back once.", success: "Every row and column now sums to zero, as centring requires. Kernel PCA then finds directions through an eigendecomposition of this centred matrix.", rule: "centred K_ij = K_ij − row mean_i − column mean_j + overall mean", run: (v, b) => { const x = b ? [1, 3] : [1, 2], K = x.map(a => x.map(c => a * c)), terms = list(v, "terms"), overall = mean(K.flat()), centred = K.map((r) => r.map((a, j) => a - (terms.includes("Subtract row mean") ? mean(r) : 0) - (terms.includes("Subtract column mean") ? mean(K.map(t => t[j])) : 0) + (terms.includes("Add overall mean") ? overall : 0))); return { readings: centred.map((r, i) => row(`Centred row ${i + 1}`, `Original row: ${K[i]}`, r, x.map(value => (x[i] - mean(x)) * (value - mean(x))))), scene: { kind: "pixels", panels: [{ label: "Original kernel", cells: K }, { label: "Your centred kernel", cells: centred }] } }; },
  },
  {
    id: "markov-chains", title: "Predict the next workshop state", story: "Botie's workshop is either running or being repaired. The next-state probabilities depend only on the current state in this model. To predict tomorrow's mix, combine the transitions from both states.", task: "Set the chance of staying in each state from the maintenance log: 0.8 for running, 0.4 for repair.", controls: [dial("running", "Running stays running", 0, 1, .1), dial("repair", "Repair stays repair", 0, 1, .1)], initial: { running: .5, repair: .5 }, solution: { running: .8, repair: .4 }, hint: "Each row of a transition matrix sums to one. The chance of switching is one minus the chance of staying.", success: "The state distribution moved through the transition matrix. This is a Markov assumption, not a claim that real maintenance history never matters.", rule: "next running = current running × P(run→run) + current repair × P(repair→run)", run: (v, b) => ({ readings: (b ? [.25, .75] : [0, 1, .5]).map(p => row(`Running fraction ${p}`, `Repair fraction ${1 - p}`, p * num(v, "running") + (1 - p) * (1 - num(v, "repair")), p * .8 + (1 - p) * .6)) }),
  },
  sequence("pipelines", "Keep the test data out of the workshop", "Botie wants to scale the measurements before fitting. If he learns the scaler from all the parcels, information from the test set slips into training before the model even starts.", "Arrange the steps so both the scaler and the model learn from training data alone.", ["Split training and test examples", "Fit the scaler on training examples", "Transform training examples and fit the model", "Transform test examples with the fitted scaler", "Evaluate predictions on test examples"], "The split must happen before anything learns a mean, scale or model parameter.", "The test examples only pass through fitted operations. Cross-validation must repeat the fitting steps separately inside each fold."),
  sequence("grid-search", "Choose a setting without peeking", "Botie has several candidate settings. Trying each on the final test set would turn that test into another training decision. We need a separate comparison procedure.", "Build a search that leaves the final test untouched until selection is finished.", ["Reserve the final test set", "Make validation folds from the remaining data", "Fit each candidate within each training fold", "Compare mean validation scores", "Refit the chosen setting, then evaluate on the final test"], "Validation chooses the setting. The final test estimates the result of that whole choice.", "The best validation setting still needs an independent test. It is not guaranteed to be the best setting on every future sample."),
  {
    id: "feature-importance", title: "Disconnect one sensor at a time", story: "Botie's fitted rule predicts twice the height and ignores colour. To see which sensor the prediction relies on, shuffle one sensor across parcels and measure the damage without refitting.", task: "Shuffle the feature that increases the fitted model's error.", controls: [choose("sensor", "Shuffle this sensor", ["Colour", "Height"])], initial: { sensor: "Colour" }, solution: { sensor: "Height" }, hint: "Which measurement actually appears in the fitted rule? Changing an unused feature cannot change its prediction.", success: "Shuffling height damages this model's predictions. Permutation importance describes the fitted model on this dataset; correlated features can complicate the interpretation.", rule: "prediction = 2 × height\nimportance = error after shuffling − original error", run: (v, b) => { const h = b ? [2, 4, 6] : [1, 2, 3]; const shuffled = [h[2], h[0], h[1]]; const damage = mean(h.map((x, i) => (2 * shuffled[i] - 2 * x) ** 2)); return { readings: [row("Increase in mean squared error", `Original heights: ${h}; shuffled heights: ${shuffled}`, str(v, "sensor") === "Height" ? damage : 0, damage)] }; },
  },
];
