import { type Mission, dial, choose, num, str, list, row, softmax, sequence } from "./types";

export const modern: Mission[] = [
  sequence("transformer-blocks", "Give attention a place in the block", "Botie can exchange information between tokens with attention, but a transformer block also needs a per-token transformation and routes that preserve the incoming representation. Here we assemble a pre-normalisation block.", "Arrange this particular pre-norm transformer block. Other layouts exist, so follow the one stated here.", ["Normalise the incoming token states", "Apply self-attention", "Add the original token states through a residual connection", "Normalise that combined result", "Apply the feed-forward network and add its residual input"], "Each sublayer receives a normalised input, and each residual route adds the representation from before that sublayer.", "Attention mixes information between positions; the feed-forward network transforms each position. The residual connections keep identity routes through both sublayers."),
  {
    id: "next-token-prediction", title: "Do not let tomorrow give away the answer", story: "Botie is predicting the next token at each position in a sequence. If a position can read a later token, it can see information it will not have during generation. A causal mask prevents that shortcut.", task: "At position 2, allow attention to positions 0, 1 and 2, but not 3. Positions count from zero.", controls: [{ kind: "select", key: "positions", label: "Visible positions", items: ["0: the", "1: cat", "2: sat", "3: down"] }], initial: { positions: ["0: the", "1: cat", "2: sat", "3: down"] }, solution: { positions: ["0: the", "1: cat", "2: sat"] }, hint: "The current token is already known. The next token is the target and must remain hidden from this position.", success: "The mask keeps the prediction causal. Training can still calculate many positions in parallel because each position has its own visibility mask.", rule: "position i may attend to position j only when j ≤ i", run: v => ({ readings: [0, 1, 2, 3].map(i => row(`Position ${i}`, "Visibility while predicting after position 2", +list(v, "positions").some(x => x.startsWith(`${i}:`)), +(i <= 2))), scene: { kind: "tokens", input: "the cat sat → predict down", pieces: ["0: the", "1: cat", "2: sat", "3: down"].map(p => list(v, "positions").includes(p) ? p : "hidden") } }),
  },
  sequence("autoregressive-generation", "Return the prediction to the input", "Botie's model produces a distribution for one next token. To produce a sentence, we choose a token, append it to the context and run the model again. The new token changes the next prediction.", "Arrange one turn of the generation loop.", ["Read the current context", "Compute next-token probabilities", "Choose a token with the sampling rule", "Append the chosen token to the context", "Check the stopping condition before repeating"], "The sampled token must become part of the context before predicting another one.", "The loop grows a sequence one token at a time. Its weights stay fixed during ordinary generation; the changing context drives the changing predictions."),
  {
    id: "sampling-and-temperature", title: "Give the unlikely token a chance", story: "Botie's model has fixed next-token scores. Temperature changes how sharply those scores are converted into probabilities. It changes sampling behaviour without retraining the model.", task: "Set temperature to 2 to match the warmer target distribution. Inspect how the highest and lowest probabilities change.", controls: [dial("temperature", "Temperature", .5, 3, .5)], initial: { temperature: .5 }, solution: { temperature: 2 }, hint: "Divide each logit by the temperature before softmax. A higher positive temperature makes the distribution flatter.", success: "The lower-scoring token now has more probability. These are distribution calculations; we are not claiming that a single random draw must choose a different token.", rule: "sampling probabilities = softmax(logits / temperature)", run: (v, b) => { const logits = b ? [3, 1, -1] : [2, 1, 0], p = softmax(logits.map(x => x / num(v, "temperature"))), target = softmax(logits.map(x => x / 2)); return { readings: p.map((x, i) => row(`Token ${i + 1}`, `Logit ${logits[i]}`, x, target[i])) }; },
  },
  {
    id: "autoencoders", title: "Pack only what the decoder needs", story: "Botie's inputs all lie on the diagonal: the second coordinate equals the first. A single number can represent each point if the decoder knows how to restore both coordinates. That is a tiny example of compression through a bottleneck.", task: "The encoder keeps the first coordinate. Set both decoder weights to reconstruct the original pair.", controls: [dial("a", "First decoded coordinate weight", 0, 2, .5), dial("b", "Second decoded coordinate weight", 0, 2, .5)], initial: { a: 1, b: 0 }, solution: { a: 1, b: 1 }, hint: "Both original coordinates equal the code, so each decoded coordinate needs one copy of it.", success: "One coordinate reconstructs these diagonal points exactly. Inputs away from the diagonal would lose information with this encoder and decoder.", rule: "code = input₁\nreconstruction = [weight₁ × code, weight₂ × code]", run: (v, b) => ({ readings: (b ? [-1, .5, 3] : [1, 2, 4]).map(x => row(`Point [${x}, ${x}]`, `One-number code: ${x}`, [x * num(v, "a"), x * num(v, "b")], [x, x])) }),
  },
  {
    id: "variational-autoencoders", title: "Sample a code without losing the controls", story: "Botie's encoder supplies a mean and a scale for a distribution of latent codes. Instead of treating the random draw as an opaque operation, we draw standard noise and transform it. The mean and scale then remain explicit in the calculation.", task: "Use mean 1 and standard deviation 2 with the supplied fixed noise draws.", controls: [dial("mean", "Latent mean", -2, 3, .5), dial("scale", "Latent standard deviation", .5, 3, .5)], initial: { mean: 0, scale: 1 }, solution: { mean: 1, scale: 2 }, hint: "Multiply the fixed noise by the standard deviation, then add the mean.", success: "This is the reparameterisation step. VAE training also balances reconstruction with a penalty that shapes the encoded distributions toward a prior.", rule: "z = mean + standard deviation × epsilon\nepsilon is drawn from a standard normal distribution", run: (v, b) => ({ readings: (b ? [-.5, .5, 1.5] : [-1, 0, 1]).map(e => row(`Noise ${e}`, "Fixed draw for a reproducible experiment", num(v, "mean") + num(v, "scale") * e, 1 + 2 * e)) }),
  },
  {
    id: "generative-adversarial-networks", title: "Follow the critic's gradient", story: "Botie's tiny generator produces a scalar sample. A fixed discriminator gives larger samples a higher real score in this local example. The generator needs to move its sample in the direction that reduces its own loss, not copy a labelled target sample.", task: "Choose gradient descent on the generator's non-saturating loss. The discriminator stays fixed for this step.", controls: [choose("direction", "Generator update", ["Add the loss gradient", "Subtract the loss gradient"])], initial: { direction: "Add the loss gradient" }, solution: { direction: "Subtract the loss gradient" }, hint: "With D(g)=sigmoid(g), the derivative of -log(D(g)) is D(g)-1. It is negative here, so subtracting it increases g.", success: "The updated sample receives a higher score from this fixed discriminator. A GAN alternates generator and discriminator learning; pleasing one fixed critic is not evidence of realistic generation.", rule: "D(g) = sigmoid(g)\ngenerator loss = −ln(D(g))\ng_new = g − 0.5 × (D(g) − 1)", run: (v, b) => ({ readings: (b ? [-1, 1] : [-2, 0]).map(g => { const grad = 1 / (1 + Math.exp(-g)) - 1; return row(`Generated value ${g}`, "One update, learning rate 0.5", g + (str(v, "direction") === "Subtract the loss gradient" ? -1 : 1) * .5 * grad, g - .5 * grad); }) }),
  },
  {
    id: "diffusion-models", title: "Remove the noise in the right units", story: "Botie's clean signal was scaled down and mixed with known noise. If we can estimate the noise, we can rearrange that corruption equation to estimate the clean signal. Merely subtracting the noise misses both scale factors.", task: "Choose the reconstruction that undoes the supplied forward corruption. This exercise provides the exact noise estimate.", controls: [choose("undo", "Reconstruction", ["Subtract noise only", "Undo both scale factors"])], initial: { undo: "Subtract noise only" }, solution: { undo: "Undo both scale factors" }, hint: "Subtract 0.6 times the noise, then divide by 0.8. The squared coefficients sum to one.", success: "With the exact noise, the clean signal is recovered. Real diffusion models estimate noise imperfectly and use a trained, multi-step reverse process.", rule: "noisy = 0.8 × clean + 0.6 × noise\nclean estimate = (noisy − 0.6 × estimated noise) / 0.8", run: (v, b) => ({ readings: (b ? [[2, -.5], [-1, 1]] : [[1, .5], [0, -1]]).map(([clean, noise], i) => { const noisy = .8 * clean + .6 * noise; return row(`Signal ${i + 1}`, `Noisy ${noisy.toFixed(2)}; estimated noise ${noise}`, str(v, "undo") === "Subtract noise only" ? noisy - noise : (noisy - .6 * noise) / .8, clean); }) }),
  },
  {
    id: "supervised-fine-tuning", title: "Learn from the demonstrated answer", story: "Botie's training example contains a prompt followed by a demonstrated answer. For this response-only fine-tuning setup, prompt tokens provide context while the answer tokens provide the supervised targets.", task: "Select only the answer tokens for the loss. The prompt must remain available as context.", controls: [{ kind: "select", key: "loss", label: "Tokens included in the loss", items: ["Prompt: What", "Prompt: colour?", "Answer: It", "Answer: is", "Answer: blue"] }], initial: { loss: ["Prompt: What", "Prompt: colour?", "Answer: It", "Answer: is", "Answer: blue"] }, solution: { loss: ["Answer: It", "Answer: is", "Answer: blue"] }, hint: "Mask prompt positions out of the loss, not out of the model's context.", success: "Only the demonstrated response contributes targets in this setup. Other fine-tuning recipes can use different loss masks; the data format and objective must agree.", rule: "response-only loss = mean of next-token losses over answer positions", run: v => ({ readings: ["Prompt: What", "Prompt: colour?", "Answer: It", "Answer: is", "Answer: blue"].map(t => row(t, "Should this position contribute to the response-only loss?", +list(v, "loss").includes(t), +t.startsWith("Answer"))) }),
  },
  {
    id: "low-rank-adaptation", title: "Add a narrow correction", story: "Botie has a frozen projection but needs to adapt its behaviour. A rank-one correction can be built from a column and a row. Their product changes the projection while using fewer trainable parameters than a full matrix.", task: "Keep the base projection fixed and set the two entries of the correction column to [1, 2]. The correction row is fixed at [1, -1].",
    controls: [dial("a", "Correction column: first entry", -2, 3), dial("b", "Correction column: second entry", -2, 3)], initial: { a: 0, b: 0 }, solution: { a: 1, b: 2 }, hint: "The narrow intermediate value is x₁-x₂. Multiply it by the column, then add the unchanged base output.", success: "The correction passed through a one-dimensional bottleneck. LoRA trains low-rank factors while freezing the base weights; this toy omits its optional scaling factor.", rule: "base W = identity\nΔW = column([a,b]) × row([1,−1])\noutput = W × input + ΔW × input", run: (v, b) => ({ readings: (b ? [[3, 1], [1, 3]] : [[2, 1], [0, 2]]).map((x, i) => row(`Input ${i + 1}`, `[${x}]`, [x[0] + num(v, "a") * (x[0] - x[1]), x[1] + num(v, "b") * (x[0] - x[1])], [x[0] + x[0] - x[1], x[1] + 2 * (x[0] - x[1])])) }),
  },
  {
    id: "reinforcement-learning", title: "Get Botie to the charging dock", story: "Botie can move through the workshop, but two floor tiles are blocked. Every move costs time and reaching the dock gives a reward. A useful policy must consider the consequences of several actions, not just the next tile.", task: "Choose five moves that reach the dock without hitting a blocked tile. Start at the top-left; the dock is at the bottom-right.", controls: Array.from({ length: 5 }, (_, i) => choose(`step${i}`, `Move ${i + 1}`, ["Right", "Down", "Left", "Up"])), initial: { step0: "Down", step1: "Right", step2: "Right", step3: "Down", step4: "Right" }, solution: { step0: "Right", step1: "Right", step2: "Right", step3: "Down", step4: "Down" }, hint: "Go along the top row, then down the right edge. The blocked middle tiles make a direct diagonal-style route impossible.", success: "The route reaches the dock with no wasted moves. You supplied this policy manually. Reinforcement learning uses rewards from repeated interaction to improve a policy algorithmically.", rule: "ordinary move: −1 reward\nblocked move: −3 reward, stay in place\nreach the dock: +10 reward, end the episode", run: v => { let x = 0, y = 0, reward = 0, bumps = 0; const path = [0]; for (let i = 0; i < 5; i++) { if (x === 3 && y === 2) break; const [dx, dy] = ({ Right: [1, 0], Down: [0, 1], Left: [-1, 0], Up: [0, -1] } as Record<string, number[]>)[str(v, `step${i}`)]; const nx = x + dx, ny = y + dy; if (nx < 0 || nx > 3 || ny < 0 || ny > 2 || (ny === 1 && (nx === 1 || nx === 2))) { reward -= 3; bumps++; } else { x = nx; y = ny; reward += x === 3 && y === 2 ? 10 : -1; } path.push(y * 4 + x); } return { readings: [row("Destination", "Dock at column 3, row 2", [x, y], [3, 2]), row("Blocked moves", "Avoid collisions", bumps, 0), row("Episode reward", "Ten for docking, minus four ordinary moves", reward, 6)], scene: { kind: "path", width: 4, cells: ["Start", "", "", "", "", "Blocked", "Blocked", "", "", "", "", "Dock"], path } }; },
  },
  {
    id: "retrieval-augmented-generation", title: "Bring the answer its evidence", story: "Botie is asked when the workshop closes on Saturday. A plausible sentence is not enough; the answer needs the relevant source. Retrieval supplies that evidence as context before generation.", task: "Retrieve the current Saturday-hours document, excluding irrelevant and outdated snippets.", controls: [{ kind: "select", key: "docs", label: "Source snippets to retrieve", items: ["Current hours: Saturday closes at 14:00", "Old hours: Saturday closes at 17:00", "Shipping: parcels leave on Monday", "Menu: coffee is available"] }], initial: { docs: ["Old hours: Saturday closes at 17:00"] }, solution: { docs: ["Current hours: Saturday closes at 14:00"] }, hint: "Match both the subject and the date of the information. A relevant but outdated snippet can still lead to a wrong answer.", success: "The current source supports the answer. Retrieval does not guarantee faithful generation; the generated answer must still be checked against the evidence.", rule: "question → retrieve relevant current evidence → place it in context → generate and verify", run: v => ({ readings: [row("Retrieved evidence", "Question: current Saturday closing time", [...list(v, "docs")].sort(), ["Current hours: Saturday closes at 14:00"])] }),
  },
  {
    id: "evaluating-generative-models", title: "Do not let the average hide a broken task", story: "Botie's model answers routine questions well but fails every accessibility request in this small evaluation. Reporting only an overall average hides that pattern. We need to inspect the groups as well as the total.", task: "Include both task groups in the evaluation report.", controls: [{ kind: "select", key: "groups", label: "Groups reported separately", items: ["Routine questions", "Accessibility requests"] }], initial: { groups: ["Routine questions"] }, solution: { groups: ["Routine questions", "Accessibility requests"] }, hint: "A high-scoring group cannot tell us whether a different group works. Keep the low-scoring group visible.", success: "The report now exposes the failure that needs work. Small samples are uncertain, so a real evaluation also needs enough representative held-out examples and a clear scoring procedure.", rule: "group success rate = successful cases in group / all cases in group", run: (v, b) => { const counts = b ? [[18, 20], [0, 4]] : [[9, 10], [0, 2]], names = ["Routine questions", "Accessibility requests"]; return { readings: names.map((name, i) => row(name, `${counts[i][0]} successes in ${counts[i][1]} held-out cases`, list(v, "groups").includes(name) ? counts[i][0] / counts[i][1] : "Not reported", counts[i][0] / counts[i][1])) }; },
  },
];
