import { type Mission, dial, choose, num, str, row, mean, dot, sequence } from "./types";

export const networks: Mission[] = [
  {
    id: "dense-layers", title: "Give two neurons different jobs", story: "Botie wants two measurements from every parcel: the sum of height and mass, and their difference. A dense layer can do both at once, with a separate set of weights for each output neuron.", task: "The first neuron already adds both inputs. Set the second neuron's weights so it subtracts mass from height.", controls: [dial("h", "Second neuron: height weight", -2, 2), dial("m", "Second neuron: mass weight", -2, 2)], initial: { h: 1, m: 1 }, solution: { h: 1, m: -1 }, hint: "The two outputs need different weight vectors. The second is [1, -1]. Biases are zero and activation is identity here.", success: "Each input row produced two outputs. That is the forward pass through this small dense layer; no training took place while we set the weights.", rule: "output₁ = height + mass\noutput₂ = height × w₁ + mass × w₂", run: (v, b) => ({ readings: (b ? [[2, 5], [4, 1]] : [[1, 3], [3, 2]]).map((x, i) => row(`Parcel ${i + 1}`, `Input: ${x}`, [x[0] + x[1], dot(x, [num(v, "h"), num(v, "m")])], [x[0] + x[1], x[0] - x[1]])) }),
  },
  {
    id: "shapes-and-flattening", title: "Keep each picture together", story: "Botie has a batch of two tiny images, each with two rows and three columns. A dense layer expects one feature row per image. Flattening must preserve the batch boundary.", task: "Choose the output shape that keeps two examples and places each image's six pixels in its own row.", controls: [dial("batch", "Number of examples", 1, 12), dial("features", "Features per example", 1, 12)], initial: { batch: 1, features: 12 }, solution: { batch: 2, features: 6 }, hint: "Flatten the image dimensions together. Leave the leading batch dimension alone.", success: "The total number of values is unchanged, and the two examples stay separate. A reshape changes the arrangement, not the pixel values.", rule: "input shape: (2, 2, 3)\noutput shape: (batch, rows × columns)", run: v => ({ readings: [row("Output shape", "Two images, six pixels each", [num(v, "batch"), num(v, "features")], [2, 6]), row("Value count", "All original pixels must remain", num(v, "batch") * num(v, "features"), 12)] }),
  },
  {
    id: "loss-functions", title: "Make a costly mistake cost more", story: "Botie's predictions have errors of different sizes. If large misses should count disproportionately, squaring the errors does that. Taking an absolute value gives a different trade-off.", task: "Choose mean squared error for this workshop's stated scoring rule.", controls: [choose("loss", "Loss rule", ["Mean error", "Mean absolute error", "Mean squared error"])], initial: { loss: "Mean error" }, solution: { loss: "Mean squared error" }, hint: "Square each error before averaging. Averaging signed errors can let overestimates cancel underestimates.", success: "Squaring prevented cancellation and made larger misses more expensive. The appropriate loss depends on the behaviour we want, rather than on which score looks smallest.", rule: "MSE = mean((prediction − target)²)", run: (v, b) => { const errors = b ? [-1, 3, -2] : [-2, 0, 2]; return { readings: errors.map((x, i) => row(`Error ${i + 1}`, `Prediction minus target: ${x}`, str(v, "loss") === "Mean squared error" ? x * x : str(v, "loss") === "Mean absolute error" ? Math.abs(x) : x, x * x)), note: `Mean of your costs: ${mean(errors.map(x => str(v, "loss") === "Mean squared error" ? x * x : str(v, "loss") === "Mean absolute error" ? Math.abs(x) : x)).toFixed(3)}` }; },
  },
  {
    id: "backpropagation", title: "Follow the effect backwards", story: "Botie needs to know how changing a weight changes the loss. The weight first changes the prediction; the prediction then changes the loss. The chain rule multiplies those local effects.", task: "Choose the operation that combines the two derivatives.", controls: [choose("operation", "Combine local derivatives", ["Add", "Multiply", "Keep only the loss derivative"])], initial: { operation: "Add" }, solution: { operation: "Multiply" }, hint: "If one unit of weight changes the prediction by x units, each of those units carries the loss derivative with it.", success: "The gradient accounts for the whole path from weight to loss. Larger networks reuse this same chain rule and sum contributions where paths join.", rule: "prediction = weight × input\nloss = ½(prediction − target)²\ndloss/dweight = (prediction − target) × input", run: (v, b) => ({ readings: (b ? [[3, 2], [-2, 3]] : [[2, 3], [4, -1]]).map(([x, error], i) => row(`Path ${i + 1}`, `dprediction/dweight: ${x}; dloss/dprediction: ${error}`, str(v, "operation") === "Multiply" ? x * error : str(v, "operation") === "Add" ? x + error : error, x * error)) }),
  },
  sequence("training-a-network", "Close the learning loop", "Botie's network starts with unhelpful weights. A prediction tells us what it does now; a loss measures the mistake; gradients tell us how the parameters influenced it. We need all three before an update means anything.", "Build one supervised training iteration, then return to prediction for the next batch.", ["Pass a training batch through the network", "Compare predictions with labels using a loss", "Backpropagate to calculate parameter gradients", "Update the parameters with the optimiser", "Repeat with the next training batch"], "An update needs gradients, and those gradients need the loss from the current forward pass.", "That is a training loop. Validation is checked separately to see whether improving the training loss is helping on unseen examples."),
  {
    id: "dropout", title: "Keep the average signal steady", story: "Botie randomly switches off half the activations during training. If he leaves the survivors unchanged, the average signal is halved too. Inverted dropout compensates by scaling the survivors.", task: "Set the survivor multiplier for a keep probability of one half.", controls: [dial("scale", "Survivor multiplier", 0, 4, .5)], initial: { scale: 1 }, solution: { scale: 2 }, hint: "A value survives half the time. Its surviving value needs to be twice as large to preserve the expectation.", success: "The expected activation is preserved, even though any individual masked pass can differ. At inference, inverted dropout leaves the activations unmasked and unscaled.", rule: "training output = activation × mask / keep probability\nexpected output = keep probability × scaled activation", run: (v, b) => ({ readings: (b ? [1, 3, 5] : [2, 4, 6]).map(x => row(`Activation ${x}`, "Keep probability 0.5", .5 * x * num(v, "scale"), x)) }),
  },
  {
    id: "normalisation-layers", title: "Normalise within each example", story: "Two examples reach Botie's layer with very different offsets. Layer normalisation treats each example separately: it subtracts that row's mean and divides by that row's standard deviation.", task: "Choose row-wise normalisation for this batch. Use population variance; the toy rows have nonzero variance.", controls: [choose("axis", "Normalise over", ["The whole batch", "Each row"])], initial: { axis: "The whole batch" }, solution: { axis: "Each row" }, hint: "One row should not borrow its centre or scale from the other row.", success: "Each row now has zero mean and unit population variance. This exercise omits the learned scale, learned shift and stabilising epsilon to isolate the axes being normalised.", rule: "normalised = (value − row mean) / row standard deviation", run: (v, b) => { const data = b ? [[2, 6], [20, 24]] : [[1, 3], [10, 12]]; return { readings: data.map((r, i) => { const ref = str(v, "axis") === "Each row" ? r : data.flat(), m = mean(ref), s = Math.sqrt(mean(ref.map(x => (x - m) ** 2))); return row(`Example ${i + 1}`, `Activations: ${r}`, r.map(x => (x - m) / s), [-1, 1]); }) }; },
  },
  {
    id: "hopfield-network", title: "Repair a noisy memory", story: "Botie stored the binary pattern [1, 1, -1]. Its pairwise weights favour agreement with that pattern. One bit has flipped, and we can ask the other bits what the damaged bit should be.", task: "Update only the corrupted first bit using the weighted vote from the other two bits.", controls: [dial("bit", "First bit", -1, 1, 2)], initial: { bit: -1 }, solution: { bit: 1 }, hint: "The stored pattern links the first bit positively to the second and negatively to the third. Both neighbours vote for +1.", success: "This update restores the stored pattern and lowers its energy. A Hopfield network can also settle into unwanted attractors; repair is not guaranteed for arbitrary corruption.", rule: "weights = outer product of stored pattern, with zero diagonal\nnew bit_i = sign(sum(weights_ij × bit_j))", run: v => { const s = [num(v, "bit"), 1, -1]; const energy = -(s[0] * s[1] - s[0] * s[2] - s[1] * s[2]); return { readings: [row("Recalled pattern", "One corrupted bit", s, [1, 1, -1]), row("Memory energy", "Lower is preferred by these weights", energy, -3)] }; },
  },
  sequence("restricted-boltzmann-machine", "Pass a pattern through hidden units", "Botie's visible units hold an observation. Hidden units describe patterns that could account for it. In an RBM, connections run between those groups, allowing conditional sampling of one group given the other.", "Arrange one visible-to-hidden-to-visible reconstruction step.", ["Set the visible units to a data example", "Compute hidden probabilities from the visible units", "Sample the hidden units", "Compute visible probabilities from the hidden units", "Sample a reconstructed visible example"], "Hidden units depend on the visible observation; the reconstruction depends on the sampled hidden state.", "This is a short Gibbs reconstruction chain. RBM learning compares data-driven and model-driven statistics; this ordering exercise does not train an RBM."),
  {
    id: "self-organising-map", title: "Move a prototype toward a visitor", story: "Botie's map is made of prototype vectors. When a new point arrives, the closest prototype wins and moves toward it. Nearby prototypes can move too, which helps preserve neighbourhoods on the map.", task: "Move this winning prototype halfway toward the input point. Neighbour updates are omitted here.", controls: [dial("rate", "Winner learning rate", 0, 1, .1)], initial: { rate: 0 }, solution: { rate: .5 }, hint: "Add half the difference between the input and the current prototype.", success: "The winner moved closer to the input. The neighbourhood update, covered in the lesson, is what distinguishes the full map from independent prototype updates.", rule: "new prototype = prototype + rate × (input − prototype)", run: (v, b) => { const p = b ? [2, 4] : [0, 2], x = b ? [6, 0] : [4, 6]; return { readings: p.map((a, i) => row(`Coordinate ${i + 1}`, `Prototype ${a}; input ${x[i]}`, a + num(v, "rate") * (x[i] - a), (a + x[i]) / 2)), scene: { kind: "plot", x: "Feature 1", y: "Feature 2", points: [[x[0], x[1], 0], [p[0] + num(v, "rate") * (x[0] - p[0]), p[1] + num(v, "rate") * (x[1] - p[1]), 1]], line: [[p[0], p[1]], [x[0], x[1]]] } }; },
  },
  {
    id: "hebbian-pca", title: "Stop a useful weight growing forever", story: "If Botie strengthens a weight whenever an input and output are active together, it can keep growing. Oja's rule adds a stabilising term to this Hebbian update. We can inspect that extra term before fitting a principal direction.", task: "Enable the stabilising term in Oja's update.", controls: [choose("rule", "Weight update", ["Plain Hebbian", "Oja"])], initial: { rule: "Plain Hebbian" }, solution: { rule: "Oja" }, hint: "Oja subtracts the squared output multiplied by the current weight from the Hebbian contribution.", success: "The correction counters unchecked weight growth. Learning a principal component also depends on centred data, repeated updates and a suitable learning-rate schedule.", rule: "y = w · x\nΔw = rate × (y × x − y² × w)", run: (v, b) => { const w = [.6, .8], x = b ? [2, 1] : [1, 2], y = dot(w, x); return { readings: w.map((a, i) => row(`Weight change ${i + 1}`, `w=[${w}], x=[${x}], rate=0.1`, .1 * (y * x[i] - (str(v, "rule") === "Oja" ? y * y * a : 0)), .1 * (y * x[i] - y * y * a))) }; },
  },
  {
    id: "recurrent-layers", title: "Carry something into the next step", story: "Botie receives one measurement at a time. If the machine forgets its previous output, it cannot keep a running total. A recurrent connection brings information from the previous step into the next calculation.", task: "Set the memory coefficient to keep a running sum. The initial state is zero and the activation is identity.", controls: [dial("memory", "Previous-state coefficient", 0, 1, .25)], initial: { memory: 0 }, solution: { memory: 1 }, hint: "Add the whole previous total to the new input.", success: "The state now carries the total through the sequence. This simple linear recurrence illustrates memory; practical recurrent layers add learned projections and nonlinear functions or gates.", rule: "state_t = input_t + memory coefficient × state_(t−1)", run: (v, b) => { const xs = b ? [2, -1, 3, 1] : [1, 2, 1, 3]; let state = 0, total = 0; return { readings: xs.map((x, i) => { state = x + num(v, "memory") * state; total += x; return row(`Step ${i + 1}`, `Input ${x}`, state, total); }) }; },
  },
  {
    id: "radial-basis-networks", title: "Build a detector with a neighbourhood", story: "Botie wants a detector that responds strongly near one prototype and weakly far away. A radial basis function measures distance from its centre, then turns that distance into a smooth response.", task: "Centre the detector at 2 with a width of 1 to match the requested responses.", controls: [dial("centre", "Prototype centre", -1, 5, .5), dial("width", "Width", .5, 3, .5)], initial: { centre: 0, width: 2 }, solution: { centre: 2, width: 1 }, hint: "The response peaks at the centre. Width controls how quickly it falls away.", success: "This detector is local: it responds most to inputs near its prototype. A radial basis network combines several such responses to make a prediction.", rule: "response = exp(−(x − centre)² / (2 × width²))", run: (v, b) => ({ readings: (b ? [.5, 2, 3.5] : [0, 1, 2, 3, 4]).map(x => row(`Input ${x}`, "Requested centre 2, width 1", Math.exp(-((x - num(v, "centre")) ** 2) / (2 * num(v, "width") ** 2)), Math.exp(-((x - 2) ** 2) / 2))) }),
  },
  {
    id: "residual-connections", title: "Let the layer make a correction", story: "Botie's next layer only needs to adjust a useful representation. A residual connection carries the input forward and adds the layer's correction, so a zero correction can leave the input unchanged.", task: "Keep the skip connection and add the residual branch to it.", controls: [choose("merge", "Combine branches", ["Replace the input", "Add to the input", "Multiply by the input"])], initial: { merge: "Replace the input" }, solution: { merge: "Add to the input" }, hint: "Try the case where the correction is zero. The original input should survive.", success: "The shortcut preserves an identity route through the block. This helps both information and gradients pass through deep networks.", rule: "output = input + residual(input)", run: (v, b) => ({ readings: (b ? [[3, 0], [1, -.5], [-2, 1]] : [[2, 0], [3, 1], [-1, .5]]).map(([x, correction], i) => row(`Case ${i + 1}`, `Input ${x}; correction ${correction}`, str(v, "merge") === "Replace the input" ? correction : str(v, "merge") === "Add to the input" ? x + correction : x * correction, x + correction)) }),
  },
];
