import { type Mission, dial, choose, num, str, list, row, mean, dot, softmax, sequence } from "./types";

export const representations: Mission[] = [
  {
    id: "a-vector-for-a-word", title: "Give the word more than an address", story: "Botie's token ID tells him which entry to look up. The embedding row contains several learned numbers. Those coordinates can support useful comparisons, unlike the numerical distance between two arbitrary IDs.", task: "Select cat's supplied embedding, [0.8, 0.2], instead of treating its ID as its meaning.", controls: [choose("representation", "Representation for cat", ["Token ID: 103", "Embedding: [0.8, 0.2]", "Embedding: [0.1, 0.9]"])], initial: { representation: "Token ID: 103" }, solution: { representation: "Embedding: [0.8, 0.2]" }, hint: "The ID is a lookup key. Use the row associated with it.", success: "The vector came from the embedding table. Useful geometry has to be learned from data; assigning a vector does not automatically give it meaning.", rule: "embedding = embedding_table[token_id]", run: v => ({ readings: [row("Retrieved representation", "Table: cat → [0.8, 0.2]; car → [0.1, 0.9]", str(v, "representation") === "Token ID: 103" ? [103] : str(v, "representation").includes("0.8") ? [.8, .2] : [.1, .9], [.8, .2])] }),
  },
  {
    id: "distance-and-similarity", title: "Compare direction without rewarding length", story: "Botie has two vectors pointing in the same direction, but one is much longer. A dot product grows with length. Cosine similarity divides that effect out so we can compare direction.", task: "Choose cosine similarity for these same-direction vector pairs.", controls: [choose("metric", "Comparison", ["Dot product", "Euclidean distance", "Cosine similarity"])], initial: { metric: "Dot product" }, solution: { metric: "Cosine similarity" }, hint: "Divide the dot product by the product of both vector lengths.", success: "The similarity is one for each same-direction pair. This comparison ignores magnitude; that is useful only when magnitude is not part of what we want to compare.", rule: "cosine similarity = dot(a, b) / (length(a) × length(b))", run: (v, b) => { const pairs = b ? [[[2, 1], [6, 3]], [[1, -2], [2, -4]]] : [[[1, 2], [2, 4]], [[3, 1], [6, 2]]]; return { readings: pairs.map(([a, c], i) => row(`Pair ${i + 1}`, `[${a}] and [${c}]`, str(v, "metric") === "Dot product" ? dot(a, c) : str(v, "metric") === "Euclidean distance" ? Math.hypot(...a.map((x, j) => x - c[j])) : dot(a, c) / (Math.hypot(...a) * Math.hypot(...c)), 1)) }; },
  },
  sequence("latent-semantic-analysis", "Compress a table of word use", "Botie has a large table of terms and documents. Documents that use related terms can share a lower-dimensional pattern even when their exact word counts differ. SVD gives us a way to retain strong shared directions.", "Arrange the steps of this truncated-SVD document representation.", ["Count terms within documents", "Apply the chosen term weighting", "Compute the singular value decomposition", "Keep the largest chosen singular components", "Compare documents in the reduced representation"], "The weighting changes the matrix being decomposed. The reduced representation comes from the retained components.", "Keeping fewer components compresses the matrix and discards some variation. These latent directions are statistical patterns, not guaranteed human concepts."),
  {
    id: "pointwise-mutual-information", title: "Ask whether the pair is surprising", story: "Two common words meet often even by chance. Botie needs to compare the observed pair probability with what independence would predict. PMI takes the logarithm of that ratio.", task: "Use the independence baseline and a base-2 logarithm to calculate PMI.", controls: [choose("baseline", "Expected pair probability", ["Add marginals", "Multiply marginals"]), choose("log", "Report", ["Raw ratio", "Log base 2"])], initial: { baseline: "Add marginals", log: "Raw ratio" }, solution: { baseline: "Multiply marginals", log: "Log base 2" }, hint: "Under independence, multiply the marginal probabilities. A pair occurring twice as often as that expectation has PMI of one bit.", success: "A positive PMI means the pair is more common than the independence baseline. Rare pairs can receive unstable high scores, so counts and smoothing matter.", rule: "PMI(a,b) = log₂(P(a,b) / (P(a) × P(b)))", run: (v, b) => { const pairs = b ? [[.1, .2, .04], [.2, .4, .04]] : [[.2, .25, .1], [.4, .25, .1]]; return { readings: pairs.map(([a, c, joint], i) => { const ratio = joint / (str(v, "baseline") === "Multiply marginals" ? a * c : a + c); return row(`Pair ${i + 1}`, `P(a)=${a}, P(b)=${c}, P(a,b)=${joint}`, str(v, "log") === "Log base 2" ? Math.log2(ratio) : ratio, Math.log2(joint / (a * c))); }) }; },
  },
  {
    id: "random-indexing", title: "Accumulate the context clues", story: "Each context word has a fixed sparse random index vector. Botie builds a word's representation by adding the vectors of contexts in which it occurs. The random vectors are addresses for accumulating evidence, not learned word meanings on their own.", task: "Add the supplied context vectors coordinate by coordinate.", controls: [choose("combine", "Combine contexts", ["Keep first", "Add", "Multiply"])], initial: { combine: "Keep first" }, solution: { combine: "Add" }, hint: "A context observed twice contributes its index vector twice. Positive and negative contributions can cancel.", success: "The representation now accumulates the observed contexts in a fixed-size space. Random projection introduces collisions and approximation.", rule: "word representation = sum of index vectors of observed contexts", run: (v, b) => { const a = b ? [0, 1, -1] : [1, 0, -1], c = b ? [1, 0, 1] : [0, 1, -1]; return { readings: [row("Context vector", `[${a}] plus [${c}]`, a.map((x, i) => str(v, "combine") === "Add" ? x + c[i] : str(v, "combine") === "Multiply" ? x * c[i] : x), a.map((x, i) => x + c[i]))] }; },
  },
  {
    id: "embedding-layers", title: "Send each ID to the right drawer", story: "Botie's embedding layer is a table. An ID chooses a row, including when the same ID appears twice. Multiplying by the ID would change the representation instead of retrieving it.", task: "Use row lookup to return embeddings for the incoming IDs.", controls: [choose("operation", "Operation", ["Multiply first row by ID", "Look up row by ID"])], initial: { operation: "Multiply first row by ID" }, solution: { operation: "Look up row by ID" }, hint: "The rows are indexed from zero. Repeated IDs should retrieve identical rows.", success: "The layer returned the correct rows. During training, gradients can update the rows that were used without treating token IDs as numerical measurements.", rule: "output_i = table[ID_i]", run: (v, b) => { const table = [[1, 0], [0, 2], [3, 1]], ids = b ? [2, 0, 2] : [0, 1, 1]; return { readings: ids.map((id, i) => row(`Position ${i + 1}`, `ID ${id}; table [[1,0],[0,2],[3,1]]`, str(v, "operation") === "Look up row by ID" ? table[id] : table[0].map(x => x * id), table[id])) }; },
  },
  sequence("word2vec", "Learn from the nearby words", "Botie has no dictionary of word meanings. In skip-gram training, a word's vector becomes useful by helping predict the words observed around it. Negative samples provide contrasting word pairs.", "Arrange one skip-gram training update with negative sampling.", ["Choose a centre word and an observed context word", "Sample contrasting context words", "Look up the word and context vectors", "Score the observed and contrasting pairs", "Update vectors using the pair classification loss"], "The observed pair comes from a context window. Scores require the vectors; the update requires a loss.", "Repeated context-prediction updates shape the geometry of the vectors. This mechanism learns associations, not a complete definition of a word."),
  {
    id: "fasttext", title: "Build a word from shared fragments", story: "Botie has useful vectors for character fragments even when a whole word is rare. A fastText-style representation can combine the word entry with its subword vectors. Related spellings can then share some training evidence.", task: "Add the word vector and both supplied subword vectors. This toy uses an unnormalised sum.", controls: [{ kind: "select", key: "parts", label: "Contributions to the representation", items: ["Word entry", "First subword", "Second subword"] }], initial: { parts: ["Word entry"] }, solution: { parts: ["Word entry", "First subword", "Second subword"] }, hint: "Every supplied component contributes. The two subwords are not substitutes for one another.", success: "The representation includes shared fragments. Exact summing or averaging conventions depend on the implementation; the lesson discusses how the library represents them.", rule: "toy representation = word vector + subword₁ + subword₂", run: (v, b) => { const vectors = b ? [[2, 0], [0, 1], [1, 1]] : [[1, 0], [0, 2], [1, 1]], names = ["Word entry", "First subword", "Second subword"]; const sum = (indices: number[]) => [0, 1].map(i => indices.reduce((s, j) => s + vectors[j][i], 0)); return { readings: [row("Combined vector", `Components: ${vectors.map(x => `[${x}]`).join(" + ")}`, sum(names.flatMap((n, i) => list(v, "parts").includes(n) ? [i] : [])), sum([0, 1, 2]))] }; },
  },
  {
    id: "glove", title: "Fit the log of a co-occurrence count", story: "Botie counts how often word pairs occur together. GloVe trains word and context vectors so their dot product, plus biases, matches a log co-occurrence count. The logarithm compresses the range of counts.", task: "Choose the natural logarithm as the target for these positive counts.", controls: [choose("target", "Transform the count", ["Raw count", "Natural logarithm", "Square root"])], initial: { target: "Raw count" }, solution: { target: "Natural logarithm" }, hint: "The target is log(count), with separate biases in the fitted score. Zero counts need different treatment and are absent here.", success: "The targets now match this part of the GloVe objective. The full loss also weights counts so very rare and very frequent pairs do not dominate in the same way.", rule: "word vector · context vector + biases ≈ ln(co-occurrence count)", run: (v, b) => ({ readings: (b ? [3, 9, 27] : [2, 4, 16]).map(c => row(`Count ${c}`, "Target for the fitted score", str(v, "target") === "Natural logarithm" ? Math.log(c) : str(v, "target") === "Square root" ? Math.sqrt(c) : c, Math.log(c))) }),
  },
  {
    id: "positional-encoding", title: "Tell two identical tokens apart", story: "Botie receives the same token twice. A token embedding alone gives both positions the same vector. Adding a position signal lets a later layer tell which occurrence came first.", task: "Add the supplied position vectors to the shared token embedding.", controls: [choose("position", "Position signal", ["Ignore", "Add"])], initial: { position: "Ignore" }, solution: { position: "Add" }, hint: "Keep the token vector and add the position vector coordinate by coordinate.", success: "The occurrences now differ by position. These hand-picked position vectors illustrate the mechanism; models use learned, sinusoidal, rotary and other position schemes.", rule: "input at position i = token embedding + position vector_i", run: (v, b) => { const token = b ? [2, 3] : [1, 2], positions = [[0, 1], [1, 0]]; return { readings: positions.map((p, i) => row(`Position ${i + 1}`, `Token [${token}]; position [${p}]`, token.map((x, j) => x + (str(v, "position") === "Add" ? p[j] : 0)), token.map((x, j) => x + p[j]))) }; },
  },
  {
    id: "attention", title: "Ask the colour question", story: "Botie has three cards: colour, shape and size. Each card has a key describing its role and a value containing its information. A query that lines up with the colour key should give that card more influence.", task: "Set the two query coordinates to [2, 0]. Compare the keys, then watch the weighted mixture of values.", controls: [dial("q1", "Query: colour coordinate", -2, 2, .5), dial("q2", "Query: other coordinate", -2, 2, .5)], initial: { q1: 0, q2: 2 }, solution: { q1: 2, q2: 0 }, hint: "The colour key is [1, 0]. The other keys are [0, 1] and [-1, 0]. A query along the first positive coordinate favours colour.", success: "The colour value contributes most, but the other values still contribute. Attention creates a weighted mixture, rather than necessarily copying one card.", rule: "scores = query · each key / sqrt(2)\nweights = softmax(scores)\noutput = sum(weight_i × value_i)", run: (v, b) => { const keys = [[1, 0], [0, 1], [-1, 0]], values = b ? [8, 3, 1] : [10, 2, 0], weights = softmax(keys.map(k => dot([num(v, "q1"), num(v, "q2")], k) / Math.sqrt(2))), expected = softmax(keys.map(k => dot([2, 0], k) / Math.sqrt(2))); return { readings: [...weights.map((w, i) => row(["Colour", "Shape", "Size"][i], `Key [${keys[i]}]; value ${values[i]}`, w, expected[i])), row("Mixed output", "Weighted sum of the values", dot(weights, values), dot(expected, values))], scene: { kind: "tokens", input: "Query → key comparisons → weighted values", pieces: weights.map((w, i) => `${["Colour", "Shape", "Size"][i]}: ${(100 * w).toFixed(1)}%`) } }; },
  },
  {
    id: "pooling-a-text", title: "Keep the padding out of the summary", story: "Botie's batch contains two real token vectors and one padding vector. If padding is counted as a word, the pooled representation changes just because the batch needed an empty slot.", task: "Average only the two real tokens, excluding padding from both the sum and the count.", controls: [{ kind: "select", key: "tokens", label: "Tokens included in the mean", items: ["Token A", "Token B", "Padding"] }], initial: { tokens: ["Token A", "Token B", "Padding"] }, solution: { tokens: ["Token A", "Token B"] }, hint: "Exclude padding from the denominator as well as the numerator.", success: "The summary depends on the real tokens. Mean pooling still loses their order unless the token representations already encode contextual and positional information.", rule: "pooled vector = sum(real token vectors) / count(real tokens)", run: (v, b) => { const vectors = b ? [[2, 4], [4, 2], [0, 0]] : [[1, 3], [3, 1], [0, 0]], names = ["Token A", "Token B", "Padding"], chosen = vectors.filter((_, i) => list(v, "tokens").includes(names[i])); return { readings: [row("Pooled representation", `Real tokens: [${vectors[0]}], [${vectors[1]}]; padding: [0,0]`, [0, 1].map(i => mean(chosen.map(x => x[i]))), [0, 1].map(i => mean(vectors.slice(0, 2).map(x => x[i]))))] }; },
  },
  sequence("paragraph-vectors", "Give a document its own memory", "Botie wants a vector for an entire document. A paragraph-vector model learns a document-specific vector by using it in a word-prediction task, rather than merely averaging a list of word IDs.", "Arrange inference for a new document while the trained word-prediction model stays fixed.", ["Freeze the trained word and output parameters", "Initialise a vector for the new document", "Use the document vector to predict its observed words", "Update only the document vector to reduce the prediction loss", "Use that inferred vector for document comparisons"], "The new document needs a vector, but inference should not retrain the shared model for each document.", "The inferred vector is shaped by a prediction objective. This simplified sequence leaves the exact context variant to the full lesson."),
];
