import { type Mission, dial, choose, num, str, row, mean, dot, sequence } from "./types";

const patch = [[0, 0, 1, 1], [0, 0, 1, 1], [0, 0, 1, 1], [0, 0, 1, 1]];
export const vision: Mission[] = [
  {
    id: "filters-and-edges", title: "Find where the light changes", story: "Botie's camera sees a bright panel beside a dark wall. We want to locate the boundary, not report that the panel is bright. A filter that subtracts neighbouring values responds to change.", task: "Build a two-pixel filter that gives zero on a flat area and a positive response at a dark-to-bright edge.", controls: [dial("left", "Left pixel weight", -2, 2), dial("right", "Right pixel weight", -2, 2)], initial: { left: 1, right: 1 }, solution: { left: -1, right: 1 }, hint: "Subtract the left brightness from the right brightness.", success: "Equal neighbours cancel while a brightness change remains. This measures an edge in one direction; a full image detector also considers other directions and noise.", rule: "response = left weight × left pixel + right weight × right pixel", run: (v, b) => ({ readings: (b ? [[.5, .5], [.2, .8], [.8, .2]] : [[0, 0], [1, 1], [0, 1]]).map((p, i) => row(`Window ${i + 1}`, `Pixels: ${p}`, dot(p, [num(v, "left"), num(v, "right")]), p[1] - p[0])), scene: { kind: "pixels", panels: [{ label: "Camera image", cells: patch }] } }),
  },
  {
    id: "template-matching", title: "Find the missing badge", story: "Botie knows what the workshop badge looks like, but not where it is in the picture. Slide that known template across the image and compare each candidate window.", task: "Move the 2 by 2 window until its pixels match the badge exactly.", controls: [dial("x", "Window column", 0, 3), dial("y", "Window row", 0, 3)], initial: { x: 0, y: 0 }, solution: { x: 2, y: 1 }, hint: "The badge has two bright pixels on top and one below on the left. Its top-left corner is row 1, column 2, counting from zero.", success: "This window matches the template. A template at a different scale or angle would need additional handling; sliding alone only searches position.", rule: "match error = sum((window pixel − template pixel)²)", run: v => { const im = [[0, 0, 0, 0, 0], [0, 0, 1, 1, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]], badge = [[1, 1], [1, 0]], window = [0, 1].map(r => [0, 1].map(c => im[num(v, "y") + r][num(v, "x") + c])); return { readings: [row("Squared pixel error", "Zero means an exact match", window.flat().reduce((s, x, i) => s + (x - badge.flat()[i]) ** 2, 0), 0)], scene: { kind: "pixels", panels: [{ label: "Camera image", cells: im }, { label: "Your window", cells: window }, { label: "Badge", cells: badge }] } }; },
  },
  {
    id: "histogram-of-oriented-gradients", title: "Count edges instead of brightness", story: "Botie sees the same sign under brighter lighting. Its gradients get stronger, but their directions stay the same. A normalised histogram can preserve that pattern while reducing sensitivity to overall contrast.", task: "Normalise the two direction-bin magnitudes by their Euclidean length.", controls: [choose("norm", "Histogram normalisation", ["None", "Divide by sum", "Divide by Euclidean length"])], initial: { norm: "None" }, solution: { norm: "Divide by Euclidean length" }, hint: "For magnitudes 3 and 4, the Euclidean length is 5. The brighter version scales all three numbers by the same amount.", success: "The normalised direction pattern survives uniform contrast scaling in this toy example. Real HOG uses local cells, blocks and additional clipping conventions.", rule: "normalised histogram = histogram / sqrt(sum(bin²))", run: (v, b) => { const h = b ? [6, 8] : [3, 4], den = str(v, "norm") === "None" ? 1 : str(v, "norm") === "Divide by sum" ? h[0] + h[1] : Math.hypot(...h); return { readings: h.map((x, i) => row(`Direction bin ${i + 1}`, `Histogram: ${h}`, x / den, i ? .8 : .6)) }; },
  },
  {
    id: "keypoints-and-descriptors", title: "Match the same corner twice", story: "Botie has described a distinctive corner in one photograph. In the next photograph, a matching descriptor should be close and clearly better than the alternatives. A nearest match alone can be ambiguous.", task: "Choose the candidate descriptor with the smallest distance to [1, 0, 1].", controls: [choose("match", "Candidate", ["A: [0, 1, 0]", "B: [0.9, 0.1, 1]", "C: [1, 1, 1]"])], initial: { match: "A: [0, 1, 0]" }, solution: { match: "B: [0.9, 0.1, 1]" }, hint: "Compare coordinates, square their differences, and add. Candidate B differs only slightly in two coordinates.", success: "The nearest descriptor is a candidate correspondence. Repeated patterns can still fool it, so a full matcher also checks ambiguity and geometric consistency.", rule: "squared distance = sum((query coordinate − candidate coordinate)²)", run: v => { const s = str(v, "match")[0], d = s === "A" ? [0, 1, 0] : s === "B" ? [.9, .1, 1] : [1, 1, 1]; return { readings: [row("Squared descriptor distance", "Query [1, 0, 1]", d.reduce((a, x, i) => a + (x - [1, 0, 1][i]) ** 2, 0), .02)] }; },
  },
  {
    id: "image-alignment", title: "Put the camera views together", story: "Botie took a second picture after shifting the camera. Three matched points all moved by the same amount. Recovering that translation lets us align the views.", task: "Translate the source points two units right and one unit down.", controls: [dial("x", "Horizontal translation", -3, 3), dial("y", "Vertical translation", -3, 3)], initial: { x: 0, y: 0 }, solution: { x: 2, y: -1 }, hint: "Subtract each source coordinate from its target coordinate. The offsets agree across all three pairs.", success: "A translation aligns these matches. Real camera motion may require rotation, scale, a projective transformation, or rejection of incorrect matches.", rule: "aligned point = source point + translation", run: (v, b) => { const pts = b ? [[1, 2], [2, 4], [3, 1]] : [[0, 1], [1, 3], [2, 0]]; return { readings: pts.map(([x, y], i) => row(`Match ${i + 1}`, `Source [${x}, ${y}]`, [x + num(v, "x"), y + num(v, "y")], [x + 2, y - 1])), scene: { kind: "plot", x: "Horizontal position", y: "Vertical position", points: [...pts.map(([x, y]): [number, number, number] => [x + 2, y - 1, 0]), ...pts.map(([x, y]): [number, number, number] => [x + num(v, "x"), y + num(v, "y"), 1])] } }; },
  },
  sequence("haar-cascades", "Reject the easy negatives early", "Botie must examine many image windows. Most contain no object. A cascade saves effort by rejecting obvious negatives with cheap tests before spending time on more demanding ones.", "Order the work so an obvious negative never reaches the expensive stage.", ["Read the image window", "Evaluate the cheap first-stage features", "Reject windows that fail the first stage", "Evaluate later stages on survivors", "Keep windows that pass every stage"], "A failed stage ends the search for that window. It should not be sent on for more tests.", "The cascade spends the most work on plausible windows. Its early stages must avoid rejecting too many true objects."),
  {
    id: "convolution", title: "Use the same detector everywhere", story: "A bright patch can appear anywhere in Botie's image. Rather than inventing a new rule at every position, slide one small filter across the image. The shared weights look for the same local pattern.", task: "Set both weights to one half so each output averages a pair of neighbouring pixels.", controls: [dial("a", "First weight", -1, 1, .25), dial("b", "Second weight", -1, 1, .25)], initial: { a: 1, b: 0 }, solution: { a: .5, b: .5 }, hint: "The two contributions should be equal and sum to one.", success: "Every position used the same weights. Neural-network convolution commonly applies this cross-correlation operation without reversing the filter.", rule: "output_i = weight₁ × pixel_i + weight₂ × pixel_(i+1)", run: (v, b) => { const xs = b ? [1, 0, 1, 1] : [0, 1, 1, 0]; const out = xs.slice(0, -1).map((x, i) => x * num(v, "a") + xs[i + 1] * num(v, "b")); return { readings: out.map((x, i) => row(`Window ${i + 1}`, `Pixels: ${xs.slice(i, i + 2)}`, x, (xs[i] + xs[i + 1]) / 2)), scene: { kind: "pixels", panels: [{ label: "Input strip", cells: [xs] }, { label: "Filter output", cells: [out] }] } }; },
  },
  {
    id: "pooling", title: "Keep the strongest local signal", story: "Botie has more detector outputs than he needs. A pooling operation summarises each neighbourhood. If we want to preserve whether a strong response appeared anywhere in a neighbourhood, the maximum is a useful summary.", task: "Choose the pooling rule that keeps the strongest response from each window.", controls: [choose("pool", "Pooling rule", ["Mean", "Maximum", "Minimum"])], initial: { pool: "Mean" }, solution: { pool: "Maximum" }, hint: "We care whether a detector fired strongly, not the average response around it.", success: "Max pooling preserves the strongest response but discards its precise position. That loss of detail matters in tasks such as segmentation.", rule: "pooled value = maximum value in the window", run: (v, b) => ({ readings: (b ? [[1, 3, 2, 0], [0, 2, 7, 1]] : [[0, 4, 1, 2], [2, 1, 0, 6]]).map((p, i) => row(`Window ${i + 1}`, `Responses: ${p}`, str(v, "pool") === "Mean" ? mean(p) : str(v, "pool") === "Maximum" ? Math.max(...p) : Math.min(...p), Math.max(...p))) }),
  },
  sequence("convolutional-networks", "Assemble the picture inspector", "Botie needs a category for a whole image. Local filters find useful patterns, activations let the network combine them nonlinearly, and a final classifier uses the resulting representation.", "Build this small convolutional classifier in the stated order.", ["Read the pixel array", "Apply learned convolution filters", "Apply the activation function", "Pool the local responses", "Use the resulting features to predict a class"], "The pooling layer needs responses to summarise. The classifier needs the features produced by the earlier layers.", "This is one small architecture, not the only valid convolutional network. Training adjusts its filters using labelled examples."),
  {
    id: "u-net", title: "Give every pixel its label", story: "Botie needs the outline of a part, not just the name of the picture. In supervised U-Net training, each input image is paired with a labelled mask. The decoder must recover locations as well as recognise features.", task: "Select the four pixels labelled as the part in the reference mask. Coordinates count from zero.", controls: [{ kind: "select", key: "pixels", label: "Pixels belonging to the part", items: ["(0,0)", "(0,1)", "(0,2)", "(1,0)", "(1,1)", "(1,2)", "(2,0)", "(2,1)", "(2,2)"] }], initial: { pixels: ["(0,0)"] }, solution: { pixels: ["(0,1)", "(0,2)", "(1,1)", "(1,2)"] }, hint: "The labelled region occupies the top-right 2 by 2 square. We are reading a supervised target, not inferring labels from brightness alone.", success: "Your mask now agrees at every pixel. U-Net learns this mapping from labelled image-mask pairs, while skip connections bring spatial detail from encoder to decoder.", rule: "one target label per pixel\nsegmentation compares the predicted mask with the labelled mask", run: v => { const truth = [[0, 1, 1], [0, 1, 1], [0, 0, 0]], actual = truth.map((r, i) => r.map((_, j) => +listIncludes(v.pixels, `(${i},${j})`))); return { readings: actual.map((r, i) => row(`Mask row ${i}`, "0 background; 1 part", r, truth[i])), scene: { kind: "pixels", panels: [{ label: "Labelled reference mask", cells: truth }, { label: "Your mask", cells: actual }] } }; },
  },
  {
    id: "a-vector-for-a-picture", title: "Give the picture a small address", story: "Botie cannot search a collection efficiently by comparing every pixel. A representation can summarise useful visual measurements. Here we begin with a deliberately simple descriptor: the mean brightness of each column.", task: "Choose the operation that turns this 2 by 2 image into its two column averages.", controls: [choose("axis", "Summarise by", ["Row averages", "Column averages", "All pixels"])], initial: { axis: "Row averages" }, solution: { axis: "Column averages" }, hint: "Keep the columns separate. Average vertically within each one.", success: "The descriptor is smaller than the image and loses information. Learned image embeddings use much richer features, but the same question remains: what does the representation preserve?", rule: "descriptor_j = mean of pixels in column j", run: (v, b) => { const im = b ? [[0, 1], [.4, .8]] : [[0, 1], [0, 1]]; return { readings: [row("Image vector", "Two column means", str(v, "axis") === "All pixels" ? im.flat() : str(v, "axis") === "Row averages" ? im.map(mean) : [mean([im[0][0], im[1][0]]), mean([im[0][1], im[1][1]])], [mean([im[0][0], im[1][0]]), mean([im[0][1], im[1][1]])])], scene: { kind: "pixels", panels: [{ label: "Picture", cells: im }] } }; },
  },
  {
    id: "learning-the-metric-itself", title: "Make a useful difference count", story: "Botie's descriptors record object shape and background colour. For this task, two pictures of the same shape should remain close even when their backgrounds differ. A learned metric can change which differences matter.", task: "Give shape a weight of 1 and background a weight of 0 in this toy distance.", controls: [dial("shape", "Shape weight", 0, 2, .5), dial("background", "Background weight", 0, 2, .5)], initial: { shape: 1, background: 1 }, solution: { shape: 1, background: 0 }, hint: "The labels say that background is irrelevant for this particular task. Remove its contribution while keeping shape differences.", success: "The desired pairs are now close for the stated task. A real metric-learning system learns such choices from labelled relationships rather than from our manual settings.", rule: "weighted squared distance = shape weight × shape difference² + background weight × background difference²", run: (v, b) => ({ readings: (b ? [[0, 3], [2, 0], [1, 2]] : [[0, 2], [1, 0], [1, 1]]).map((p, i) => row(`Pair ${i + 1}`, `Shape, background difference: ${p}`, p[0] ** 2 * num(v, "shape") + p[1] ** 2 * num(v, "background"), p[0] ** 2)) }),
  },
  {
    id: "searching-a-collection-of-pictures", title: "Find the matching picture", story: "Botie's query picture is represented by [1, 0]. The collection contains several vectors. Searching an embedding collection means comparing these representations, then returning the associated pictures.", task: "Retrieve the candidate with the smallest Euclidean distance to the query.", controls: [choose("candidate", "Retrieved picture", ["Blue box: [0, 1]", "Red bolt: [0.9, 0.1]", "Green wheel: [-1, 0]"])], initial: { candidate: "Blue box: [0, 1]" }, solution: { candidate: "Red bolt: [0.9, 0.1]" }, hint: "Compare each candidate with [1, 0], coordinate by coordinate.", success: "The retrieval follows similarity in this representation. Whether that is the picture we intended depends on how well the embedding captures the task.", rule: "distance = sqrt(sum((query − candidate)²))", run: v => { const choice = str(v, "candidate"), p = choice.startsWith("Blue") ? [0, 1] : choice.startsWith("Red") ? [.9, .1] : [-1, 0]; return { readings: [row("Retrieval distance", "Query [1, 0]", Math.hypot(p[0] - 1, p[1]), Math.sqrt(.02))], scene: { kind: "plot", x: "Feature 1", y: "Feature 2", points: [[1, 0, 1], [0, 1], [.9, .1], [-1, 0]], line: [[1, 0], [p[0], p[1]]] } }; },
  },
];
const listIncludes = (value: unknown, item: string) => Array.isArray(value) && value.includes(item);
