import { missionById, labLessons } from "../labs";
import { assemble, evaluate, expressionTools, op, source as s, constant as c, type Build, type Data, type Expression } from "./engine";
import { TOOLS } from "./tools";
import { moreBuilds } from "./more";
import { textBuilds } from "./text-builds";
import { modernBuilds } from "./modern-builds";
import { constructionExplanations,constructionTitles } from "./explanations";
import { workshopContexts, workshopCaseNames } from "./contexts";
import type { HistoryLessonId } from "../history";

const add=(a:Expression,b:Expression)=>op("add",[a,b]);
const sub=(a:Expression,b:Expression)=>op("subtract",[a,b]);
const mul=(a:Expression,b:Expression)=>op("multiply",[a,b]);
const div=(a:Expression,b:Expression)=>op("divide",[a,b]);
const square=(a:Expression)=>op("square",[a]);
const total=(a:Expression)=>op("total",[a]);
const pack=(a:Expression,b:Expression)=>op("pack",[a,b]);
const average=(a:Expression)=>div(total(a),op("count",[a]));
const norm=(a:Expression)=>op("root",[total(square(a))]);
const sigmoid=(a:Expression)=>div(c(1),add(c(1),op("exp",[mul(c(-1),a)])));
const centred=(a:Expression)=>sub(a,average(a));
const fittedSlope=div(total(mul(centred(s("times")),centred(s("positions")))),total(square(centred(s("times")))));

export function build(id:string, challenge:string, sources:Record<string,string>, data:Record<string,Data>[], recipe:Expression, why?:string, limitation?:string):Build {
  const mission=missionById[id];
  const graph=assemble(recipe,TOOLS);
  const problem=id==="workshop-guide" ? "We need to give the machine instructions that work when the reading changes. Let's start with doubling a reading, then follow the values through the pieces we connect." : workshopContexts[id as HistoryLessonId];
  if(!problem)throw Error(`${id}: the workshop needs a connection to its lesson's problem.`);
  return { id, title:constructionTitles[id]??mission?.title ?? "A first machine with Botie", problem, challenge, sources, recipe,
    cases:data.map((data,i)=>{const result=evaluate(graph,data,TOOLS);if(result.error||result.output===undefined)throw Error(`${id}: ${result.error?.message}`);return {name:workshopCaseNames[id as HistoryLessonId]?.[i]??`Example ${i+1}`,data,expected:result.output};}),
    why:why??constructionExplanations[id]??mission?.success??"The output comes from the operations you connected. Changing a wire changes the calculation.", limitation:limitation??"This is a small construction problem. The lesson explains the assumptions and the parts of the full method that this example leaves out.", extras:["constant","add","subtract","multiply","divide","mean","dot","length","softmax"], };
}

export const BUILDS:Build[]=[
  build("workshop-guide","Build a machine that doubles each reading. We will place the pieces, connect their inputs, and test what comes out.",{reading:"Sensor reading"},[{reading:3},{reading:5},{reading:1}],mul(s("reading"),c(2)),"The same construction worked for different readings. The wires carry values between operations; they do not merely join labels."),
  build("statistics","How many deaths were recorded in an average week? Build the mean from the weekly counts. The same construction must work for records covering different numbers of weeks.",{weeklyCounts:"Deaths recorded each week"},[{weeklyCounts:[36,42,38,44,40]},{weeklyCounts:[28,36,32]},{weeklyCounts:[30,34,38,42]}],average(s("weeklyCounts")),"Adding the weekly counts gives the total recorded deaths. Dividing by the number of weeks shares that total equally across the recording period. The mean describes these records; it does not show how much the weeks differ or establish anyone's risk of dying.","These are invented weekly counts. Comparing mortality risks would also require information such as the population size and who was included in the records."),
  build("linear-algebra","What should each customer pay? A loaf costs 2 coins and a bottle of milk costs 3 coins. Build each contribution from its quantity and price, then return the total in coins.",{loaves:"Number of loaves",bottles:"Bottles of milk"},[{loaves:1,bottles:2},{loaves:3,bottles:1},{loaves:2,bottles:0}],add(mul(s("loaves"),c(2)),mul(s("bottles"),c(3)))),
  build("calculus","How fast was the traveller moving between the two readings? Build average speed in metres per second from the change in position and the elapsed time. Compare the answers as the interval gets shorter.",{startPosition:"Earlier position (metres)",endPosition:"Later position (metres)",startTime:"Earlier time (seconds)",endTime:"Later time (seconds)"},[{startPosition:4,endPosition:9,startTime:2,endTime:3},{startPosition:4,endPosition:6.25,startTime:2,endTime:2.5},{startPosition:4,endPosition:4.41,startTime:2,endTime:2.1}],div(sub(s("endPosition"),s("startPosition")),sub(s("endTime"),s("startTime"))),"The position difference tells us how far the traveller moved, and dividing by the time difference gives the interval's average speed. These readings come from a path whose position is the square of the time. Shortening the interval brings the estimate closer to the speed at the starting moment.","Each result is an average over a nonzero interval. Instantaneous speed is the limit of these averages, not an average computed by dividing by zero."),
  build("simple-linear-regression","How can we predict a position when the observations disagree? Fit a least-squares line to the supplied times and positions, then predict at the requested time. Use departures from both means to find the slope, and measure the requested time from the mean time.",{times:"Observation times",positions:"Observed positions",query:"Time to predict"},[{times:[0,1,2,3],positions:[1,4,5,8],query:4},{times:[0,1,2,3],positions:[1,4,5,8],query:5},{times:[0,1,2],positions:[2,2,5],query:3}],add(average(s("positions")),mul(fittedSlope,sub(s("query"),average(s("times"))))),"The fitted line passes through the mean time and mean position. Its slope uses how the time and position departures vary together, divided by the squared time departures. Every observation contributes, so the line can compromise between measurements that disagree.","The times and positions are invented and use arbitrary units. The observations have nonzero time variation. A straight-line approximation over a short interval does not describe a complete astronomical orbit."),
  build("held-out-evaluation","How far were the predicted positions from the reserved observations? Build their mean squared error. Reuse the averaging calculation and add a way to measure mistakes.",{predictions:"Predicted positions",targets:"Reserved observed positions"},[{predictions:[2,5,7],targets:[3,3,8]},{predictions:[4,2],targets:[1,4]}],average(square(sub(s("predictions"),s("targets")))),"The machine measures errors on observations that were excluded from fitting. Including training observations here would change what the score tells us."),
  build("logistic-regression","Which components should we inspect? Convert the failure score to a probability, then return 1 when it is at least 0.6 and 0 otherwise. The cutoff needs a probability, not the original score.",{score:"Component failure score"},[{score:-2},{score:0},{score:.5},{score:2}],op("gate",[sigmoid(s("score")),c(.6)])),
  build("judging-a-classifier","Of the reported lights, what fraction were real? Build precision from the counts of true detections and false alarms. The rule must work for each set of observations.",{tp:"True light detections",fp:"False light reports"},[{tp:3,fp:2},{tp:4,fp:1},{tp:2,fp:6}],div(s("tp"),add(s("tp"),s("fp")))),
  build("centring-on-the-mean","Find the training mean, then express each incoming reading relative to that mean. Keep the new reading out of the calculation of the reference point.",{training:"Training heights (cm)",reading:"New height (cm)"},[{training:[160,170,180],reading:172},{training:[155,165,175],reading:180}],sub(s("reading"),average(s("training")))),
  build("the-standard-score","Use the training readings to construct their mean and population standard deviation. Express the new reading in those units.",{training:"Group measurements",reading:"New measurement"},[{training:[160,170,180],reading:175},{training:[58,66,74],reading:62}],div(sub(s("reading"),average(s("training"))),op("root",[average(square(sub(s("training"),average(s("training")))))]))),
  build("feature-scaling","The recorded heights are in centimetres. Build a reusable conversion into metres, using the same rule for each person.",{reading:"Height (centimetres)"},[{reading:160},{reading:175},{reading:182}],div(s("reading"),c(100))),
  build("polynomial-features","How can we give the model a feature that grows faster at larger readings? Construct the square of the instrument reading. You may connect the same source to more than one input.",{reading:"Instrument reading"},[{reading:2},{reading:3},{reading:1.5}],mul(s("reading"),s("reading"))),
  build("pca","These centred points vary along the direction [1, 1]. Build a unit vector for that direction, then project each point onto it.",{point:"Centred point",direction:"Chosen principal direction"},[{point:[-2,-2],direction:[1,1]},{point:[3,3],direction:[1,1]}],op("dot",[s("point"),div(s("direction"),norm(s("direction")))]),undefined,"The principal direction is supplied. This challenge constructs projection and normalisation; finding that direction from a general dataset requires the decomposition explained in the lesson."),
  build("multiple-polynomial-regression","Does raising the temperature always increase the predicted yield? Build the supplied rule: start with 10, add twice the temperature change, add the pressure change, then add the product of both changes. Compare cooler and warmer settings at each pressure.",{temperature:"Temperature change",pressure:"Pressure change"},[{temperature:-1,pressure:-3},{temperature:1,pressure:-3},{temperature:-1,pressure:2},{temperature:1,pressure:2}],add(add(add(c(10),mul(c(2),s("temperature"))),s("pressure")),mul(s("temperature"),s("pressure")))),
  build("distance-metrics","How far apart are these two people on the standardised measurements? Build Manhattan distance by adding the absolute height and weight differences. A negative difference must not cancel a positive one.",{offset:"Standardised height and weight differences"},[{offset:[.3,.4]},{offset:[-.2,.3]},{offset:[.1,-.5]}],total(op("absolute",[s("offset")]))),
  build("gradient-descent-regression","The supplied derivative tells us the slope of the error at the current coefficient. Build an update that subtracts half the gradient.",{parameter:"Current parameter",gradient:"Current gradient"},[{parameter:0,gradient:-6},{parameter:6,gradient:6},{parameter:4,gradient:2}],sub(s("parameter"),mul(c(.5),s("gradient")))),
  build("gradient-boosting","The correction model predicts what the earlier model missed. Add a quarter of its prediction to the existing prediction.",{prediction:"Earlier prediction",residual:"Fitted residual prediction"},[{prediction:2,residual:4},{prediction:5,residual:-2},{prediction:1,residual:8}],add(s("prediction"),mul(c(.25),s("residual")))) ,
  build("multiclass-classification","Turn the scores for digits 0, 1 and 2 into positive probabilities that sum to one. Build the exponentiation, total and division yourself.",{scores:"Scores for digits 0, 1 and 2"},[{scores:[-2,1,3]},{scores:[0,2,1]},{scores:[-1,-1,-1]}],div(op("exp",[s("scores")]),total(op("exp",[s("scores")])))),
  build("bagging","Three fitted models estimate the position of the same object. Build an equal-weight average using the tools from statistics.",{predictions:"Predictions from three models"},[{predictions:[2,4,9]},{predictions:[8,2,5]},{predictions:[3,6,9]}],average(s("predictions"))),
  build("kernel-trick","Can a distance feature separate the inner and outer groups? Return 1 for a point whose squared distance from the centre exceeds 2, and 0 otherwise. Construct that feature before making the decision.",{point:"Point coordinates"},[{point:[0,1]},{point:[0,-1]},{point:[2,0]},{point:[-2,0]},{point:[1.5,1.5]}],op("greater",[total(square(s("point"))),c(2)]),undefined,"This explicitly constructs a feature. The kernel trick computes feature-space comparisons without explicitly constructing every feature."),
  build("kernel-ridge","This toy kernel matrix is the identity. With a ridge penalty of 1, build the operation that solves each independent coefficient equation.",{targets:"Training targets",penalty:"Ridge penalty"},[{targets:[2,4,-2],penalty:1},{targets:[3,-1,5],penalty:1}],div(s("targets"),add(c(1),s("penalty"))),undefined,"Elementwise division is valid here because the kernel matrix is the identity. A general kernel requires solving the coupled linear system."),
  build("markov-chains","What is the probability that the next letter is a vowel or consonant? Apply the transition table to the current distribution. Rows describe the current category and columns describe the next, always ordered vowel then consonant.",{distribution:"Current vowel/consonant probabilities",transitions:"Vowel/consonant transition rows"},[{distribution:[1,0],transitions:[[.8,.2],[.6,.4]]},{distribution:[.25,.75],transitions:[[.8,.2],[.6,.4]]}],op("matvec",[op("transpose",[s("transitions")]),s("distribution")])) ,
  build("neurons-and-activations","Can the neuron recognise when the left sensor is at least two brightness units above the right? Choose the weights, bias and threshold activation needed. Return 1 when that light pattern is present and 0 otherwise.",{leftLight:"Left light sensor",rightLight:"Right light sensor"},[{leftLight:1,rightLight:3},{leftLight:3,rightLight:1},{leftLight:2,rightLight:1},{leftLight:4,rightLight:1},{leftLight:2,rightLight:2},{leftLight:4,rightLight:2},{leftLight:3,rightLight:2},{leftLight:3,rightLight:3}],op("gate",[add(add(mul(s("leftLight"),c(1)),mul(s("rightLight"),c(-1))),c(-2)),c(0)]),"A positive left weight and a negative right weight make the neuron respond to contrast. The bias requires a sufficient difference before the threshold activation reports the pattern. Different constructions can produce the same valid rule.","The readings use an invented brightness scale shared by both sensors. This recognises one simple pattern; a learned visual recogniser needs many detectors and training examples."),
  build("dense-layers","What can two neurons tell us about the same light pattern? Return the combined brightness first and the left-minus-right contrast second. Keep both responses together in that order.",{leftLight:"Left light sensor",rightLight:"Right light sensor"},[{leftLight:1,rightLight:3},{leftLight:3,rightLight:2},{leftLight:4,rightLight:1}],pack(add(s("leftLight"),s("rightLight")),sub(s("leftLight"),s("rightLight")))),
  build("loss-functions","Build mean squared error from the model predictions and their known answers. The result must not let positive and negative mistakes cancel.",{predictions:"Predictions",targets:"Answers"},[{predictions:[1,2,5],targets:[3,2,3]},{predictions:[2,6,1],targets:[3,3,3]}],average(square(sub(s("predictions"),s("targets"))))),
  build("backpropagation","The prediction is weight times input. For half the squared error, build the gradient with respect to the weight by following the two local effects.",{input:"Input",weight:"Current weight",target:"Target"},[{input:2,weight:1,target:5},{input:3,weight:2,target:4}],mul(sub(mul(s("input"),s("weight")),s("target")),s("input"))),
  build("training-a-network","Build one supervised update for a single linear neuron using half the squared error. Find the prediction, error and weight gradient, then subtract the learning-rate-scaled gradient from the old weight.",{input:"Training input",weight:"Current weight",target:"Training label",rate:"Learning rate"},[{input:2,weight:1,target:5,rate:.1},{input:3,weight:2,target:4,rate:.1}],sub(s("weight"),mul(s("rate"),mul(sub(mul(s("input"),s("weight")),s("target")),s("input"))))),
  build("dropout","The supplied mask contains 1 for surviving activations and 0 for dropped activations. Build inverted dropout using a keep probability of one half.",{activations:"Activations",mask:"Sampled mask"},[{activations:[2,4,6],mask:[1,0,1]},{activations:[1,3,5],mask:[0,1,1]}],div(mul(s("activations"),s("mask")),c(.5))),
  build("normalisation-layers","Build the normalised values for one example from its mean and population variance. The same construction must work for a different offset and scale.",{row:"One example's activations"},[{row:[1,3,5]},{row:[10,14,18]}],div(sub(s("row"),average(s("row"))),op("root",[average(square(sub(s("row"),average(s("row")))))])),undefined,"These rows have nonzero variance. The challenge omits learned scale, shift and epsilon to focus on the normalisation itself."),
  build("recurrent-layers","How much sound energy has arrived so far? Build a running total from the energy measured in each audio frame. Return the total after every frame, preserving its order.",{sequence:"Energy per audio frame"},[{sequence:[1,2,1,3]},{sequence:[2,0,3,1]}],op("cumulative",[s("sequence")])) ,
  build("residual-connections","Keep the original representation and add the layer's correction. Test the example whose correction is zero as well as the nonzero examples.",{input:"Incoming representation",correction:"Layer correction"},[{input:[2,3],correction:[0,0]},{input:[1,-2],correction:[.5,1]}],add(s("input"),s("correction"))),
  build("radial-basis-networks","Build a detector centred at 2 with width 1. Its response should be 1 at the centre and fall smoothly with squared distance.",{reading:"Input coordinate"},[{reading:0},{reading:1},{reading:2},{reading:3.5}],op("exp",[mul(c(-.5),square(sub(s("reading"),c(2))))])),
  build("self-organising-map","The winning prototype has already been selected. Build its update so it moves halfway towards the incoming point.",{prototype:"Winning prototype",point:"Incoming point"},[{prototype:[0,2],point:[4,6]},{prototype:[2,4],point:[6,0]}],add(s("prototype"),mul(c(.5),sub(s("point"),s("prototype"))))),
  build("hebbian-pca","Build Oja's weight change at learning rate 0.1. Start by finding the output from the current weight vector and input, then include the stabilising subtraction.",{weights:"Current weights",input:"Input vector"},[{weights:[.6,.8],input:[1,2]},{weights:[.6,.8],input:[2,1]}],mul(c(.1),sub(mul(op("dot",[s("weights"),s("input")]),s("input")),mul(square(op("dot",[s("weights"),s("input")])),s("weights"))))),
  build("distance-and-similarity","Build cosine similarity from a dot product and both vector lengths. The longer copy should not receive a larger similarity just because it is longer.",{a:"Query term vector",b:"Document term vector"},[{a:[1,2],b:[2,4]},{a:[1,0],b:[0,1]},{a:[2,1],b:[1,2]}],div(op("dot",[s("a"),s("b")]),mul(norm(s("a")),norm(s("b"))))),
  build("pointwise-mutual-information","Build the independence baseline from the two marginal probabilities. Compare the observed joint probability with that baseline, then report the ratio in bits.",{a:"First word probability",b:"Second word probability",joint:"Observed word-pair probability"},[{a:.2,b:.25,joint:.1},{a:.2,b:.4,joint:.04}],op("log2",[div(s("joint"),mul(s("a"),s("b")))])),
  build("random-indexing","Build the representation from the supplied context index vectors. Both observations must contribute, including any cancellation.",{a:"First context vector",b:"Second context vector"},[{a:[1,0,-1],b:[0,1,-1]},{a:[0,1,-1],b:[1,0,1]}],add(s("a"),s("b"))),
  build("fasttext","Combine the word entry with both subword vectors. This exercise uses an unnormalised sum.",{word:"Word vector",first:"First subword vector",second:"Second subword vector"},[{word:[1,0],first:[0,2],second:[1,1]},{word:[0,0],first:[0,1],second:[1,1]}],add(add(s("word"),s("first")),s("second"))),
  build("glove","Construct the squared discrepancy between the fitted word-pair score and its log-count target. The score needs the dot product and both biases.",{word:"Word vector",context:"Context vector",biases:"Word and context biases",count:"Co-occurrence count"},[{word:[1,0],context:[2,1],biases:[.1,.2],count:4},{word:[1,2],context:[0,1],biases:[0,.5],count:9}],square(sub(add(op("dot",[s("word"),s("context")]),total(s("biases"))),op("log",[s("count")])))),
  build("positional-encoding","The same token appears at different positions. Preserve its embedding and add the supplied position information.",{token:"Token embedding",position:"Position vector"},[{token:[1,2],position:[0,1]},{token:[1,2],position:[1,0]}],add(s("token"),s("position"))),
  build("attention","Build attention from its parts. Compare the query with every key, scale the scores by the square root of the key dimension, turn them into shares, and use those shares to combine the values.",{query:"Translation step query",keys:"Keys for the / red / door",values:"One value coordinate per source word",dimension:"Key dimension"},[{query:[2,0],keys:[[0,0],[1,0],[0,1]],values:[0,10,2],dimension:2},{query:[0,2],keys:[[0,0],[1,0],[0,1]],values:[0,10,2],dimension:2}],op("dot",[op("softmax",[div(op("matvec",[s("keys"),s("query")]),op("root",[s("dimension")]))]),s("values")])),
  build("sampling-and-temperature","Build the probability distribution from the model's logits and a temperature. The temperature must change the scores before softmax.",{scores:"Model logits",temperature:"Temperature"},[{scores:[2,1,0],temperature:2},{scores:[2,1,0],temperature:.5}],op("softmax",[div(s("scores"),s("temperature"))])),
  build("low-rank-adaptation","Build the adapter's contribution using two narrow matrices, then add it to the frozen projection. The matrices here use column-vector convention.",{input:"Input vector",base:"Frozen projection",down:"Narrow down projection",up:"Up projection"},[{input:[1,2],base:[[1,0],[0,1]],down:[[1,-1]],up:[[2],[1]]},{input:[3,1],base:[[1,0],[0,1]],down:[[1,-1]],up:[[2],[1]]}],add(op("matvec",[s("base"),s("input")]),op("matvec",[s("up"),op("matvec",[s("down"),s("input")])]))),
];

BUILDS.push(...moreBuilds(build),...textBuilds(build),...modernBuilds(build));
export const buildById=Object.fromEntries(BUILDS.map(b=>[b.id,b]));
export const firstUse:Record<string,string>={constant:"workshop-guide",multiply:"workshop-guide"};
for(const lesson of labLessons) { const build=buildById[lesson.id]; if(build)for(const tool of expressionTools(build.recipe).filter(t=>!t.startsWith("source:")))firstUse[tool]??=lesson.id; }
// Later lessons can use the operation the reader previously constructed from smaller pieces.
firstUse.mean="statistics";
firstUse.dot="linear-algebra";
firstUse.softmax="multiclass-classification";
