// These explanations describe the construction tasks, which can isolate a
// different part of a method from the lesson's other demonstrations.
export const constructionTitles:Record<string,string> = {
  "statistics":"What do the weekly records tell us?",
  "linear-algebra":"One price list, a whole page of purchases",
  "calculus":"How fast was the traveller moving?",
  "simple-linear-regression":"Fit a line to the observations",
  "held-out-evaluation":"Check predictions against reserved observations",
  "logistic-regression":"Which components need inspection?",
  "pca":"Describe the cloud along its main direction",
  "multiple-polynomial-regression":"When does warmer help the process?",
  "distance-metrics":"Compare people on a common scale",
  "multiclass-classification":"Which digit do the scores support?",
  "kernel-trick":"Separate the inner and outer groups",
  "markov-chains":"Predict the next letter's category",
  "neurons-and-activations":"Build a light-pattern detector",
  "loss-functions":"Measure the prediction errors",
  "self-organising-map":"Move a prototype towards an observation",
  "k-means":"Recalculate the group centres",
  "template-matching":"Locate the reference pattern",
  "pipelines":"Keep preparation tied to the training data",
  "embedding-layers":"Retrieve and combine the word vectors",
  "kernel-ridge":"Keep the kernel coefficients in check",
  "training-a-network":"Teach the weight from one mistake",
  "attention":"Let the query choose what contributes",
  "decision-trees":"Classify a specimen with two questions",
  "keypoints-and-descriptors":"Is the closest match convincing?",
  "haar-cascades":"Give a window two checks to pass",
  "feature-importance":"Does the model depend on height?",
  "u-net":"Bring the missing detail back",
  "learning-boundaries-from-examples":"Turn boundary probabilities into pieces",
  "greedy-coverage":"Choose the piece that covers more new ground",
  "generative-adversarial-networks":"Find out what the critic rewards",
  "diffusion-models":"Mix a clean signal with noise",
  "reinforcement-learning":"Learn what an action was worth",
  "evaluating-generative-models":"Can a good average hide repetition?",
};
export const constructionExplanations:Record<string,string> = {
  "linear-algebra": "Each row of the purchase matrix belongs to one customer. The columns keep bread and milk in the same order as the prices. Multiplying matching quantities and prices, then adding, gives one bill. That is a dot product. Matrix-vector multiplication repeats it for every row and keeps the bills in customer order. The same arrangement works for a shorter customer list or new prices. In a model, the rows can instead hold observations and the vector can hold the weights used to calculate a prediction for each one.",
  "judging-a-classifier": "The denominator includes every reported light, both true detections and false alarms. The numerator keeps only the true detections. This tells us how trustworthy a positive report was, but the missing-light count would be needed to measure recall.",
  "polynomial-features": "The squared reading grows differently from the original reading. A model can give each its own coefficient, so its prediction can change at different rates across the input range. We have constructed one feature, not fitted its coefficient.",
  "multiple-polynomial-regression": "The product term changes the contribution of temperature depending on pressure. At the low pressure in these examples, warming lowers the predicted yield. At the higher pressure, warming raises it. Separate temperature and pressure terms alone could not reverse that effect.",
  "distance-metrics": "Taking absolute values keeps both coordinate differences positive before adding them. The inputs are standardised, so centimetres cannot overwhelm kilograms merely through their numerical size. Manhattan distance is one choice; it does not account for correlations between measurements.",
  "multiclass-classification": "Exponentiation makes each digit's contribution positive. Dividing by their shared total turns them into probabilities that sum to one. A digit's probability depends on its score relative to the competing digits, not just on its own score.",
  "kernel-trick": "Points on opposite sides of the centre can have the same squared distance. The new feature therefore groups nearby-to-centre points together and puts outer points above the cutoff. The separation becomes simple because we changed what the coordinate measures.",
  "markov-chains": "Each possible current category contributes its probability to the next-category prediction through its own transition row. Combining those contributions gives the next vowel/consonant distribution. The example assumes the next category depends only on the current one.",
  "dense-layers": "The same two light readings feed both neurons, but the weights give each neuron a different job. Adding measures total brightness; subtracting measures contrast. Keeping both outputs gives the next layer information that either response alone would lose.",
  "logistic-regression": "The sigmoid turns a score into a value between zero and one. The threshold then makes a decision from that probability. Keeping these as separate pieces lets us change the decision rule without changing the probability calculation.",
  "centring-on-the-mean": "The training mean supplies a reference point. Subtracting it tells us how far a new reading lies above or below that reference. The new reading must not move the reference point we learned from training.",
  "the-standard-score": "Centring tells us which side of the training mean a reading falls on. Dividing by the training standard deviation also tells us how large that difference is relative to the spread of the training readings.",
  "feature-scaling": "Changing units changes the numbers without changing the person's height. The same conversion belongs on every observation. A model comparing several measurements needs their units and scales to be handled consistently.",
  "gradient-descent-regression": "The gradient tells us which direction increases the loss locally. Subtracting a scaled gradient moves in the other direction. The learning rate controls the size of that move; this particular rate is not suitable for every loss surface.",
  "training-a-network": "The label gives us an error, the gradient tells us how the weight contributed to it, and the update changes the weight. This is one training step. Training repeats these operations over examples and checks performance on separate validation data.",
  "distance-and-similarity": "The dot product depends on both direction and length. Dividing by both lengths removes the size contribution. Matching directions, perpendicular directions and partially matching directions therefore give different results even when the vectors have different magnitudes.",
  "glove": "The word and context vectors produce a shared score, while the biases account for tendencies of the individual words. Comparing this score with the log count measures one pair's discrepancy. The full GloVe objective also weights these discrepancies by frequency.",
  "attention": "The query changes how strongly each key matches. Softmax turns those comparisons into nonnegative shares, and the final weighted sum uses those shares to combine the values. Changing the query can change the mixture even when the keys stay fixed.",
  "sampling-and-temperature": "Temperature changes the gaps between the scores before they become probabilities. A higher temperature spreads the probability more evenly; a lower one concentrates it on the largest scores. Drawing a token is a separate operation.",
  "k-nearest-neighbours": "Distances tell us which stored examples are nearby, but their labels tell us which class to predict. Keeping the row indices attached to the labels makes the vote depend on the selected neighbours rather than on the order of the table.",
  "decision-trees": "Each measurement question produces a yes or no result. Class 1 requires both answers to be yes. This constructs a fixed two-condition decision rule; learning a tree would also involve choosing questions from labelled specimens.",
  "random-forests": "A row can appear more than once in a bootstrap sample, and the two trees can see different rows and features. These differences help produce varied trees. We have prepared their inputs here; fitting the trees and combining their predictions are later steps.",
  "k-means": "The mean minimises the total squared distance to the points in one assigned group. We have rebuilt the centres from the current groups. K-means next assigns points to their nearest updated centre and repeats.",
  "keypoints-and-descriptors": "Being the closest match is less convincing when another candidate is almost as close. Comparing the first two distances lets us reject that ambiguity. A full image matcher also checks whether the accepted correspondences agree geometrically.",
  "haar-cascades": "Both conditions must hold for a window to survive. A deployed cascade can stop after an early rejection to save work. This construction calculates both tests so you can inspect their separate effects; it does not demonstrate that speed saving.",
  "hopfield-network": "The other bits cast weighted votes for the bit being repaired. A zero diagonal weight prevents that bit from reinforcing its own corrupted value. We have performed one local update, not guaranteed recovery of every corrupted pattern.",
  "restricted-boltzmann-machine": "The visible values determine hidden probabilities. Comparing those probabilities with random draws creates a sampled hidden state, which supplies a reconstruction through the transposed weights. Training additionally compares data-driven and model-driven statistics.",
  "learning-the-metric-itself": "The loss asks for the matching example to be closer than the nonmatching example by a margin. Once that condition holds, the loss stops at zero. Training would use its gradient to change the representation; this construction measures the current violation.",
  "bytes-and-characters": "UTF-8 represents different characters with different numbers of bytes. Counting the encoded bytes therefore answers a different question from counting the characters in the text. Neither necessarily counts the visible symbols a reader perceives.",
  "splitting-on-spaces": "The count comes from the nonempty pieces, so extra whitespace does not create extra words. This treatment discards the original spacing. That is acceptable for this counter, but insufficient for reconstructing the original text exactly.",
  "segmenting-with-a-hidden-model": "The supplied state path says which characters end words. Turning those states into boundaries connects the model's output to readable pieces. Choosing the state path itself requires the transition and emission scores explained in the lesson.",
  "learning-boundaries-from-examples": "The detector supplies probabilities, while the cutoff turns them into boundary decisions. The cutting operation then applies those decisions to the original characters. A detector's usefulness still depends on its labelled training examples and segmentation convention.",
  "embedding-layers": "An ID selects a row; its numeric size is not a feature measurement. The average then combines the selected rows, including repeated selections. Training can change these embedding rows so that their values become useful to the model.",
  "word2vec": "The observed and contrasting pairs need opposite treatment. The loss becomes smaller when the observed pair receives a high probability and the contrasting pair receives a low one. Repeated gradient updates use this pressure to shape the vectors.",
  "paragraph-vectors": "The prediction error changes the document vector while the word-prediction weight stays fixed. Repeating this process can infer a representation for a new document in the space learned during training. Here we have built one update.",
  "autoencoders": "The single encoded coordinate keeps the average but loses the difference between the two inputs. The decoder can reconstruct equal coordinates exactly. The second example exposes information that this bottleneck cannot preserve.",
  "generative-adversarial-networks": "The generator creates a value and the discriminator judges it. The generator's loss becomes smaller when the discriminator gives that generated value a higher probability of being real. A full GAN trains both models alternately; this construction calculates one objective with fixed weights.",
  "diffusion-models": "The two branches control how much signal and noise reach the result. Their square-root scaling gives the intended variance contributions when signal and noise are independent. We have built forward noising; learning to reverse it is the next part of diffusion modelling.",
  "reinforcement-learning": "The observed reward and discounted best next-state value form a new target. The learning rate controls how far the current estimate moves towards it. Repeating such updates can improve action values; one update alone is not a learned policy.",
  "retrieval-augmented-generation": "Similarity selects a document, and the corresponding text becomes part of the model's context. Keeping the vector and text rows aligned is essential. We have prepared evidence for generation; the generator must still use it faithfully.",
  "evaluating-generative-models": "A high quality average can hide repetition. Reporting a separate diversity measurement makes that weakness visible. These small checks illustrate why one score is insufficient; real evaluations need representative examples and measures suited to the task.",
};
