import type { Data, Tool } from "./engine";
import { vector,matrix,scalar,list,text,mean,softmax,map } from "./tools";
const tool=(title:string,why:string,inputs:string[],run:Tool["run"],settings?:Tool["settings"]):Tool=>({title,why,inputs,run,settings});
const number=(key:string,label:string,initial=1)=>({key,label,initial,min:0,max:20,step:1});
const string=(key:string,label:string,initial="")=>({key,label,initial});
function dictionary(x:Data):Record<string,Data>{if(!x||Array.isArray(x)||typeof x!=="object")throw Error("This input needs a lookup table with named entries.");return x;}
function pieces(value:Data):string[]{return list(value).map(text);}
function segment(sentence:string,vocabulary:Record<string,Data>,weighted:boolean,continuations=false):string[]{
  if(!weighted){let at=0;const result:string[]=[];while(at<sentence.length){const options=Object.keys(vocabulary).filter(w=>continuations?(at===0?!w.startsWith("##"):w.startsWith("##")):true).map(w=>({entry:w,piece:w.replace(/^##/,"")})).filter(w=>w.piece&&sentence.startsWith(w.piece,at)).sort((a,b)=>b.piece.length-a.piece.length);if(!options.length)throw Error(`The vocabulary cannot cover the text at position ${at}.`);result.push(options[0].entry);at+=options[0].piece.length;}return result;}

  const routes:Array<{cost:number;pieces:string[]}|undefined>=Array(sentence.length+1);routes[0]={cost:0,pieces:[]};
  for(let at=0;at<sentence.length;at++){const previous=routes[at];if(!previous)continue;for(const [piece,cost] of Object.entries(vocabulary)){if(!piece||!sentence.startsWith(piece,at))continue;const end=at+piece.length,candidate=previous.cost+scalar(cost);if(!routes[end]||candidate<routes[end]!.cost)routes[end]={cost:candidate,pieces:[...previous.pieces,piece]};}}
  if(!routes[sentence.length])throw Error("No complete route through the vocabulary covers this text.");return routes[sentence.length]!.pieces;
}
function windows(image:number[][],size:number,stride=1){if(!Number.isInteger(size)||size<1||size>Math.min(image.length,image[0].length)||!Number.isInteger(stride)||stride<1)throw Error("Choose a window and stride that fit the image.");const out:number[][]=[];for(let r=0;r<=image.length-size;r+=stride)for(let c=0;c<=image[0].length-size;c+=stride)out.push(image.slice(r,r+size).flatMap(row=>row.slice(c,c+size)));return out;}

export const EXTRA_TOOLS:Record<string,Tool>={
  maskScores:tool("Mask unavailable scores","Replaces disallowed scores with a very negative value before softmax. These examples use -1 billion so the exponential contribution rounds to zero.",["Score vector","Visibility mask"],([scores,mask])=>{const xs=vector(scores),m=vector(mask);if(xs.length!==m.length)throw Error("The visibility mask needs one entry per score.");return xs.map((x,i)=>m[i]?x:-1e9);}),
  rowPick:tool("Read each labelled probability","Retrieves the requested class entry from each probability row.",["Probability rows","Class IDs"],([rows,labels])=>{const data=matrix(rows),ids=vector(labels);if(data.length!==ids.length)throw Error("Each row needs one class ID.");return data.map((r,i)=>{if(r[ids[i]]===undefined)throw Error("A class ID is outside its probability row.");return r[ids[i]];});}),
  unique:tool("Keep distinct items","Keeps the first copy of each distinct item. Compare the count with the original count to detect repetition.",["Items"],([xs])=>{const seen=new Set<string>();return list(xs).filter(x=>{const k=JSON.stringify(x);if(seen.has(k))return false;seen.add(k);return true;});}),
  lengths:tool("Count each group","Returns one count for each list, preserving the order of the groups.",["Groups"],([x])=>list(x).map(group=>list(group).length)),
  maximum:tool("Largest value","Finds the largest number in a list, keeping the value rather than its position.",["Numbers"],([x])=>Math.max(...vector(x))),
  minimum:tool("Smallest value","Finds the smallest number in a list.",["Numbers"],([x])=>Math.min(...vector(x))),
  sign:tool("Sign of a value","Produces -1 for negative values and 1 for nonnegative values in this binary-state convention.",["Values"],([x])=>map(x,n=>n<0?-1:1)),
  rank:tool("Rank from smallest","Returns the indices in ascending score order. The original values remain available on another wire.",["Scores"],([x])=>vector(x).map((_,i)=>i).sort((a,b)=>vector(x)[a]-vector(x)[b])),
  gather:tool("Gather selected entries","Reads the entries at a list of indices. Repeated indices deliberately repeat the same example.",["Data table","Indices"],([x,i])=>vector(i).map(k=>{if(!Number.isInteger(k)||list(x)[k]===undefined)throw Error("A selected index does not exist in this table.");return list(x)[k];})),
  columnmean:tool("Mean of each column","Combines examples while keeping the feature columns separate.",["Example rows"],([x])=>{const rows=matrix(x);return rows[0].map((_,i)=>mean(rows.map(r=>r[i])));}),
  columnshift:tool("Subtract a vector from every row","Uses one reference value per column, applying the same reference to every example.",["Rows","Reference vector"],([x,v])=>{const ref=vector(v);return matrix(x).map(r=>{if(r.length!==ref.length)throw Error("The reference needs one entry per column.");return r.map((n,i)=>n-ref[i]);});}),
  rowshift:tool("Subtract each row's reference","Uses a different reference for each row, subtracting it from every entry in that row.",["Rows","Row reference values"],([x,v])=>{const refs=vector(v),rows=matrix(x);if(refs.length!==rows.length)throw Error("Supply one reference per row.");return rows.map((r,i)=>r.map(n=>n-refs[i]));}),
  rowsoftmax:tool("Softmax within each row","Gives each query its own distribution over keys, without mixing different queries' totals.",["Rows of scores"],([x])=>matrix(x).map(softmax)),
  thresholdRows:tool("Keep rows with a label","Selects rows whose supplied labels match the requested group. The labels and rows must correspond.",["Rows","Group labels"],([rows,labels],s)=>{const xs=list(rows),ys=vector(labels);if(xs.length!==ys.length)throw Error("Each row needs one label.");return xs.filter((_,i)=>ys[i]===Number(s.group));},[number("group","Group",0)]),
  windows:tool("Slide a square window","Extracts every image window in row order. The stride decides how far the window moves between positions.",["Image"],([x],s)=>windows(matrix(x),Number(s.size),Number(s.stride)),[number("size","Window size",1),number("stride","Stride",1)]),
  rowmax:tool("Maximum in each window","Keeps the strongest response from each row or flattened image window.",["Windows"],([x])=>matrix(x).map(r=>Math.max(...r))),
  upsample:tool("Repeat pixels","Enlarges a small map by repeating each pixel in both directions. It cannot recreate detail that was discarded earlier.",["Small map"],([x],s)=>{const factor=Number(s.factor),rows=matrix(x);if(!Number.isInteger(factor)||factor<1||factor>20||rows.length*rows[0].length*factor*factor>10000)throw Error("Choose a whole-number scale from 1 to 20 and a resulting map of at most 10,000 pixels.");return rows.flatMap(r=>Array.from({length:factor},()=>r.flatMap(n=>Array(factor).fill(n))));},[number("factor","Scale factor",1)]),
  reshape:tool("Arrange rows","Rearranges a flat list into rows of a chosen width, without changing or discarding values.",["Flat values"],([x],s)=>{const xs=list(x),cols=Number(s.columns);if(!Number.isInteger(cols)||cols<1||xs.length%cols)throw Error("The row width must divide the number of values exactly.");return Array.from({length:xs.length/cols},(_,i)=>xs.slice(i*cols,(i+1)*cols));},[number("columns","Values per row",1)]),
  concatenate:tool("Join lists","Places the second list after the first, preserving every entry and its order.",["First list","Second list"],([a,b])=>[...list(a),...list(b)]),
  mask:tool("Select real entries","Keeps only entries whose mask is 1. A padding entry should have mask 0.",["Entries","Keep mask"],([a,b])=>{const xs=list(a),ms=vector(b);if(xs.length!==ms.length)throw Error("The mask needs one entry per item.");return xs.filter((_,i)=>ms[i]===1);}),
  words:tool("Split whitespace runs","Separates words at runs of whitespace, discarding those separators. Exact spacing is lost.",["Text"],([x])=>text(x).trim().split(/\s+/u).filter(Boolean)),
  characters:tool("Read Unicode code points","Separates a string into Unicode code points. A visible character can still contain more than one code point.",["Text"],([x])=>Array.from(text(x))),
  codes:tool("Code-point numbers","Reads the Unicode code-point value of each input character. These numbers are not UTF-8 bytes.",["Characters"],([x])=>pieces(x).map(c=>c.codePointAt(0)!)),
  utf8:tool("Encode UTF-8","Encodes a string into bytes. A single character can contribute several bytes.",["Text"],([x])=>Array.from(new TextEncoder().encode(text(x)))),
  decodeUtf8:tool("Decode UTF-8","Reconstructs text from a valid UTF-8 byte sequence.",["Bytes"],([x])=>new TextDecoder("utf-8",{fatal:true}).decode(new Uint8Array(vector(x)))),
  vocabulary:tool("Vocabulary lookup","Uses each piece as a key in a supplied vocabulary. Repeated pieces keep the same ID.",["Token pieces","Vocabulary"],([xs,table])=>pieces(xs).map(piece=>{const value=dictionary(table)[piece];if(value===undefined)throw Error(`No vocabulary entry for ${piece}.`);return value;})),
  lower:tool("Lowercase text","Combines upper- and lowercase spellings under one form. Use it only if losing that distinction suits the task.",["Text"],([x])=>text(x).toLowerCase()),
  punctuation:tool("Separate punctuation","Groups letters and numbers while preserving each punctuation mark as its own piece. This is a small Unicode-aware rule, not a full language segmenter.",["Text"],([x])=>text(x).match(/[\p{L}\p{N}]+|[^\s\p{L}\p{N}]/gu)??[]),
  pattern:tool("Group text by kind","Groups an optional leading space with a letter run, keeps digit runs together, and separates other symbol runs. This is the lesson's teaching pattern.",["Text"],([x])=>text(x).match(/ ?\p{L}+|\p{N}+|[^\s\p{L}\p{N}]+|\s+/gu)??[]),
  cut:tool("Cut at labelled boundaries","Ends a piece wherever the corresponding after-character label is 1. Always preserves the full input.",["Text","After-character labels"],([x,labels])=>{const chars=Array.from(text(x)),bs=vector(labels);if(bs.length!==chars.length)throw Error("Supply one boundary label per character.");const out:string[]=[];let current="";chars.forEach((c,i)=>{current+=c;if(bs[i]||i===chars.length-1){out.push(current);current="";}});return out;}),
  endStates:tool("Read word-end states","Converts E (end) and S (single) states into after-character boundaries; B and M keep a word open.",["State sequence"],([x])=>pieces(x).map(s=>Number(s==="E"||s==="S"))),
  merge:tool("Merge an adjacent pair","Combines every non-overlapping occurrence of one named pair. Repeated merge machines can apply a learned merge order.",["Pieces"],([x],s)=>{const xs=pieces(x),out:string[]=[];for(let i=0;i<xs.length;i++){if(xs[i]===s.left&&xs[i+1]===s.right){out.push(xs[i]+xs[i+1]);i++;}else out.push(xs[i]);}return out;},[string("left","Left piece"),string("right","Right piece")]),
  longest:tool("Longest dictionary match","At each position, takes the longest vocabulary piece that matches. It makes a local choice without comparing complete paths.",["Text","Vocabulary"],([x,v])=>segment(text(x),dictionary(v),false)),
  wordpiece:tool("WordPiece continuation match","Matches a starting entry, then entries marked with ## for continuations. The markers name vocabulary entries, not extra input characters.",["Text","Vocabulary"],([x,v])=>segment(text(x),dictionary(v),false,true)),
  bestPath:tool("Cheapest complete word path","Keeps the cheapest route to each text position and extends it with matching pieces. This is dynamic programming over the supplied costs.",["Text","Piece costs"],([x,v])=>segment(text(x),dictionary(v),true)),
  negativeLogs:tool("Probabilities to path costs","Turns each positive piece probability into a negative natural-log cost. Adding these costs compares products of probabilities.",["Probability table"],([x])=>Object.fromEntries(Object.entries(dictionary(x)).map(([k,v])=>[k,-Math.log(scalar(v))]))),
  replace:tool("Replace a literal string","Replaces every occurrence of one literal piece of text with another. The choice can preserve a boundary explicitly or discard information.",["Text"],([x],s)=>{if(!s.find)throw Error("Choose a nonempty string to replace.");return text(x).split(String(s.find)).join(String(s.with));},[string("find","Find"),string("with","Replace with")]),
  splitLiteral:tool("Split at a literal separator","Cuts at one exact separator. Unlike splitting whitespace runs, repeated separators can leave empty pieces.",["Text"],([x],s)=>text(x).split(String(s.separator)),[string("separator","Separator"," ")]),
  prefix:tool("Prefix text","Adds a fixed marker before a string.",["Text"],([x],s)=>String(s.prefix)+text(x),[string("prefix","Marker")]),
  grams:tool("Overlapping windows","Collects consecutive groups of items, moving one position at a time. The middle items can belong to several windows.",["Items"],([x],s)=>{const xs=list(x),n=Number(s.size);if(!Number.isInteger(n)||n<1)throw Error("A window needs at least one item.");return xs.slice(0,Math.max(0,xs.length-n+1)).map((_,i)=>xs.slice(i,i+n));},[number("size","Items per window",1)]),
  chunks:tool("Non-overlapping groups","Groups neighbouring items into fixed-width chunks. Each item appears once, including any shorter final chunk.",["Items"],([x],s)=>{const xs=list(x),n=Number(s.size);if(!Number.isInteger(n)||n<1)throw Error("A group needs at least one item.");return Array.from({length:Math.ceil(xs.length/n)},(_,i)=>xs.slice(i*n,(i+1)*n));},[number("size","Items per group",1)]),
  suffix:tool("Rewrite an ending","Replaces a stated ending with another. This is one spelling rule, not a complete morphological analyser.",["Stem"],([x],s)=>{const value=text(x),ending=String(s.ending);if(!ending||!value.endsWith(ending))throw Error("The supplied stem does not have that ending.");return value.slice(0,-ending.length)+s.replacement;},[string("ending","Old ending"),string("replacement","New ending")]),
  join:tool("Join text pieces","Reconstructs text from pieces with a chosen separator.",["Pieces"],([x],s)=>pieces(x).join(String(s.separator)),[string("separator","Separator")]),
  tableReorder:tool("Move rows by token identity","Looks up each new vocabulary entry in the old vocabulary before copying its vector. This operation requires all entries to already exist.",["Old token order","Old vectors","New token order"],([old,rows,next])=>pieces(next).map(t=>{const i=pieces(old).indexOf(t);if(i<0)throw Error("This new token needs an initialised vector; it was absent from the old table.");return list(rows)[i];})),
  toyModel:tool("Fixed next-token model","Looks up the supplied score row for the final context ID. This tiny fixed table stands in for a trained language model.",["Context IDs","Score table"],([ids,table])=>{const last=vector(ids).at(-1)!;const row=list(table)[last];if(row===undefined)throw Error("The context ends with an ID outside this model's table.");return row;}),
  append:tool("Append one item","Adds the selected result to the end of an existing sequence.",["Sequence","New item"],([xs,x])=>[...list(xs),x]),
  causal:tool("Keep past and current positions","Returns an attention mask that allows positions no later than the query position. Future positions receive 0.",["Position indices","Query position"],([indices,p])=>vector(indices).map(i=>Number(i<=scalar(p)))),
};
