import { op,source as s,constant as c,type Expression } from "./engine";
type Builder=typeof import("./catalog").build;
const add=(a:Expression,b:Expression)=>op("add",[a,b]),sub=(a:Expression,b:Expression)=>op("subtract",[a,b]),mul=(a:Expression,b:Expression)=>op("multiply",[a,b]),div=(a:Expression,b:Expression)=>op("divide",[a,b]);
const total=(a:Expression)=>op("total",[a]),square=(a:Expression)=>op("square",[a]),mean=(a:Expression)=>div(total(a),op("count",[a]));
const log=(a:Expression)=>op("log",[a]),negative=(a:Expression)=>mul(c(-1),a),dot=(a:Expression,b:Expression)=>op("dot",[a,b]);
const normalized=op("rownorm",[s("states")]);
const attended=op("matmul",[op("rowsoftmax",[div(op("matmul",[normalized,op("transpose",[normalized])]),op("root",[c(2)]))]),normalized]);
const residual=add(s("states"),attended);
const retrieved=op("index",[s("documents"),op("argmin",[op("distances",[s("query"),s("vectors")])])]);
const rag=op("join",[op("pack",[s("question"),retrieved])],{separator:"\n"});
export function modernBuilds(build:Builder){return [
  build("latent-semantic-analysis","The supplied left singular vectors are ordered from strongest to weakest. Retain the first direction, then project the term-document matrix into that one-dimensional representation.",{directions:"Left singular vectors as columns",documents:"Term-document matrix"},[{directions:[[1,0],[0,1]],documents:[[3,4],[0,0]]},{directions:[[0,1],[1,0]],documents:[[0,0],[2,5]]}],op("matmul",[op("slice",[op("transpose",[s("directions")])],{start:0,end:1}),s("documents")]),undefined,"The SVD is supplied. This challenge builds truncation and projection; it does not find singular directions or train a language model."),
  build("word2vec","Build the negative-sampling loss for one observed word pair and one contrasting pair. The observed pair should receive a high sigmoid probability; the contrasting pair should receive a low one.",{word:"Centre-word vector",positive:"Observed context vector",negative:"Contrasting context vector"},[{word:[1,0],positive:[2,1],negative:[-1,1]},{word:[0,1],positive:[1,2],negative:[1,-2]}],negative(add(log(op("sigmoid",[dot(s("word"),s("positive"))])),log(op("sigmoid",[negative(dot(s("word"),s("negative")))]))))),
  build("paragraph-vectors","Infer a new document vector with one update. Keep the supplied word-prediction weight fixed. For a positive observed word, subtract the learning-rate-scaled sigmoid-loss gradient from the document vector.",{document:"Current document vector",weight:"Frozen word-prediction vector",rate:"Inference learning rate"},[{document:[0,0],weight:[1,2],rate:.1},{document:[1,0],weight:[1,2],rate:.1}],sub(s("document"),mul(s("rate"),mul(sub(op("sigmoid",[dot(s("document"),s("weight"))]),c(1)),s("weight"))))),
  build("transformer-blocks","Build this small pre-normalisation block. Normalise the token rows, use them as queries, keys and values for scaled attention, add the first residual, then normalise and apply the supplied feed-forward matrix with ReLU before adding the second residual.",{states:"Token states",feedforward:"Feed-forward matrix"},[{states:[[1,3],[4,2]],feedforward:[[1,0],[0,1]]},{states:[[2,4],[3,1]],feedforward:[[.5,0],[0,.5]]}],add(residual,op("relu",[op("matmul",[op("rownorm",[residual]),s("feedforward")])])),undefined,"This two-dimensional teaching block uses identity query, key and value projections and a single feed-forward matrix. Full transformer blocks use learned projections, multiple heads, and a larger feed-forward sublayer."),
  build("next-token-prediction","Build attention weights that cannot use future positions. Construct the visibility mask, apply it to the scores, then normalise the remaining scores.",{positions:"Key positions",query:"Current query position",scores:"Attention scores"},[{positions:[0,1,2,3],query:2,scores:[1,2,3,9]},{positions:[0,1,2,3],query:1,scores:[2,1,8,9]}],op("softmax",[op("maskScores",[s("scores"),op("causal",[s("positions"),s("query")])])])),
  build("autoregressive-generation","Use the fixed next-token table to predict from the last context ID. Choose the highest-scoring token and append it to the context. The next example begins with a different context.",{context:"Current context IDs",model:"Fixed next-token score table"},[{context:[0],model:[[0,3,1],[0,0,4],[5,0,0]]},{context:[0,1],model:[[0,3,1],[0,0,4],[5,0,0]]}],op("append",[s("context"),op("argmax",[op("toyModel",[s("context"),s("model")])])]),undefined,"This builds one greedy generation step with a tiny fixed model. Repeated generation feeds the growing context back through the same model; its weights do not update."),
  build("autoencoders","Send the input through a one-coordinate encoder and its decoder, then measure the reconstruction's mean squared error. Compare an input the bottleneck preserves with one it loses information from.",{input:"Input vector",encoder:"Encoder matrix",decoder:"Decoder matrix"},[{input:[2,2],encoder:[[.5,.5]],decoder:[[1],[1]]},{input:[1,3],encoder:[[.5,.5]],decoder:[[1],[1]]}],mean(square(sub(op("matvec",[s("decoder"),op("matvec",[s("encoder"),s("input")])]),s("input"))))),
  build("variational-autoencoders","Construct a latent sample from the mean, log variance and supplied standard-normal draw. Convert log variance to standard deviation before multiplying the noise.",{mean:"Latent mean",logVariance:"Latent log variance",noise:"Standard-normal draw"},[{mean:[1,2],logVariance:[0,0],noise:[.5,-1]},{mean:[0,1],logVariance:[1,-1],noise:[1,.5]}],add(s("mean"),mul(op("exp",[mul(c(.5),s("logVariance"))]),s("noise")))),
  build("generative-adversarial-networks","This toy generator multiplies noise by its weight. Pass that fake value through the frozen discriminator's linear score and sigmoid. Build the generator's non-saturating loss by taking the negative log of the discriminator's probability.",{noise:"Generator input",generator:"Generator weight",discriminator:"Frozen discriminator weight",bias:"Discriminator bias"},[{noise:1,generator:.5,discriminator:2,bias:-1},{noise:-1,generator:.5,discriminator:2,bias:-1}],negative(log(op("sigmoid",[add(mul(mul(s("noise"),s("generator")),s("discriminator")),s("bias"))]))),undefined,"This scalar construction isolates the generator's objective. A full GAN alternates discriminator and generator training and uses much larger models."),
  build("diffusion-models","Build one forward noising step. Scale the clean sample by the square root of alpha and the noise by the square root of one minus alpha, then combine them.",{clean:"Clean sample",noise:"Standard-normal noise draw",alpha:"Retained signal fraction"},[{clean:[1,0],noise:[0,1],alpha:.8},{clean:[0,1],noise:[1,0],alpha:.2}],add(mul(op("root",[s("alpha")]),s("clean")),mul(op("root",[sub(c(1),s("alpha"))]),s("noise")))),
  build("supervised-fine-tuning","Build the mean next-token loss over response positions only. Convert each score row to probabilities, read the labelled token's probability, and exclude prompt positions using the mask.",{scores:"Next-token score rows",labels:"Known next-token IDs",mask:"Response-position mask"},[{scores:[[3,1],[1,3],[2,0]],labels:[0,1,0],mask:[0,1,1]},{scores:[[1,3],[2,1]],labels:[1,0],mask:[0,1]}],mean(op("mask",[negative(log(op("rowPick",[op("rowsoftmax",[s("scores")]),s("labels")]))),s("mask")]))),
  build("reinforcement-learning","Build one Q-learning update from the observed reward and the best next-state action value. Use the supplied learning rate and discount, and return the updated current estimate.",{current:"Current Q estimate",reward:"Observed reward",next:"Next-state action values",rate:"Learning rate",discount:"Discount"},[{current:2,reward:1,next:[3,4],rate:.5,discount:.9},{current:1,reward:-1,next:[0,2],rate:.25,discount:.9}],add(s("current"),mul(s("rate"),sub(add(s("reward"),mul(s("discount"),op("maximum",[s("next")]))),s("current"))))),
  build("retrieval-augmented-generation","Find the closest document vector, retrieve that document's text, and join it with the question. The result is context for a later generation step.",{query:"Question vector",vectors:"Document vectors",documents:"Document texts",question:"Question text"},[{query:[1,0],vectors:[[1,0],[0,1]],documents:["The workshop opens at nine.","The roof is blue."],question:"When does the workshop open?"},{query:[0,1],vectors:[[1,0],[0,1]],documents:["The workshop opens at nine.","The roof is blue."],question:"What colour is the roof?"}],rag),
  build("evaluating-generative-models","Return two measurements together: the mean supplied quality score and the fraction of outputs that are distinct. A model that repeats one good output should expose that repetition.",{quality:"Quality scores",outputs:"Generated outputs"},[{quality:[.9,.9,.9],outputs:["red cat","red cat","red cat"]},{quality:[.8,.9,.7],outputs:["red cat","blue dog","green bird"]}],op("pack",[mean(s("quality")),div(op("count",[op("unique",[s("outputs")])]),op("count",[s("outputs")]))]),undefined,"These are illustrative quality and diversity checks. Distinct text alone does not establish useful diversity, and evaluating a real generative model requires task-specific evidence."),
];}