import { op,source as s,constant as c,type Expression } from "./engine";
type Builder=typeof import("./catalog").build;
const add=(a:Expression,b:Expression)=>op("add",[a,b]),sub=(a:Expression,b:Expression)=>op("subtract",[a,b]),mul=(a:Expression,b:Expression)=>op("multiply",[a,b]),div=(a:Expression,b:Expression)=>op("divide",[a,b]);
const square=(a:Expression)=>op("square",[a]),total=(a:Expression)=>op("total",[a]),mean=(a:Expression)=>div(total(a),op("count",[a]));
const norm=(a:Expression)=>op("root",[total(square(a))]),pack=(a:Expression,b:Expression)=>op("pack",[a,b]);
const image=[[0,0,0,0,0],[0,0,1,1,0],[0,0,1,0,0],[0,0,0,0,0],[0,0,0,0,0]];
export function moreBuilds(build:Builder){return [
  build("ridge-lasso","In this orthonormal toy problem, lasso shrinks each magnitude by the penalty and stops at zero. Build the shrinkage while preserving the original signs.",{coefficients:"Unpenalised coefficients",penalty:"Penalty"},[{coefficients:[2,.5,-3],penalty:1},{coefficients:[.2,-.5,4],penalty:1}],mul(op("sign",[s("coefficients")]),op("relu",[sub(op("absolute",[s("coefficients")]),s("penalty"))]))),
  build("k-nearest-neighbours","Find the three closest reference points, retrieve their labels, and use the majority vote for the query. A class of 1 needs at least half of the votes.",{query:"Unknown specimen measurements",references:"Reference specimen measurements",labels:"Known specimen classes"},[{query:[0,0],references:[[.1,0],[.2,0],[.3,0],[2,0],[3,0]],labels:[0,1,1,0,0]},{query:[3,0],references:[[.1,0],[.2,0],[.3,0],[2,0],[3,0]],labels:[0,1,1,0,0]}],op("gate",[mean(op("gather",[s("labels"),op("slice",[op("rank",[op("distances",[s("query"),s("references")])])],{start:0,end:3})])),c(.5)])),
  build("decision-trees","Which specimens belong to class 1? Our supplied tree requires a stem longer than 3 cm and a leaf narrower than 4 cm. Return 1 when both conditions hold and 0 otherwise.",{height:"Stem length (cm)",mass:"Leaf width (cm)"},[{height:2,mass:2},{height:5,mass:3},{height:6,mass:5},{height:3,mass:1}],mul(op("greater",[s("height"),c(3)]),op("greater",[c(4),s("mass")]))),
  build("random-forests","Prepare two different training views. Use each tree's bootstrap row indices, then retain its chosen feature columns. Return the two tables together.",{data:"Specimen measurement rows",a:"Tree A sample indices",b:"Tree B sample indices",fa:"Tree A feature indices",fb:"Tree B feature indices"},[{data:[[1,10],[2,20],[3,30]],a:[0,0,2],b:[1,2,1],fa:[0],fb:[1]},{data:[[4,40],[5,50],[6,60]],a:[2,0,2],b:[0,1,1],fa:[1],fb:[0]}],pack(op("transpose",[op("gather",[op("transpose",[op("gather",[s("data"),s("a")])]),s("fa")])]),op("transpose",[op("gather",[op("transpose",[op("gather",[s("data"),s("b")])]),s("fb")])])) ,undefined,"This constructs resampled training views. A full forest chooses candidate features again at each split and later combines fitted tree predictions."),
  build("k-means","The assignment step has supplied two groups. Build the new centre for each group by averaging its feature columns, then return both centres.",{points:"Point rows",groups:"Current group labels"},[{points:[[1,0],[3,2],[7,0],[9,2]],groups:[0,0,1,1]},{points:[[0,2],[4,4],[6,2],[10,4]],groups:[0,0,1,1]}],pack(op("columnmean",[op("thresholdRows",[s("points"),s("groups")],{group:0})]),op("columnmean",[op("thresholdRows",[s("points"),s("groups")],{group:1})]))),
  build("kernel-pca","Centre this kernel matrix. Remove each row's mean and each column's mean, then restore the overall mean once.",{kernel:"Kernel matrix"},[{kernel:[[1,2],[2,4]]},{kernel:[[1,3],[3,9]]}],add(op("columnshift",[op("rowshift",[s("kernel"),op("rowmean",[s("kernel")])]),op("columnmean",[s("kernel")])]),mean(op("flatten",[s("kernel")])))),
  build("filters-and-edges","Build an edge response from two neighbouring pixels. Flat brightness should produce zero; a brighter right pixel should produce a positive response.",{left:"Left brightness",right:"Right brightness"},[{left:0,right:0},{left:1,right:1},{left:.2,right:.8},{left:.8,right:.2}],sub(s("right"),s("left"))),
  build("template-matching","Find which 2 by 2 image window has the smallest squared difference from the reference patch. Return its window index in row order, counting from zero.",{image:"Camera image",template:"Flattened reference pixels"},[{image,template:[1,1,1,0]},{image,template:[0,0,0,0]}],op("argmin",[op("distances",[s("template"),op("windows",[s("image")],{size:2,stride:1})])])),
  build("histogram-of-oriented-gradients","Build the normalisation of a direction histogram. The brighter version of the same edge pattern should give the same result.",{histogram:"Gradient direction magnitudes"},[{histogram:[3,4]},{histogram:[6,8]},{histogram:[0,5]}],div(s("histogram"),norm(s("histogram")))),
  build("keypoints-and-descriptors","Compare the query descriptor with each candidate. Accept the closest only when its distance is less than 0.8 times the second-closest distance. Return that acceptance decision.",{query:"Query descriptor",candidates:"Candidate descriptors"},[{query:[0,0],candidates:[[1,0],[3,0],[5,0]]},{query:[0,0],candidates:[[1,0],[1.1,0],[5,0]]}],op("greater",[mul(c(.8),op("root",[op("index",[op("gather",[op("distances",[s("query"),s("candidates")]),op("rank",[op("distances",[s("query"),s("candidates")])])]),c(1)])])),op("root",[op("minimum",[op("distances",[s("query"),s("candidates")])])])])),
  build("image-alignment","Which image shift do most matches support? Subtract each source point from its proposed destination, find the median shift on each coordinate, then use that shift to place another point in the destination image.",{originals:"Source points (pixels)",matches:"Proposed matching points (pixels)",point:"Point to align (pixels)"},[{originals:[[1,2],[2,3],[4,5]],matches:[[4,1],[5,2],[30,20]],point:[5,6]},{originals:[[2,3],[0,1],[5,2]],matches:[[1,5],[-1,3],[50,-20]],point:[4,0]}],add(s("point"),op("columnmedian",[sub(s("matches"),s("originals"))])),"Each pair proposes a shift. The incorrect match proposes a very different one, but it cannot move the middle value past the two agreeing matches. Applying that middle shift aligns the new point without trusting the outlier.","This handles translation only, with a majority of exactly agreeing matches. Coordinate medians are a small robust estimator, not the full RANSAC procedure or a solution for rotation and perspective."),
  build("haar-cascades","Build a two-stage rejection rule. The first stage requires a bright-minus-dark rectangle contrast above 2; the second requires the supplied edge response above 1. Both must accept.",{bright:"Bright rectangle pixels",dark:"Dark rectangle pixels",edge:"Second-stage edge response"},[{bright:[3,3],dark:[1,1],edge:2},{bright:[1,1],dark:[1,1],edge:3},{bright:[4,4],dark:[1,1],edge:0}],mul(op("greater",[sub(total(s("bright")),total(s("dark"))),c(2)]),op("greater",[s("edge"),c(1)]))),
  build("pipelines","Fit a centring reference using only the training rows. Apply it to the held-out readings, then run the supplied fitted linear rule on those transformed readings.",{training:"Training readings",test:"Held-out readings",weight:"Fitted weight",bias:"Fitted bias"},[{training:[2,4,6],test:[7,9],weight:2,bias:1},{training:[1,3,5],test:[4,8],weight:2,bias:1}],add(mul(sub(s("test"),mean(s("training"))),s("weight")),s("bias"))),
  build("grid-search","Each candidate has one validation loss per fold. Average within each candidate, choose the lowest mean, then retrieve that candidate's setting. The final test set is absent from this decision.",{losses:"Validation losses by candidate",settings:"Candidate settings"},[{losses:[[3,4,5],[1,3,2],[5,1,6]],settings:[.1,.5,1]},{losses:[[2,2,2],[4,1,4],[1,1,2]],settings:[.1,.5,1]}],op("index",[s("settings"),op("argmin",[op("rowmean",[s("losses")])])])),
  build("feature-importance","The model is fixed. Calculate how much its mean squared error increases when the height values are shuffled.",{height:"Original heights",shuffled:"Shuffled heights",targets:"Known answers"},[{height:[1,2,3],shuffled:[3,1,2],targets:[2,4,6]},{height:[2,4,6],shuffled:[6,2,4],targets:[4,8,12]}],sub(mean(square(sub(mul(s("shuffled"),c(2)),s("targets")))),mean(square(sub(mul(s("height"),c(2)),s("targets")))))),
  build("shapes-and-flattening","The input contains two images, each with two rows of three pixels. Build a two-row batch with six features per image, keeping every pixel in its original order.",{images:"Two image arrays"},[{images:[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]},{images:[[[0,1,0],[1,0,1]],[[2,3,2],[3,2,3]]]}],op("reshape",[op("flatten",[op("flatten",[s("images")])])],{columns:6})),
  build("hopfield-network","Repair the first bit from the other bits' weighted vote. The diagonal weight is zero, so the corrupted bit should not vote for itself.",{state:"Current memory state",weights:"First bit's incoming weights"},[{state:[-1,1,-1],weights:[0,1,-1]},{state:[1,-1,1],weights:[0,1,-1]}],op("sign",[op("dot",[s("state"),s("weights")])])),
  build("restricted-boltzmann-machine","Construct hidden probabilities from the visible state, compare them with the supplied uniform draws to sample hidden bits, then reconstruct visible probabilities with the transposed connections.",{visible:"Visible state",weights:"Hidden-by-visible weights",draws:"Uniform draws"},[{visible:[1,0],weights:[[1,-1],[.5,.5]],draws:[.2,.8]},{visible:[0,1],weights:[[1,-1],[.5,.5]],draws:[.7,.1]}],op("sigmoid",[op("matvec",[op("transpose",[s("weights")]),op("greater",[op("sigmoid",[op("matvec",[s("weights"),s("visible")])]),s("draws")])])])),
  build("convolution","Slide a 2 by 2 kernel across the image with stride 1. Build the dot product for every flattened window, returning the four responses in row order. This uses the cross-correlation convention common in neural networks.",{image:"Image",kernel:"Flattened kernel"},[{image:[[1,2,3],[4,5,6],[7,8,9]],kernel:[1,0,0,-1]},{image:[[0,1,0],[1,2,1],[0,1,0]],kernel:[1,0,0,-1]}],op("matvec",[op("windows",[s("image")],{size:2,stride:1}),s("kernel")])) ,
  build("pooling","Build non-overlapping 2 by 2 max pooling. Each output should keep the strongest value in its own window.",{image:"Feature map"},[{image:[[1,3,2,4],[0,2,1,3],[5,2,6,1],[4,3,2,0]]},{image:[[2,0,1,1],[1,4,3,2],[0,1,5,2],[3,2,1,4]]}],op("rowmax",[op("windows",[s("image")],{size:2,stride:2})])),
  build("convolutional-networks","Build one small feature extractor: slide the supplied kernel, discard negative responses, then keep the largest surviving response for this image.",{image:"Handwritten stroke image",kernel:"Supplied stroke filter"},[{image:[[1,0,0],[1,1,0],[0,0,0]],kernel:[1,0,1,0]},{image:[[0,1,0],[0,1,0],[0,0,1]],kernel:[1,0,1,0]}],op("maximum",[op("relu",[op("matvec",[op("windows",[s("image")],{size:2,stride:1}),s("kernel")])])])),
  build("u-net","The decoder has a coarse map, while an earlier encoder layer kept fine detail. Upsample the coarse map by two, flatten both maps, and concatenate the fine features before the coarse features for the next learned layer.",{fine:"Cell detail from the encoder",coarse:"Coarse cell features from the decoder"},[{fine:[[1,0],[0,1]],coarse:[[2]]},{fine:[[0,1],[1,0]],coarse:[[3]]}],op("concatenate",[op("flatten",[s("fine")]),op("flatten",[op("upsample",[s("coarse")],{factor:2})])]),"The skip path brings back features at the required resolution. U-Net learns its segmentation from images paired with labelled pixel masks.","This builds one skip connection. A full U-Net concatenates channels at matching spatial positions, then learns further convolutions; flattening here only makes the two feature groups easy to inspect."),
  build("a-vector-for-a-picture","Two feature maps describe the image. Average each map's responses, then normalise the resulting image vector so overall size does not dominate comparison.",{maps:"Flattened feature maps"},[{maps:[[1,2,3,2],[0,1,0,1]]},{maps:[[2,4,6,4],[0,2,0,2]]}],div(op("rowmean",[s("maps")]),norm(op("rowmean",[s("maps")])))),
  build("learning-the-metric-itself","Build the triplet loss from the anchor, matching example and nonmatching example. Use squared distances, margin 1, and stop the loss at zero when the margin is already satisfied.",{anchor:"Anchor vector",positive:"Matching vector",negative:"Nonmatching vector"},[{anchor:[0,0],positive:[1,0],negative:[.5,0]},{anchor:[0,0],positive:[.5,0],negative:[2,0]}],op("relu",[add(sub(total(square(sub(s("anchor"),s("positive")))),total(square(sub(s("anchor"),s("negative"))))),c(1))])),
  build("searching-a-collection-of-pictures","Find the closest stored image vector, then return its image ID. Keep the descriptors separate from the identifiers they point to.",{query:"Query image vector",vectors:"Stored image vectors",ids:"Stored image IDs"},[{query:[.9,1.1],vectors:[[0,0],[1,1],[2,0]],ids:[12,34,56]},{query:[1.8,.1],vectors:[[0,0],[1,1],[2,0]],ids:[12,34,56]}],op("index",[s("ids"),op("argmin",[op("distances",[s("query"),s("vectors")])])])),
];}
